### ISSUE TITLE
An error occurred while initializing the youtube player.

### ISSUE THREAD

**Issue by dozel** [inProgress-team/react-native-youtube#100]
I've added the following code in the RN project, but keep getting the 'An error occurred while initializing the youtube player.' error only on Android (emulator). On iphone it runs beautifully.

<YouTube
                  ref="youtubePlayer"
                  videoId="KVZ-P-ZI6W4" // The YouTube video ID
                  play={true}           // control playback of video with true/false
                  hidden={false}        // control visiblity of the entire view
                  playsInline={false}    // control whether the video should play inline
                  loop={false}          // control whether the video should loop when ended
                  apiKey={'API_KEY'}
                  style={{alignSelf: 'stretch', height: 300, backgroundColor: 'black', marginVertical: 10}}
                />

What could be the possible problems causing this error?

Thanks!

**Comment by labithiotis** [comment]
I'm also experiencing the same issue on RN0.36. I have followed the readme to the letter and recompiled the app and still have the issue.

**Comment by ilyadoroshin** [comment]
same for me.. does it have anything to do with running it on emulator? Is it even possible to make it work in emulator? 
#97

**Comment by morelazers** [comment]
@ilyadoroshin I can't remember if I managed to get it to work in android emulator. I think that you need the YouTube app installed on the device for it to function on Android. I am not sure if you can install the app on emulator.

If you have a device to test on definitely try that instead. Otherwise the iOS simulator should work.

**Comment by ilyadoroshin** [comment]
@morelazers YouTube app worked splendidly! Thanks!

**Comment by bilal-tariq786** [comment]
add the below lines of code into your android AndroidManifest.xml file

  <queries>
    <intent>
      <action android:name="com.google.android.youtube.api.service.START" />
    </intent>
  </queries>

**Comment by BilalTariq01** [comment]
> add the below lines of code into your android AndroidManifest.xml file
> 
> ```
>   <queries>
>     <intent>
>       <action android:name="com.google.android.youtube.api.service.START" />
>     </intent>
>   </queries>
> ```

https://stackoverflow.com/a/66330541/15265413
