### ISSUE TITLE
unable to hide youtube button ?

### ISSUE THREAD

**Issue by keyurparalkar** [inProgress-team/react-native-youtube#102]
Hi team,

I am unable to hide the youtbe button which is present at the bottom right of the video. Even when i set
`modestbranding={true}` and `showinfo={false}` still I am not able to remove the youtube button ?
here is my code 

`
<YouTube
               videoId="videoId"
               play={this.state.isPlaying}
               hidden={false}
               playsInline={true}
               showinfo={false}
               modestbranding={true}
               apiKey="SAMPLE_API_KEY"
               onReady={(e)=>{this.setState({isReady: true})}}
               onChangeState={(e)=>{this.setState({status: e.state})}}
               onChangeQuality={(e)=>{this.setState({quality: e.quality})}}
               onError={(e)=>{this.setState({error: e.error})}}
               style={{alignSelf: 'stretch', height: 250, backgroundColor: 'black', marginVertical: 10}}
             />
`

**Comment by davidohayon669** [comment]
@keyurparalkar iOS or Android?

**Comment by keyurparalkar** [comment]
Android

**Comment by davidohayon669** [comment]
@keyurparalkar this is not possible on the Android implementation

**Comment by keyurparalkar** [comment]
So there is no way I can do it?

**Comment by davidohayon669** [comment]
@keyurparalkar The Android implementation uses [this official Youtube Android API library](https://developers.google.com/youtube/android/player/). You can learn about possible options there. AFAIK the youtube button is permanent
