### ISSUE TITLE
Unauthorized Overlay in Android

### ISSUE THREAD

**Issue by dozel** [inProgress-team/react-native-youtube#103]
Has anyone figured out how to deal with unauthorized overlay error in Android? 

Is it an order-placement issue? Should I display it modally? What's the solution here?

**Comment by dozel** [comment]
The only solution I can come up with is to present it Modally. I would rather not do that.

**Comment by davidohayon669** [comment]
@dozel To my knowledge the Android YouTube API will always pause if it is covered even partially by other views or cropped inside a scrollable view. You should plan your UI/UX around this limitation.

Another option would be to implement this player in Android as an embedded WebView that holds the generic html iFrame like its being done in iOS. I guess then the iFrame has no knowledge about being covered so you would get the same functionality as in the iOS implementation.

I would might do this in the future in my repository or this one if my version would be merged

**Comment by flowkraD** [comment]
@dozel , may I know how you can get around this issue using Modal?
I am trying to implement the same but it just doesn't seem to work

**Comment by dozel** [comment]
@flowkraD I ended up just using a WebView to show the youtube video. So if iOS, use this library, if Android, use a webview.
