### ISSUE TITLE
[FEATURE] Play video without sound (mute)

### ISSUE THREAD

**Issue by max-mykhailenko** [inProgress-team/react-native-youtube#106]
It will be great to control video volume or just mute/unmute

**Comment by davidohayon669** [comment]
@max-mykhailenko Since this is not a cross platform method (possible only on iOS), and I don't think is too important to be implemented only for iOS, I'll have to ignore this for now.

**Comment by filipef101** [comment]
How could I do this? I really need this option, and ios only

**Comment by filipef101** [comment]
@max-mykhailenko did you solve that?

**Comment by tarasfo** [comment]
@filipef101 you can check https://github.com/inProgress-team/react-native-youtube/pull/346

**Comment by max-mykhailenko** [comment]
@filipef101 you should try another lib

**Comment by max-mykhailenko** [comment]
We use fork https://github.com/davidohayon669/react-native-youtube
