### ISSUE TITLE
Video auto pause when screen rotates

### ISSUE THREAD

**Issue by nhcuong95** [inProgress-team/react-native-youtube#111]
When my screen rotates from portrait mode to landscape mode, the video is paused. It should keep playing like a native youtube video player but I don't know how to fix it. Anyone have an idea about this problem?

Thanks

**Comment by deqyd** [comment]
Yea, I am having a similar problem. It rebuffers (reloads) the video if the device is rotated.

**Comment by davidohayon669** [comment]
Version? Platform?

**Comment by kamalk333** [comment]
I had this similar issue, v0.41 android (marshmallow)

**Comment by swaroopaillinda** [comment]
@nhcuong95 how did you solve the issue?
