### ISSUE TITLE
Android FullScreen Hardware Back Button locks orientation to landscape

### ISSUE THREAD

**Issue by edencakir** [inProgress-team/react-native-youtube#114]
When user makes the player full screen and quits via pressing hardware back button, orientation locks to landscape. In addition to that, if user quits and kills the app, he sees the video player full screen just as it was left.

I'm using the latest version of react-native-youtube and RN 0.40

**Comment by gorjanz** [comment]
Any news on a fix for this issue?
perhaps in the v1 pull request?

**Comment by ziyafenn** [comment]
> Here: https://github.com/inProgress-team/react-native-youtube/blob/master/android/src/main/java/com/inprogress/reactnativeyoutube/YouTubeView.java#L52
> 
> I've added the following code:
> 
> ```
> getReactContext().getCurrentActivity()
>                 .setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
> ```
> since my application is in Portrait mode all the time. In a more complicated case, you would need some kind of means of checking what orientation to go back to.
> 
> hope this helps.

I'm getting error in my console:
```

> Task :react-native-youtube:compileDebugJavaWithJavac
/Users/zia/dev/proclubs/mobile/node_modules/react-native-youtube/android/src/main/java/com/inprogress/reactnativeyoutube/YouTubeView.java:52: error: invalid method declaration; return type required
    getReactContext().getCurrentActivity()
    ^
/Users/zia/dev/proclubs/mobile/node_modules/react-native-youtube/android/src/main/java/com/inprogress/reactnativeyoutube/YouTubeView.java:52: error: ';' expected
    getReactContext().getCurrentActivity()
                     ^
2 errors
```
