### ISSUE TITLE
Not working with React Native 0.42

### ISSUE THREAD

**Issue by salmankhann** [inProgress-team/react-native-youtube#115]
Since the example does not work with RN 0.42, I updated the Examples project to use React Native 0.42 and also used React Native Youtube 0.8.1 from master for it work. Everything compiles fine and runs but it is stuck at 'Player setting up' with a white background (instead of black). There are not compile errors or runtime errors except this one:
Received error rendering template: Error Domain=NSCocoaErrorDomain Code=258 "The file name is invalid."

Any ideas what am I missing in order to make the example work? I intend to PR the examples project once it starts working.

Thanks

@paramaggarwal @georgiana-gligor @jujumoz

**Comment by salmankhann** [comment]
Got the error, it was that I didn't that the html file referenced from the Assets folder. I'll create a PR for the examples project once @jujumoz releases 0.8.1.

**Comment by gemma-ferreras** [comment]
@salmankhann i got the same issue, where did you referenced it? can you give me an example? thanks

**Comment by jmuziki** [comment]
Hi, can you confirm whether this module works with RN 0.42. I was running version 1.0.0.alpha and the video does not load. 

![screen shot 2017-05-12 at 1 46 56 pm](https://cloud.githubusercontent.com/assets/7222660/25996942/1eb308fa-371a-11e7-8377-c2ed87907970.png)


I downgraded to version 0.8.1 and that doesn't seem to solve the issue. The player ran fine on initial installation then stopped working at some point.

**package.json**

  "dependencies": {
    "apisauce": "^0.10.0",
    "format-json": "^1.0.3",
    "lodash": "^4.17.2",
    "native-base": "^2.0.11",
    "querystringify": "0.0.4",
    "ramda": "^0.23.0",
    "react": "~15.4.1",
    "react-native": "0.42.0",
    "react-native-animatable": "^1.1.1",
    "react-native-config": "^0.2.1",
    "react-native-device-info": "^0.10.0",
    "react-native-drawer": "^2.3.0",
    "react-native-elements": "^0.11.2",
    "react-native-i18n": "^1.0.0",
    "react-native-percentage-circle": "^1.0.6",
    "react-native-vector-icons": "^4.0.1",
    "react-native-youtube": "^0.8.1",
    "react-navigation": "^1.0.0-beta.7",
    "react-redux": "^5.0.2",
    "redux": "^3.6.0",
    "redux-persist": "^4.1.0",
    "redux-saga": "^0.14.3",
    "reduxsauce": "0.4.1",
    "seamless-immutable": "^7.0.1"
  }
