### ISSUE TITLE
The "rel" property default value seems set to "false"?

### ISSUE THREAD

**Issue by wellyshen** [inProgress-team/react-native-youtube#125]
As the README file describing that the `rel` property default is `false`, but if I don't set the `rel={false}` in my youtube component, the relative videos will show up. It seems the default value is `false`, am I correct?

**Comment by davidohayon669** [comment]
have you tried next version?
`npm i react-native-youtube@1.0.0-alpha.3 -S`

[README](https://github.com/inProgress-team/react-native-youtube/blob/v1/README.md)

**Comment by wellyshen** [comment]
@davidohayon669 I tried it, it works as README file, thanks.
