### ISSUE TITLE
Flowtype error

### ISSUE THREAD

**Issue by wellyshen** [inProgress-team/react-native-youtube#126]
Thank you for this great library, it really help me a lot. But the library will cause some flowtype errors, now I ignore `.*/node_modules/react-native-youtube/.*.ios.js` in my `.flowconfig`, does anyone have greater solution for it?

My flow version is 0.40.0

**Comment by davidohayon669** [comment]
[flow typed](https://github.com/flowtype/flow-typed/tree/ee680e3aa4209b7b54caf0dbf0749ba309b51a67/definitions/npm/react-native-youtube_v1.x.x/flow_v0.53.x-)
