### ISSUE TITLE
Feature request: Hide annotations with iv_load_policy ?

### ISSUE THREAD

**Issue by GedoonS** [inProgress-team/react-native-youtube#127]
The web player offers a parameter to hide annotations: [iv_load_policy](https://developers.google.com/youtube/player_parameters#iv_load_policy). Could it be implemented in the RN module as well? So that giving ivLoadPolicy={3} has the same effect as the web player, it hides the annoying-tations from the player...

**Comment by davidohayon669** [comment]
ill look at it soon..

**Comment by davidohayon669** [comment]
@GedoonS https://www.theverge.com/2017/3/16/14953756/youtube-annotations-feature-discontinue-cards-end-screens
