### ISSUE TITLE
Black screen when jumping a new page

### ISSUE THREAD

**Issue by YuanSyun** [inProgress-team/react-native-youtube#129]
**My question**
Hello , YOUTUBE will be black when I jump on the new page. But YOUTUBE can play the video after the screen is reopened.

**My solution**
Do not jump pages.
First hide the contents of the original page, after the show YOUTUBE player in original page.

**Comment by SteveJohnstone** [comment]
I was getting this as well. The work around I used was to add the following to componentDidMount, and use the height and width from the state in my styles:

```
    // TODO: There's a bug with drawing the video after load, so we need to do this.
    var counter = 0
    this.timer = setInterval(() => {
      this.setState({
        width: width,
        height: height + Math.floor(Math.random() * 2)
      })
      counter++
      if (counter > 3) clearInterval(this.timer)
    }, 500)
```

**Comment by cinder92** [comment]
same issue here

RN 0.49.3
Plugin V Latest

**Comment by davidohayon669** [comment]
@cinder92 Can you describe the problem more?

**Comment by IacoCesar** [comment]
same issue here on RN 0.57.6 using tab navigation of react-navigation

**Comment by IbrahimCanKALYA** [comment]
@lacoCesar did you any solution for this problem getting this problem to.
if u find any solution could u share it ?
thanks in advence
