### ISSUE TITLE
seekTo method is undefined

### ISSUE THREAD

**Issue by Jarrio** [inProgress-team/react-native-youtube#135]
I want to be able to set the time but for some reason I do not get access to the `seekTo` method. Printing the reference shows the following:
![image](https://cloud.githubusercontent.com/assets/748557/24316671/f33e894a-10e7-11e7-873b-02d6904c0ccc.png)

And making a reference to it in code via `this.refs.youtubePlayer.seekTo()` (I do null check). I get the following error:

![image](https://cloud.githubusercontent.com/assets/748557/24316737/7031d588-10e8-11e7-8cf0-3ff91ad0f26c.png)

My `youtube.android.js` file is up to date and has the same `3 references` to the seekTo method as does the github so I'm not sure what I'm doing wrong here. Anyone else have any input? I *am* new to react-native so maybe I'm making a reference to the seekTo method wrong here?

**Comment by SteveJohnstone** [comment]
I'm not quite sure how seekTo ever worked. When looking in the YouTubePlayerController I found this:

```
    @Override
    public void onSeekTo(int i) {

    }
```

So it looks like the manager calls the view, the view calls the controller, and the controller does nothing. Plus I'm reasonably sure that you can't call methods on UI components in the way that is currently being done, but I'm still investigating that.

**Comment by davidohayon669** [comment]
This method is implemented on both platforms the v1 branch

**Comment by iDams** [comment]
Having the same issue. But the error is `Cannot read property 'seekTo' of undefined` which means that the ref `youtubePlayer` is not defined. Nothing to do with the `seekTo` function I think.

**Comment by DannyAziz** [comment]
Having the same issue, only on android works perfectly on iOS

**Comment by iDams** [comment]
Using [v1 branch](https://github.com/inProgress-team/react-native-youtube/tree/v1) fixed it for me

**Comment by DannyAziz** [comment]
@iDams using v1 branch, not getting the error but seekTo does nothing

**Comment by iDams** [comment]
Is your video playing when you're trying to seekTo? If it's on paused/stopped, the video will not start with seekTo.

> If the player is paused or stopped when this function is called, the player will remain remain in the same state, but will start the video at the sought-to position when playback resumes.

https://developers.google.com/youtube/android/player/reference/com/google/android/youtube/player/YouTubePlayer#seekToMillis(int)

**Comment by DannyAziz** [comment]
@iDams Perfect, that helped a lot thanks. I was attempting to get the video to start at a particular time and was using the `onReady` event to seek forward but it wasn't actually playing when `onReady` is called. Instead, I used `onChangeState` when the state equals `started`. Just thought I should leave this here in case anyone else gets stuck trying to do something similar

**Comment by Jarrio** [comment]
I had to stop working on this project so I couldn't try test things further. I still seem to not be able to make `seekTo` work with the `v1` branch, I updated and I see the following in my `android.js` file:
```javascript
  seekTo(seconds) {
    UIManager.dispatchViewManagerCommand(
      ReactNative.findNodeHandle(this._nativeComponentRef),
      UIManager.ReactYouTube.Commands.seekTo,
      [parseInt(seconds, 10)],
    );
  }```

My reference no longer throws `Cannot read property seekTo` with the v1 branch, but it still doesn't do anything for me whilst playing the video. I can't seem to find `seekTo` in the refs list either. (I trace when the `state` changes to `playing` just to be extra sure)

**Comment by Jarrio** [comment]
Update:

It seems like setting `controls=2` means that I can't use the `seekTo` method! This is really awkward, is this due to the youtube plugin or native android? I don't want to provide the full access to the control scheme if at all possible
