### ISSUE TITLE
Auto Play in Fullscreen on iOS is not working

### ISSUE THREAD

**Issue by juergengunz** [inProgress-team/react-native-youtube#136]
The player does not switch to fullscreen automatically even though I put playsInline={false} to false. It plays inline instead.

**Comment by salmankhann** [comment]
did you manage to fix this ?

**Comment by salmankhann** [comment]
@jujumoz I've created a new pull request to address this for iOS 10. Please merge

**Comment by jujumoz** [comment]
@juergengunz @salmankhann done !
