### ISSUE TITLE
Error service_missing 

### ISSUE THREAD

**Issue by fabiancarlos** [inProgress-team/react-native-youtube#137]
having a error service_missing ?? How do i debug that?

**Comment by davidohayon669** [comment]
If it means that a YouTube app isn't present on the device (Android)

**Comment by fabiancarlos** [comment]
Yes, you are right, on my cellphone works!

**Comment by wcandillon** [comment]
@davidohayon669 Does this means that it is a requirement for the phone to have the youtube app installed on the phone?

**Comment by fabiancarlos** [comment]
Yes!

**Comment by cyb3rsalih** [comment]
How we can handle that with open the youtube url in default browser?
