### ISSUE TITLE
Play prop only works on load

### ISSUE THREAD

**Issue by bmeverett** [inProgress-team/react-native-youtube#138]
The play prop seems to only work when the view is loaded. Once the view is loaded it does not stop the video when set to `false`. Is there a way to expose the YouTube [playVideo](https://github.com/inProgress-team/react-native-youtube/blob/master/YTPlayerView/YTPlayerView.m#L101-L103) and [stopVideo](https://github.com/inProgress-team/react-native-youtube/blob/master/YTPlayerView/YTPlayerView.m#L110-L112) functions to play and stop the video in code?

Edit: I see that it already may be done [here](https://github.com/inProgress-team/react-native-youtube/blob/master/RCTYouTube.m#L105-L120) but doesn't seem to be working when setting play to `false`.

**Comment by davidohayon669** [comment]
try `npm i react-native-youtube@1.0.0-alpha.3`

[README](https://github.com/inProgress-team/react-native-youtube/blob/v1/README.md)

**Comment by GutteApps** [comment]
this still happens on 1.1.0. play={false} is ignored on iOS after initial load. suggested alpha doesn't work.
