### ISSUE TITLE
ios only: onFullScreenEnter and onFullScreenExit not working in the V1 branch

### ISSUE THREAD

**Issue by larryranches** [inProgress-team/react-native-youtube#140]
The onFullScreenEnter and onFullScreenExit functions are NOT working in the V1 branch but it DOES work in Master. Also the functions are working for Android in the V1 branch.

Any ideas?

**Comment by davidohayon669** [comment]
those events are not implemented in v1 yet.
I'll probably add it to my next round of finish-ups in coming days

**Comment by larryranches** [comment]
@davidohayon669 Thanks! Please update when you can, it's a feature that is needed in my project.

**Comment by larryranches** [comment]
@davidohayon669 Thank you sooo much!
