### ISSUE TITLE
[V1] How to add a getter for currentTime on Android?

### ISSUE THREAD

**Issue by iDams** [inProgress-team/react-native-youtube#145]
Hi,

Since `onProgress` is not available on Android, I would need to get the current time of the video on Android.
I've tried to add it but I got stucked when I need to call the getter from `YoutubeManager.java` in `Youtube.android.js`.

I've done this:
```
// YoutubePlayerController.java
public int getCurrentTime() {
        return mYouTubePlayer.getCurrentTimeMillis() / 1000;
    }
```

```
// YoutubeView.java
public int getCurrentTime() {
        return mYoutubeController.getCurrentTime();
    }
```

```
// YoutubeManager.java
public int getCurrentTime(YouTubeView view) {
        return view.getCurrentTime();
    }
```

But I don't know how to call the `getCurrentTime()` of `YoutubeManager.java` in `Youtube.android.js`.

If anyone has an idea how to do it, that would be nice!
Maybe @davidohayon669?

Thanks!

**Comment by davidohayon669** [comment]
Methods with returned values should be implemented as a promise like `videosIndex()`

Look at how `videosIndex()` is implemented at `YouTubeModule.java`

I can probably look at it only in few days

**Comment by iDams** [comment]
@davidohayon669 thanks.

I did a PR [here](https://github.com/inProgress-team/react-native-youtube/pull/146) in case you want to merge it.
