### ISSUE TITLE
unauthorized overlay  top of player and there are only a framelayout on xml 

### ISSUE THREAD

**Issue by rahmamajed** [inProgress-team/react-native-youtube#147]
i have this error out of unknown 
please note that i discard all views  on my xml and i am getting this error over and over again even of the xml having just framelayout to display youtube fragment 

 YouTubeAndroidPlayerAPI: YouTube video playback stopped due to unauthorized overlay on top of player. The YouTubePlayerView is obscured by com.google.android.youtube.player.YouTubePlayerView{1aa23167 V.E..... ........ 0,0-1080,607}. YouTubePlayerView is completely covered, with the distance in px between each edge of the obscuring view and the YouTubePlayerView being: left: 0, top: 0, right: 0, bottom: 0..

please help me it happend to me in two fragment and i am discarding all xml views i just put framelayout

**Comment by davidohayon669** [comment]
What version?
