### ISSUE TITLE
Does not autoplay when change video ID

### ISSUE THREAD

**Issue by longtranista** [inProgress-team/react-native-youtube#148]
I have implemented a player which allowing play by a playlist. 
When clicking on the next button, the video ID will change to next video ID, 
The youtube player loads the new video successfully but not autoplay. 
Any helps?

**Comment by davidohayon669** [comment]
do you `play={true}`?

**Comment by longtranista** [comment]
Yes, but  play={true} only effect when first init, it does not effect on the fly

**Comment by davidohayon669** [comment]
@longtranista paste the full JSX
