### ISSUE TITLE
Video List Feature

### ISSUE THREAD

**Issue by marcosschroh** [inProgress-team/react-native-youtube#149]
Hi,

Thanks for this good plugin. I was wondering whether is possible to add support to youtube video list. 

For example, given the following URL:
https://www.youtube.com/embed/VIDEO_ID?playlist=aaaaaa,bbbbb,cccccc

After the main video was finished, continue with the list of videos in the playlist.

Best regards.

**Comment by davidohayon669** [comment]
`npm i react-native-youtube@1.0.0-alpha.3`

[docs here](https://github.com/inProgress-team/react-native-youtube/tree/v1)
