### ISSUE TITLE
On Android 4.2 video works only after rotation.

### ISSUE THREAD

**Issue by oky1** [inProgress-team/react-native-youtube#151]
PlaysInline cause of fail in Android 4.2. RN 4.3
PlaysInline was 'dropped'... ( message).
I removed playsInline. Video works only after rotation.

**Comment by davidohayon669** [comment]
On v1 I changed `playsInline` to `fullscreen` which is exactly the same only opposite. It just makes more sense like that

**Comment by oky1** [comment]
I tried fullscreen. 
fullscreen={true}  Video working. 
fullscreen={false}  Loading with delay.  Video not working ( works only after rotation)

**Comment by hasaezs** [comment]
@oky1 @davidohayon669 I have the same issue, any solution for this? Android 4.4, react-native@0.43.3

**Comment by davidohayon669** [comment]
Try installing the example in the v1 repo and reproduce what you are doing, if the same error persists let me know what exactly happened

**Comment by nmartin867** [comment]
V1 is working well for me.
