### ISSUE TITLE
[v1] BackAndroid is deprecated. Please use BackHandler instead.

### ISSUE THREAD

**Issue by joncursi** [inProgress-team/react-native-youtube#154]
I get this yellowbox warning on android when this module is loaded. This looks like the culprit:

https://github.com/inProgress-team/react-native-youtube/blob/v1/YouTube.android.js#L13

**Comment by davidohayon669** [comment]
I'll probably get to it sometime

**Comment by yogieputra8** [comment]
https://github.com/react-community/react-navigation/issues/1330

**Comment by davidohayon669** [comment]
#177
