### ISSUE TITLE
Could not play on Android Pausing after 1 second everytime I plays

### ISSUE THREAD

**Issue by Dineshchitta** [inProgress-team/react-native-youtube#155]
Info : 

 "react-native-youtube": "^1.0.0-alpha.3"
 "react": "~15.4.0-rc.4",
    "react-native": "0.42.3"

Usage :

<YouTube
          youtubeVideoId={'myYoutubeVideoId'}
          play
          hidden={false}
          playsInline
          loop={false}
        />

Working in Full screen.

**Comment by davidohayon669** [comment]
What version? Plus there is no `youtubeVideoId` property

**Comment by Dineshchitta** [comment]
sorry.It is videoId only. Which package version you are asking. react-native-youtube ? You can find it in above comment. 

"react-native-youtube": "^1.0.0-alpha.3"

**Comment by davidohayon669** [comment]
try to log errors `onError={e => console.log(e.error)}`

**Comment by Dineshchitta** [comment]
When I Worked on it again. This time I got error like playsInline prop is dropped like that.So I Removed that prop and now it is playing continuously.

**Comment by Dineshchitta** [comment]
When I Worked on it again. This time I got error like playsInline prop is dropped like that.So I Removed that prop and now it is playing continuously.
