### ISSUE TITLE
Expo support?

### ISSUE THREAD

**Issue by berdof** [inProgress-team/react-native-youtube#158]
I tried out to use this library with expo but stuck with an error.
Are there any plans for expo support?

**Comment by davidohayon669** [comment]
I'm not familiar with Expo.
If anybody is willing to add the support, you're welcome

**Comment by mikelambert** [comment]
AFAIK, Expo is a way to run apps that don't require native-linked libraries. RN-YT is a native-linked library, so it won't work in Expo. Unless Expo decides to include RN-YT (and you'd have to discuss that with the Expo team). Or unless you decide to export your Expo app to ExponentKit (I think that's the correct route.)

You're of course welcome to use the YT iframe in a RN WebView, which I believe should work within an Expo app. But will be a bit less "native" feeling.

**Comment by reergymerej** [comment]
https://stackoverflow.com/questions/44891650/how-to-play-youtube-videos-using-expo

**Comment by sin2** [comment]
If anyone is having issues with a detached Expo app, make sure to add an appropriate path to  **Pods/Headers/Public** under **Header Search Paths** for the RCTYouTube target in your project.

https://docs.expo.io/versions/latest/guides/expokit.html#changing-native-dependencies
