### ISSUE TITLE
Black screen after scrolling down and coming back to video view

### ISSUE THREAD

**Issue by Dineshchitta** [inProgress-team/react-native-youtube#159]

**Comment by davidohayon669** [comment]
Not enough background info

**Comment by Dineshchitta** [comment]
Versions : 

    "react-native-youtube": "^1.0.0-alpha.4",
    "react": "~15.4.0-rc.4",
    "react-native": "0.42.3",

I integrated youtube player as given example in readme.md. When I opened it works fine. When I scroll down and come back that video player is becoming black . I am putting that view in ListView

**Comment by moorthysubu** [comment]
Yes. Am also facing the same issue. anyone knows the solution for this? @Dineshchitta

**Comment by Dineshchitta** [comment]
Nope .  We couldn't figure out why it is happening @moorthysubu

**Comment by Dineshchitta** [comment]
@davidohayon669 When I tried with normal scrollview it worked fine. But when I put it in ListView I am getting that issue

**Comment by davidohayon669** [comment]
@Dineshchitta To my understanding, the components in a ListView gets mounted and unmounted to save memory. Try `removeClippedSubviews={false}` on the ListView, but this doesn't sound like a problem with this package
