### ISSUE TITLE
How to stop video and lave fullscreen

### ISSUE THREAD

**Issue by bernatfortet** [inProgress-team/react-native-youtube#164]
I want to programatically stop the video and minimze/leave fullscreen when it reaches a specific time.

How could I do that?

Thanks.

**Comment by wellyshen** [comment]
@bernatfortet use a state to control the property of fullscreen.

**Comment by davidohayon669** [comment]
Probably a combination of `onProgress` on iOS / `currentTime` on Android and some custom code. This kind of functionality is not a part of the component's API

**Comment by yspychala** [comment]
I guess you can use the remaining time using the onProgress event. For example:

```
state = {
   isFullscreen: true,
};
```

```
<YouTube
   ...
   fullscreen={this.state.isFullscreen}
   onProgress={this._onProgress}
/>
```

Set the remaining time (10s before the end).
```
_onProgress = ({currentTime, duration}) => {
   const remaining = Math.floor(duration - currentTime);
   if (remaining === 10) {
      this.setState({isFullscreen: false});
   }
}
```

And you can use the state to also stop the video.

**Comment by bernatfortet** [comment]
@davidohayon669, @yspychala have you tried these solutions?

When I try to make the fullscreen prop dynamic it doesn't work.

**Comment by davidohayon669** [comment]
@bernatfortet The iOS version cannot change fullscreen mode through the API without `reloadIframe()`. The fullscreen prop is a parameter that is used in the initiation of the inner iFrame and when replacing it you should also initiate a refresh of the inner iFrame

**Comment by bernatfortet** [comment]
Got it. I'll give it a try
