### ISSUE TITLE
Android onProgress method alternative

### ISSUE THREAD

**Issue by die20** [inProgress-team/react-native-youtube#170]
Hey, 

I'm looking to use this library for a cross-platform app but I noticed that onProgress is not supported on android. Are there any alternatives to getting the current video time on android?

**Comment by die20** [comment]
I just noticed that on Youtube.Android.js there is a currentTime() method, could it be that the docs are just not updated to show currentTime() is available on Android?

**Comment by davidohayon669** [comment]
Done

**Comment by die20** [comment]
:) Awesome. 

The reason I closed the issue is because I noticed that currentTime was available on android and not on iOS - I'd prefer to have a single method for getting the current time instead of having to use onProgress for iOS and currentTime for android --- So I forked and made an update that exposes currentTime on iOS. 

I'll make a PR in case you want to add it to the plugin as well.
