### ISSUE TITLE
Feature request: setPlaybackQuality

### ISSUE THREAD

**Issue by wellyshen** [inProgress-team/react-native-youtube#173]
Could it possible to add the feature of set playback quality. Some user may care about their data usage, I think this feature is helpful for saving their data usage. Thanks.

**Comment by davidohayon669** [comment]
@wellyshen Since this is not available on Android, and seems like too of a corner case to implement only for iOS, I think we'll have to pass on it. I believe the underlaying iFrame in the iOS component handles quality according to network connection.
