### ISSUE TITLE
How to set playback rate

### ISSUE THREAD

**Issue by maltz** [inProgress-team/react-native-youtube#175]
How do I set playback rate?
This node package can set playback rate.
https://github.com/react-native-community/react-native-video#usage
```
rate={1.5}   
```

Can react-native-youtube set playback rate also?

**Comment by davidohayon669** [comment]
It depends on the platform specific YouTube module

**Comment by maltz** [comment]
Sorry. I talked about not quality but speed.

**Comment by davidohayon669** [comment]
@maltz the official YouTube plugins we use in this component do not provide this kind of functionality

**Comment by Sikandarkhan** [comment]
any update on this feature?

**Comment by mandersondesign** [comment]
> any update on this feature?

I also would love to know if there is an update to the YouTube plugin that would allow this.
