### ISSUE TITLE
example is not working

### ISSUE THREAD

**Issue by barron9** [inProgress-team/react-native-youtube#176]
The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false

Body:
{"from":"/Users/barron9/Downloads/react-native-youtube-master/YouTube.android.js","to":"react","message":"Unable to resolve module `react` from `/Users/barron9/Downloads/react-native-youtube-master/YouTube.android.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start --reset-cache`.","name":"UnableToResolveError","type":"UnableToResolveError","errors":[{}]}
onResponse
    DevServerHelper.java:332
execute
    RealCall.java:126
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1162
run
    ThreadPoolExecutor.java:636
run
    Thread.java:764

**Comment by davidohayon669** [comment]
That is a React Native problem

I would follow the suggestions in the error message
