### ISSUE TITLE
BackAndroid is deprecated. Please use BackHandler instead.

### ISSUE THREAD

**Issue by ishita-kothari** [inProgress-team/react-native-youtube#179]
When implement the youtube package, I am facing the error of backandroid is deprecated. I think navigation has solved this issue but with youtube package I am still facing the error. I can see just the blank black screen in my android device.

The file YouTubeAndroid.js uses backAndroid events.

Dependencies are:
"react-native-youtube": "^1.0.0-alpha.4",
    "react-navigation": "^1.0.0-beta.11",

Please provide me effective solution to make my app running.

Thanks!

**Comment by davidohayon669** [comment]
#177
