### ISSUE TITLE
Not working in Android

### ISSUE THREAD

**Issue by ishita-kothari** [inProgress-team/react-native-youtube#181]
I have "react-native-youtube": "^1.0.0-alpha.4" package. I don't want to play the video in full screen. Once the video exists full screen mode, it stops playing after 1 second.  Can anyone please guide me to solve this issue?

**Comment by ben54260** [comment]
we solve this issue there
#161

**Comment by davidohayon669** [comment]
@ishita-kothari RN version?

**Comment by ishita-kothari** [comment]
@davidohayon669 RN v 0.45.1. In webView I am not able to have full screen option with youtube player. Is there any other solution?

**Comment by davidohayon669** [comment]
@ishita-kothari I'm working on a fix

**Comment by jitendra-Tech** [comment]
android required youtub apiKey
