### ISSUE TITLE
Youtube showing black and white area (React native 0.40 and 0.42)

### ISSUE THREAD

**Issue by shashikant23** [inProgress-team/react-native-youtube#182]
<img width="364" alt="screen shot 2017-06-22 at 12 06 02 am" src="https://user-images.githubusercontent.com/10278617/27400767-cb7477b6-56de-11e7-92d6-174c407b0fe6.png">

**Comment by davidohayon669** [comment]
Did you include the `assets/YTPlayerView-iframe-player.html` in your `.pbsproj`?

`rnpm link` should to it automatically. follow the instructions.

**Comment by shashikant23** [comment]
hi rnpm doesn't work. After following https://github.com/inProgress-team/react-native-youtube/issues/79 it works. Thanks

**Comment by davidohayon669** [comment]
@shashikant23 you need to have rnpm installed on your global npm
