### ISSUE TITLE
Native youtube buttons goes off the screen sometimes.

### ISSUE THREAD

**Issue by kamalk333** [inProgress-team/react-native-youtube#183]
I am facing one issue here on my android platform with react native version 0.41 that sometimes the native youtube buttons gets hidden and sometimes it reappears after reload. 

Don't what is causing this issue to appear. I'm also facing some design issue that the moment I come back from fullscreen mpode the loader shifts itself to bottom right corner. And the option button doesn't work too first time and works after routing to fullscreen mode.

**Comment by davidohayon669** [comment]
#131 #74
