### ISSUE TITLE
App crashes when calling youtubePlayer.currentTime()

### ISSUE THREAD

**Issue by Dineshchitta** [inProgress-team/react-native-youtube#186]
Attempt to invoke interface method int com.google.android.youtube.player.YoutubePlayer.getCurrentTimeMillis()' on a null object reference

YoutubePlayerController : 152 line

Using versions : 
 "react": "~15.4.0-rc.4",
 "react-native": "0.42.3",
 "react-native-youtube": "^1.0.0-alpha.6",

Trying to access like this 

```
<YouTube
        ref={(component) => {
          if (__DEV__) {
            if (component !== null) {
              component.currentTime().then((time) => {
                if (__DEV__) console.log('current Time in player :: >> ', time)
              })
            }
          }
          this.youTubePlayer = component
        }}
      />

```

**Comment by davidohayon669** [comment]
@Dineshchitta seems like you are calling this method too soon. Of course it shouldn't cause a crash but anyway try calling methods after the `onReady` event

**Comment by Dineshchitta** [comment]
yes.Thank you @davidohayon669
