### ISSUE TITLE
controls not in position

### ISSUE THREAD

**Issue by ishita-kothari** [inProgress-team/react-native-youtube#189]
Hello,

Youtube player works fine in my app. When the fullscreen is turned off and the video is playing, the controls are not in position. Changing the state of player, changes the orientation of controls. I have tried the solutions given in other issues but no luck.

 Can anyone help me solve this issue?

Thanks!

**Comment by davidohayon669** [comment]
#74 
try keeping similar problems in one issue

**Comment by ishita-kothari** [comment]
this solution does not seem to work.

**Comment by davidohayon669** [comment]
@ishita-kothari I gave you no solution, I only ask to discuss this problem in the dedicated issue thread
