### ISSUE TITLE
Skipping previous scene without popping onBackPress in Full screen

### ISSUE THREAD

**Issue by Dineshchitta** [inProgress-team/react-native-youtube#191]
I am having 3 scenes flow like this A -> B -> C

A Scene : This is the scene where I will select video

B Scene : In this scene when user clicks play button I will navigate to Scene C

           `NavigationActions.sceneC();`

C Scene : In this scene I will defaultly play youtube video in full screen mode like below 

```
<YoutubePlayer
        videoId={videoId}
        play
        hidden={false}
        loop={false}
        fullscreen
        showFullscreenButton={false}
        onError={(e) => {
          if (__DEV__) console.log('Youtube playing Error', e.error)
        }}
      />
```

Here the problem is After getting into Scene C when I press back button I am directly going to Scene A. And When I select another video I am getting error like navigation state children key conflicts with another child (Seems to be Scene B is still in the stack I guess).  I am using react-native-router-flux for navigation.  Am I doing any thing wrong ? Basically I want to navigate user directly to youtube full screen mode without inline in another scene.

Info : 
    "react": "~15.4.0-rc.4",
    "react-native": "0.42.3",
    "react-native-youtube": "^1.0.0-alpha.4",
    "react-native-router-flux": "3.38.0",

**Comment by davidohayon669** [comment]
@Dineshchitta Is it the hardware Android back button of the back button of the navigation?

iOS and android are a bit different when it comes to the fullscreen mode so I'm afraid you'll have to solve it different for each platform.

Basically the `YouTubeStandaloneAndroid` can accomplish your needs in Android, in iOS you can do stuff a bit different

**Comment by Dineshchitta** [comment]
@davidohayon669 I tried with YoutubeStandaloneAndroid but problem still exist. I tried debugging by putting another normal scene at that time there is no problem.

**Comment by davidohayon669** [comment]
@Dineshchitta so what is the problem now?
