### ISSUE TITLE
Video not starting in ios

### ISSUE THREAD

**Issue by jariwalabhavesh** [inProgress-team/react-native-youtube#192]
I had try react-native-youtube player. It is working with android, but it is not playing video in ios simulator, It shows "An Error occurred. Pleased try again Later". 
Here is screenshot of ios simulator.

![screen shot 2017-07-13 at 11 48 44 am](https://user-images.githubusercontent.com/10993666/28153145-8cce5a6a-67c1-11e7-88c1-2e4442d53be3.png)

Same video is playing in android code.

**Comment by davidohayon669** [comment]
@jariwalabhavesh what props do you send the component?

**Comment by jariwalabhavesh** [comment]
@davidohayon669 
i am using same code provide in example of this library 
```
<YouTube
          ref={component => {
            this._youTubeRef = component;
          }}
          // You must have an API Key for the player to load in Android
          // Un-comment one of videoId / videoIds / playlist.
          // You can also edit these props while Hot-Loading in development mode to see how
          // it affects the loaded native module
          videoId="f6I9y7V-Ibk"
          // videoIds={['HcXNPI-IPPM', 'XXlZfc1TrD0', 'czcjU1w-c6k', 'zV2aYno9xGc']}
          // playlistId="PLF797E961509B4EB5"
          play={this.state.isPlaying}
          loop={this.state.isLooping}
          fullscreen={this.state.fullscreen}
          controls={1}
          style={styles.player}
          onError={e => this.setState({ error: e.error })}
          onReady={e => this.setState({ isReady: true })}
          onChangeState={e => this.setState({ status: e.state })}
          onChangeQuality={e => this.setState({ quality: e.quality })}
          onChangeFullscreen={e =>
            this.setState({ fullscreen: e.isFullscreen })}
          onProgress={
            Platform.OS === 'ios'
              ? e =>
                  this.setState({
                    duration: e.duration,
                    currentTime: e.currentTime,
                  })
              : undefined
          }
        />

```

**Comment by davidohayon669** [comment]
@jariwalabhavesh is it like that for every video? Since the player loads correctly and even the name of the video is given, it seems unlikely to be related to this component. It's probably a problem with the inner YouTube iFrame player or the video itself

**Comment by jariwalabhavesh** [comment]
@davidohayon669: Yes every video facing issue in ios only. In android it is working fine

**Comment by davidohayon669** [comment]
@jariwalabhavesh Don't know what to tell you.. try eliminating some factors to pinpoint the reason

**Comment by ydy1128** [comment]
I am running into the same error and getting 'invalid_param' error in onError().
Could you explain what can cause this?

**Comment by shubhi15** [comment]
I am also getting same error in iOS Simulator does anyone has idea about it?

**Comment by rochapablo** [comment]
Also getting `invalid_param`

```
```

**Comment by ramon90** [comment]
I am getting a white screen on ios, video not starting all

**Comment by rohitpuriji** [comment]
We are facing the same issue of invalid params on ios
{ error: 'invalid_param', target: 1817 }, while running the youtube videos

Although, running well in android and safari browser but in ios it shows video unavailable.

"react": "^16.11.0",
"react-native": "0.60.5",
"react-native-youtube": "^2.0.0",

**Comment by mudit70** [comment]
I have the same issue as reported by Rohit above.
