### ISSUE TITLE
Is there any way to download video for offline purpose??

### ISSUE THREAD

**Issue by jariwalabhavesh** [inProgress-team/react-native-youtube#194]
I want to download video so that user can enjoy it when he/she is offline as well. Is there any way or any feature in player that allows us to download youtube videos in application private space??

**Comment by davidohayon669** [comment]
I guess there are ways to pull the .mp4 file of videos from YouTube, anyway it has nothing to do with this implementation and I also guess is not official

**Comment by jariwalabhavesh** [comment]
@davidohayon669 
Thanks you for response
