### ISSUE TITLE
How stop playing video when navigate to other screen

### ISSUE THREAD

**Issue by lnpquang** [inProgress-team/react-native-youtube#196]
Dear,
Could you please show How stop playing video when navigate to other screen?

Thanks.
Best regards,
LNPQuang

**Comment by DonavanMartin** [comment]
@lnpquang  Did you find a solution for this?

This solution doesn't work: 
`  componentWillMount() {
    ...
    this.props.navigation.addListener('willFocus', (route) => {
      console.log("naviguation changed")
      this.setState({
        paused: true
      });
    });
  }`

**Comment by lnpquang** [comment]
@DonavanMartin Can you try this? It's a long time ago, I'm not sure it's still working or not:

<YouTube
          videoId={video.youtubeId}
          play={this.state.isPlaying}
          fullscreen={false}
          loop={false}
          onReady={e => this.setState({isReady: true})}
          onChangeState={e => this.setState({status: e.state})}
          onChangeQuality={e => this.setState({quality: e.quality})}
          onError={e => this.setState({error: e.error})}

          style={{alignSelf: 'center', height: 200, width: 350}}
          key={video.id}
        />
