### ISSUE TITLE
Manual linking iOS

### ISSUE THREAD

**Issue by archansel** [inProgress-team/react-native-youtube#197]
I have existing iOS native app that use some RN view, I tried to install `react-native-youtube` and link it using `react-native link` and `rnpm link` but not working. I also tried linking it manually but not working too. Can anyone provide how to guide to link this library with existing native app? it would be better if I can use cocoapods

EDIT:
React version 16.0.0-alpha.12
React Native version 0.46.0
React Native YouTube version 1.0.0-beta.1

**Comment by davidohayon669** [comment]
Best thing I can suggest would be to copy this repo to your computer and then install and run `react-native-link` and `rnpm link` in the example app, and watch the diffs between the files in both stages.

Why didn't the linking commands work?

**Comment by archansel** [comment]
> Why didn't the linking commands work?

I think it's because of the project structure, not sure though. I integrate existing native app with RN so I put RN source inside XCode project (not the other way around). Other libraries that required linking work just fine because they provide cocoapods way of linking the library

**Comment by archansel** [comment]
I found workaround, this isn't answer my question but at least I make it work. I use podspec from this PR #142, it was merge before but removed again so I clone the repo to my local folder and add this podspec manually

**Comment by davidohayon669** [comment]
@archansel I've just added the podspec from #142 and updated the npm package. I'm not familiar with pods so please check it and tell me if anything is missing
