### ISSUE TITLE
Status Bar missing after change orientation

### ISSUE THREAD

**Issue by archansel** [inProgress-team/react-native-youtube#198]
Hi, in my app and example app (iOS), everytime I change device orientation (in fullscreen) to landscape and back to portrait again, iOS status bar gone after I toogle the fullscreen (not in fullscreen). Is it bug? or I missed something

**Comment by davidsamacoits** [comment]
Same issue here

**Comment by davidohayon669** [comment]
I'll take a look

**Comment by wack17s** [comment]
hi, any progress with this?

**Comment by davidohayon669** [comment]
@archansel I could not reproduce what you explained. In the example app I always see the status bar trying every kind of sequence of full screen and rotation.

Can you be more specific?

**Comment by archansel** [comment]
@davidohayon669 
![bug](https://user-images.githubusercontent.com/816817/29525064-bf6ed17a-86bb-11e7-845a-b22366bd6aeb.gif)

**Comment by simonvaucher** [comment]
Ah, yes. Probably some problem in React Native, not related to the package.
It happens when switching to fullscreen and THEN rotating. After rotation the status bar is gone.

My solution was to to listen to `onLayout` event and set the status bar as visible using `  StatusBar.setHidden(false);`

It looks a bit like this:
```
...
static onChangeLayout() {
    StatusBar.setHidden(false);
  }
...
render() {
    return (
      <View onLayout={ this.onChangeLayout }>
        <YouTube ... />
     </View>
  );
}
```

**Comment by askielboe** [comment]
I'm seeing the same issue. Workaround by @simonvaucher seems to work ok..

**Comment by VesperDev** [comment]
+1
