### ISSUE TITLE
How to get video duration on Android?

### ISSUE THREAD

**Issue by hasaezs** [inProgress-team/react-native-youtube#199]
Hi!

I need to get the total duration of a video and I'm not clear how to do it, without using Youtube Data API.

I was researching a bit and in the documentation of Youtube API Player is the method [getDurationMillis](https://developers.google.com/youtube/android/player/reference/com/google/android/youtube/player/YouTubePlayer#getDurationMillis()) but my implementation was not successful.

Is there any way to implement this correctly? It is only implemented on iOS and is required on android too.

My implementation was the next.. based on https://github.com/inProgress-team/react-native-youtube/pull/146

**YouTubeManager.java**
```java
....
public int getDuration(YouTubeView view) {
    return view.getDuration();
}
....
```

**YouTubeView.java**
```java
....
public int getDuration() {
    return mYoutubeController.getDuration();
}
....
```

**YouTubePlayerController.java**
```java
....
public int getDuration() {
    return mYouTubePlayer.getDurationMillis() / 1000;
}
....
```

**YouTubeModule.java**
```java
....
@ReactMethod
public void duration(final int reactTag, final Promise promise) {
    try {
        UIManagerModule uiManager = mReactContext.getNativeModule(UIManagerModule.class);
        uiManager.addUIBlock(new UIBlock() {
            public void execute (NativeViewHierarchyManager nvhm) {
                YouTubeView youTubeView = (YouTubeView) nvhm.resolveView(reactTag);
                YouTubeManager youTubeManager = (YouTubeManager) nvhm.resolveViewManager(reactTag);
                 int duration = youTubeManager.getDuration(youTubeView);
                 promise.resolve(duration);
            }
        });
    } catch (IllegalViewOperationException e) {
            promise.reject(E_MODULE_ERROR, e);
    }
}
....
```

**YouTube.android.js**
```javascript
....
duration() {
  return new Promise((resolve, reject) =>
    NativeModules.YouTubeModule
      .duration(ReactNative.findNodeHandle(this._nativeComponentRef))
      .then(duration => resolve(duration))
      .catch(errorMessage => reject(errorMessage)),
  );
}
....
```

**Comment by davidohayon669** [comment]
I'll handle it soon when I find some time

**Comment by hasaezs** [comment]
@davidohayon669 any news about this? I think it is necessary also on Android.

**Comment by davidohayon669** [comment]
@hasaezs 8d579baf1f1b55293c38cc937a39b173d221352a next version

**Comment by sriteja777** [comment]
Is it possible to get video duration in youtube standalone player on Android?
