### ISSUE TITLE
How to reset when the video is out of screen

### ISSUE THREAD

**Issue by willlaserlike** [inProgress-team/react-native-youtube#202]
I'm using the library together with listview. When a row with youtube video moves out of the screen, the video stops playing. But when I scroll back,  the control state and progress bar are not updated. They still show the playing state and time. I need to tap again to resume the playing.

I want the video component to reset itself when moved out of screen. Not remembering its state or taking any memory. 

Any suggestions on how to do this?  Thanks!

**Comment by davidohayon669** [comment]
The iOS and Android versions acts different to being clipped inside a ScrollView (ListView).
Anyway this has to do more with react than this repo. If you want the component to reset when clipped I guess you should find a way to unmount it and mount again when shown.

Try to see what `removeClippedSubviews` prop do in the [ListView](https://facebook.github.io/react-native/docs/listview.html)
