### ISSUE TITLE
Render multiple YouTube videos

### ISSUE THREAD

**Issue by aravindhkumar23** [inProgress-team/react-native-youtube#203]
Hi
   Is it possible to render multiple videos in FlatList in android ? 
   i have checked the closed [issue](https://github.com/inProgress-team/react-native-youtube/issues/62), any workaround or fix the issue.

my scenario is render dynamic video in listview row.

i am using 
- react native -0.44.2
- react-native-youtube -1.0.0-beta.1

**Comment by davidohayon669** [comment]
What do you get when you try it?
The Android version cannot load a video in two component at the same time for the reasons in the issue
