### ISSUE TITLE
didn't work?

### ISSUE THREAD

**Issue by nvdnvd00** [inProgress-team/react-native-youtube#206]
run app
-> react-native-youtube:compile release java with javac -> FAILED

**Comment by davidohayon669** [comment]
@nvdnvd00 I don't understand anything

**Comment by nvdnvd00** [comment]
i don't know why T_T
https://www.flickr.com/photos/153584198@N03/?

**Comment by nvdnvd00** [comment]
my jdk version is 1.8 
you know how to fix it?

**Comment by davidohayon669** [comment]
@nvdnvd00 Just upgraded the npm package to the latest with a support for this problem

`npm install react-native-youtube@latest -S`

**Comment by nvdnvd00** [comment]
thank you!
