### ISSUE TITLE
YouTubeStandaloneAndroid is messing up layout

### ISSUE THREAD

**Issue by MrPeproni** [inProgress-team/react-native-youtube#207]
Hello,

I am using React-Native-Youtube in my app. I am getting issue related to layout because of this package.

When the video play in full screen by `YouTubeStandaloneAndroid` code. And when we come back to app. Layout is already messed up... may be because `YouTubeStandaloneAndroid` is using full screen and changing screen orientation.

Please help me to solve it. This is very annoying.
Thanks in Advance.

**Comment by davidohayon669** [comment]
@aditya1027 Please be more descriptive and add screenshots if possible
