### ISSUE TITLE
YouTube three dots menu does not work on Android

### ISSUE THREAD

**Issue by vasiliy-sarzhynskyi** [inProgress-team/react-native-youtube#208]
Hello,

I display YouTube component in my app. If YouTube component not in fullScreen mode, android's three dots menu does not work for me (actually does not open Quality and Subtitles on/off menu). In fullScreen mode everything is fine.
I use RN version 0.45.1 and react-native-youtube 1.0.0-beta.3.

Thanks in advance

![screenshot 2](https://user-images.githubusercontent.com/22271138/29353287-624e533c-8272-11e7-93bf-d7020680cc34.jpg)

**Comment by davidohayon669** [comment]
When this happens, other controls still respond?

**Comment by davidohayon669** [comment]
@vasiliy-sarzhynskyi Just checked... To be honest I'm not sure if it ever responded. Seems to me like an issue with the native component

**Comment by vasiliy-sarzhynskyi** [comment]
@davidohayon669, other controls work fine. 
Android's three dots menu always does not work for non fullScreen mode.

**Comment by davidohayon669** [comment]
@vasiliy-sarzhynskyi I have no idea why

**Comment by tikkichan4** [comment]
It is also happened for my case with React-native v0.54.3. I think it is a quite serious problem and should not be closed without situation...
