### ISSUE TITLE
undefined is not an object "YouTubeStandaloneIOS"

### ISSUE THREAD

**Issue by MrPeproni** [inProgress-team/react-native-youtube#210]
Hello,

I am using YouTubeStandaloneIOS. Followed these steps `https://github.com/inProgress-team/react-native-youtube#standalone-player-ios` but no success.

I am using this:

```
import Youtube,
{ YouTubeStandaloneAndroid, YouTubeStandaloneIOS }
from 'react-native-youtube';

YouTubeStandaloneIOS.playVideo('KVZ-P-ZI6W4')
.then(() => console.log('Standalone Player Exited'))
.catch(errorMessage => console.error(errorMessage))
```

My Podfile is:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppName' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'XCDYouTubeKit', '~> 2.5'
  # Pods for AppName

  target 'AppNameTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AppName-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppName-tvOS

  target 'AppName-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```
Tried to use below url code but didn't get the YoutubeStandaloneIOS button.

https://github.com/inProgress-team/react-native-youtube/blob/master/example/RCTYouTubeExample.js

![screen shot 2017-08-23 at 11 41 46 am](https://user-images.githubusercontent.com/25629063/29601258-34cca36a-87f8-11e7-959f-0658d37cde76.png)

![simulator screen shot 22-aug-2017 4 28 21 pm](https://user-images.githubusercontent.com/25629063/29562591-80c24e92-8757-11e7-81ac-54b98943692d.png)

**Comment by aditya1027** [comment]
Now tried to use this code but didn't get the YoutubeStandaloneIOS button.

https://github.com/inProgress-team/react-native-youtube/blob/master/example/RCTYouTubeExample.js

![screen shot 2017-08-23 at 11 41 46 am](https://user-images.githubusercontent.com/25629063/29601258-34cca36a-87f8-11e7-959f-0658d37cde76.png)

**Comment by aditya1027** [comment]
@davidohayon669 Please look into this issue

**Comment by davidohayon669** [comment]
@aditya1027 Are you installing the pods?

**Comment by aditya1027** [comment]
@davidohayon669 somehow i have managed to make it working by deleting node_module folder and re-run npm install.

When i am using YoutubeStandaloneIOS... there is no loading icon when video is starting and it is just getting pause instead of showing loading icon when buffering.

**Comment by davidohayon669** [comment]
@MrPeproni The way this standalone module works depend on [XCDYouTubeKit](https://github.com/0xced/XCDYouTubeKit)
