### ISSUE TITLE
api key safe?

### ISSUE THREAD

**Issue by vvavepacket** [inProgress-team/react-native-youtube#211]
Is our developer API key safe when we put it in this plugin and distribute to our clients? Can it be sniffed in the network requests or are there any risks involved?

**Comment by davidohayon669** [comment]
@vvavepacket In my experience this key isn't checked by Google right now. The Android component will work with any non-empty string as a key. I cannot tell you if it still works for large scale, but then again, large scale of what? How can they tell one app from the other which uses this component without a registered key?

As far as how this key is dealt with, and sent over the network, I guess you should consult with the creators of the plugin themselves (Google)
