### ISSUE TITLE
[iOS] The bigger size the bigger borders are added

### ISSUE THREAD

**Issue by mdrbohlav** [inProgress-team/react-native-youtube#213]
The bigger size set to the video the bigger borders appear, grey at the top, black at the sides. There should be no borders at all.

![simulator screen shot - iphone 7 plus - 2017-09-01 at 15 24 30](https://user-images.githubusercontent.com/7562302/29971740-ad311628-8f29-11e7-8708-0f1f9d7b9df0.png)

ReactNative: 0.47.1
React-Native-YouTube: 1.0.0-beta.3
iOS: 11 dev beta 9

**Comment by davidohayon669** [comment]
@mdrbohlav what size of screen is it?

**Comment by mdrbohlav** [comment]
It’s iPhone 7 Plus

**Comment by davidohayon669** [comment]
@mdrbohlav can you capture the whole screen?

**Comment by mdrbohlav** [comment]
This is the whole screen in landscape. I can capture a video how the borders change when resizing the video.

**Comment by davidohayon669** [comment]
@mdrbohlav that might also help

**Comment by mdrbohlav** [comment]
![2017-09-01 19 46 31](https://user-images.githubusercontent.com/7562302/29981574-67c25014-8f4e-11e7-89b0-59e1b36ba93b.gif)

**Comment by davidohayon669** [comment]
@mdrbohlav Is it like that with every video? It seems like you somehow reached a maximum physical size of the video resolution. I would try some higher-def videos. There is also a method to change that quality of video in the native component but we haven't implemented that yet

**Comment by mdrbohlav** [comment]
Yes, the resolution of the video is 'only' full hd but it should fit the whole screen anyway. When I rotate the screen to the portrait and back it looks good sometimes.

**Comment by davidohayon669** [comment]
@mdrbohlav can you somehow reproduce this behavior on the example app or a modification of it in a fork?

**Comment by mdrbohlav** [comment]
I can try but I found the core of the problem.
I have top navigation bar visible in my app but when the video starts it hides. The video is rendered under the navigation bar (it is transparent) but for some reason when the bar is visible while the video gets ready the grey border is rendered under the navigation bar. When the video is rendered while the navigation bar is already hidden everything looks good.
It would suggest the video is not rendered in the places where another layer covers it but I have other controls at the bottom without any problems.

**Comment by davidohayon669** [comment]
@mdrbohlav So did you solve the problem?

**Comment by mdrbohlav** [comment]
Well, not yet. I just found why the border appears. It is like the content of the scrollview inside the webview could not be initially rendered under the navigation bar.

**Comment by davidohayon669** [comment]
@mdrbohlav It seems like a very specific issue with the kind of components you use. I'll close this issue for now, If you discover anything helpful please share

**Comment by mdrbohlav** [comment]
For everyone who encounters this - it is caused because of the iOS 11 changes, `automaticallyAdjustsScrollViewInsets` was deprecated, you have to use `contentInsetAdjustmentBehavior` - [like I did](https://github.com/mdrbohlav/react-native-youtube/commit/aa62d02b4b00e326b84f3f4f9b12dd0fc9ef8f8e)

**Comment by davidohayon669** [comment]
@mdrbohlav can you make a pull request?
