### ISSUE TITLE
video gets paused after starting

### ISSUE THREAD

**Issue by sidd123456** [inProgress-team/react-native-youtube#215]

**Comment by davidohayon669** [comment]
@sidd123456 need more details

**Comment by tikkichan4** [comment]
I got the same problem.
After clicking the play button / change the play state, the player will start playing 1-2 seconds and just freezed.

**Comment by davidohayon669** [comment]
@tikkichan4  do you get anything from `onError`?

**Comment by martinchristov** [comment]
+1.
onError output: {target: 304, error: "UNAUTHORIZED_OVERLAY"}

**Comment by davidohayon669** [comment]
@martinchristov On Android, the player view shouldn't be covered with any other view
https://github.com/inProgress-team/react-native-youtube#unauthorized_overlay-and-player_view_too_small-on-android
#161

**Comment by martinchristov** [comment]
@salmankhann you can simply do this:

	{(Platform.OS !== 'ios') &&
		<WebView
			style={{ alignSelf: 'stretch' }}
			source={{uri: `https://www.youtube.com/embed/${this.state.youtubeID}?controls=1&showinfo=0`}}
		/>
	}

I had no more time to put into it, so this is what I did.

**Comment by salmankhann** [comment]
But you're suggesting to do this without using this component right ?

Sent from my iPhone

On Sep 15, 2017, at 5:12 PM, Martin Christov <notifications@github.com<mailto:notifications@github.com>> wrote:


@salmankhann<https://github.com/salmankhann> you can simply do this:

{(Platform.OS !== 'ios') &&
        <WebView
                style={{ alignSelf: 'stretch' }}
                source={{uri: `https://www.youtube.com/embed/${this.state.youtubeID}?controls=1&showinfo=0`}}
        />
}


I had no more time to put into it, so this is what I did.

**Comment by salmankhann** [comment]
To be clear though, this library used to work with me but something broke it and now it just pauses automatically only the first time you play. Works perfectly every time after that. Also to add, I'm playing in full screen only and not inline

Sent from my iPhone

On Sep 15, 2017, at 5:12 PM, Martin Christov <notifications@github.com<mailto:notifications@github.com>> wrote:


@salmankhann<https://github.com/salmankhann> you can simply do this:

{(Platform.OS !== 'ios') &&
        <WebView
                style={{ alignSelf: 'stretch' }}
                source={{uri: `https://www.youtube.com/embed/${this.state.youtubeID}?controls=1&showinfo=0`}}
        />
}


I had no more time to put into it, so this is what I did.

**Comment by martinchristov** [comment]
In that case you'll have to figure it out, because the webview doesn't have fullscreen :) 
let me know if you do...

**Comment by davidohayon669** [comment]
@salmankhann can you provide more details? like exact props you pass to the component, stuff coming from onChangeState / onError or can you recreate this problem with the example app?

**Comment by ursNj** [comment]
same issue :( any one has solution for this ??? 
<YouTube
          videoId="umAgdVTBae0" // The YouTube video ID
          apiKey={APP_CONFIG.youtubeKey}
          play={true} // control playback of video with true/false
          showFullscreenButton
          fullscreen={this.state.fullscreen} // control whether the video should play in fullscreen or inline
          onChangeFullscreen={e => {
            this.setState({fullscreen: e.isFullscreen});
          }}
          // loop // control whether the video should loop when ended
          // onReady={e => this.setState({isReady: true})}
          // onChangeState={e => this.setState({ status: e.state })}
          // onChangeQuality={e => this.setState({ quality: e.quality })}
          onError={e => console.log('ERROR', e)}
          controls={2}
          style={{flex: 1, alignSelf: 'stretch'}}
        />

**Comment by tavareshenrique** [comment]
I have the same problem, apparently the video only plays if it is fullscreen.

`<YouTube
        videoId="xxxxx"
        apiKey="xxxxx"
        play
        fullscreen
        style={{ alignSelf: 'stretch', height: 300 }}
      />`

**Comment by shubhamram** [comment]
I have the same problem, Video getting stop after some time and getting this below error
{"error": "PLAYER_VIEW_TOO_SMALL", "target": 15143}

**Comment by vanlongfc** [comment]
check: 
https://stackoverflow.com/questions/64730529/react-native-youtube-video-stop-after-2-seconds-on-fullscreen-works-fine-una
