### ISSUE TITLE
android stuck in landscape mode after exiting with back button

### ISSUE THREAD

**Issue by MrLoh** [inProgress-team/react-native-youtube#217]
As reported before an android app is stuck in landscape mode after exiting a fullscreen player with the back button, this is a pretty big issue obviously, so I'm opening a new one here since the old ones were closed. It seems there was a PR #133 forthcoming that never got ready. I'll look into it and possibly provide a new PR.

**Comment by davidohayon669** [comment]
@MrLoh As far as I remember I fixed it somewhere down the road. I just tested on the example app and It looked fine for me. Can you be more specific about the behavior you describe?

**Comment by MrLoh** [comment]
yes, it seems to be fixed now. I'm very confused as to why it was broken before, but I just reloaded the app for the 101th time and it was working. Sometimes React Native is a mysterie to me. Thanks for the awesome YouTube Component.
