### ISSUE TITLE
Setting songs playing position periodically on a slider

### ISSUE THREAD

**Issue by serialbandicoot** [inProgress-team/react-native-youtube#219]
I've added a slider in order to move through a track, however I wanted to know if there is a callback method, which is periodically called so that I can set the slider to the current track position.

I can see the onProgress state already gets the values I need, its just how I can periodically update the slider.

Do I need to create my own timer function and set the slider value?

e.g: progress = (this.currentTime / this.state.duration) * 100

**Comment by davidohayon669** [comment]
@serialbandicoot on iOS this parameter is delivered with `onProgress` (I think every 500ms), with Android you'll have to call `currentTime()` periodically

**Comment by serialbandicoot** [comment]
Thanks @davidohayon669 - that's perfect!...I used the following on the YouTube element.

`onProgress={ e => this.getProgress(e)  }`

```
getProgress(e){
        this.setState({
            sliderValue: (e.currentTime / e.duration) * 100,
            duration: e.duration,
            currentTime: e.currentTime,
            songTime: this.getTimeDisplay(e.currentTime)
        })
    }
```

```
 getTimeDisplay = (d) => {
        d = Number(d);

        let m = Math.floor(d % 3600 / 60);
        let s = Math.floor(d % 3600 % 60);

        return ('0' + m).slice(-2) + ":" + ('0' + s).slice(-2);
    };
```
