### ISSUE TITLE
[Android] Issues with 2 Videos on same screen

### ISSUE THREAD

**Issue by joncursi** [inProgress-team/react-native-youtube#220]
If you put two youtube videos on the same screen on Android:

```js
<Youtube
  ...
  videoId="abc"
  ...
/>
<Youtube
  ...
  videoId="def"
  ...
/>
```

The first video instance (should render video for `abc`) will actually render the video for the second instance (`def`). So you get two `def` videos on the same screen.

When you try to play one of them, it tries to play both because they are the same videoID, I assume.

So:

1. Incorrect videoId for the first video instance
2. Neither are playable

**Comment by davidohayon669** [comment]
@jon Always read the [manual](https://github.com/inProgress-team/react-native-youtube#multiple-youtube--instances-on-android)

**Comment by joncursi** [comment]
Thanks, I'll close this down since it's captured in the README.
