### ISSUE TITLE
When application is minimized while playing video the video gets stopped. How resume the video when app is again in foreground

### ISSUE THREAD

**Issue by technextest** [inProgress-team/react-native-youtube#222]
I have set controls to zero and I have tested example app of this repository. On android when application is minimized while playing video the video gets stopped. And I need to resume the video when app is again in foreground. Please let me know if it is possible.

**Comment by davidohayon669** [comment]
@technextest next version #c206c5f611732f3a189a85629bd1e3c624e3b3c2
