### ISSUE TITLE
controls props doesn't change controls (iOS)

### ISSUE THREAD

**Issue by stantoncbradley** [inProgress-team/react-native-youtube#224]
Settings `controls` to 0 doesn't have any noticeable effect on iOS.  Does anyone else have this issue?

"react": "16.0.0-alpha.12",
"react-native": "0.47.1",
"react-native-youtube": "^1.0.0-beta.3",

**Comment by davidohayon669** [comment]
@stantoncbradley Can you provide a screenshot?

**Comment by davidohayon669** [comment]
@stantoncbradley setting 0/1 on this prop should conform to the functionality [described here](https://developers.google.com/youtube/player_parameters) (under "controls" parameter)
