### ISSUE TITLE
android crashes trying to update fullscreen on released player

### ISSUE THREAD

**Issue by MrLoh** [inProgress-team/react-native-youtube#226]
I keep getting errors like this on android: 

![screenshot_20171014-172925](https://user-images.githubusercontent.com/1285032/31577105-6268aa74-b0d6-11e7-953f-b9f04f86f9a9.png)

It might be my specific setup, but it's really hard to fix those errors. It would be best if the library would have some checks to prevent trying to update released players, so one doesn't have to worry about thos implementation details in javascript.

**Comment by franzmoro** [comment]
Any updates on this?

**Comment by davidohayon669** [comment]
@franzmoro I'll deal with it next few days

**Comment by davidohayon669** [comment]
@franzmoro can you help me recreate this bug? or maybe provide more log information.
From the information I have I cannot decide which call to the player should be wrapped in an `if` of `try` and I wouldn't want to wrap all of them

**Comment by MrLoh** [comment]
Probably all the calls on the `view` here must assume that it can be null. 
https://github.com/inProgress-team/react-native-youtube/blob/master/android/src/main/java/com/inprogress/reactnativeyoutube/YouTubeManager.java

**Comment by davidohayon669** [comment]
@MrLoh I'm sorry but I can't seem to recreate this problem. You can either fork this repo and try to recreate it on the example project, and then share here, or try to locate the exact place in the code where there is a call on a null object. Most props goes through YouTubeManager -> YouTubeView -> YouTubeController -> YouTubePlayer and I wouldn't want to add so much unnecessary checks.

**Comment by Pedneri1** [comment]
+1

**Comment by franzmoro** [comment]
@davidohayon669 I embedded the Youtube player like so (nested inside a FlatList + other views):
```js
<FlatList
  {...otherProps}
  renderItem={({ item: props }) => (
    <View style={styles.container}>
      {props.isYoutubeVideo && (
        <YoutubePlayer
          apiKey={androidGoogleAPIKey}
          style={styles.player}
          videoId={props.video.youtubeId}
          showFullscreenButton={true}
        />
      )}
    </View>
  )}
/>
```
**Steps**:
- run app on Android Emulator
- scroll through list of other items & reach video
- play video (works while still in portrait)
- press the fullscreen button, outcome:
    - orientation rotates to Landscape
    - list is still showing (video is not fullscreen) & list has scrolled to the top
    - cannot rotate back to portrait
    - no error thrown

**Comment by MrLoh** [comment]
@franzmoro has that anything to do with this issues? Are you getting the error?

**Comment by franzmoro** [comment]
@MrLoh when I had originally commented I got the same error, but now its not being thrown anymore.

**Comment by MrLoh** [comment]
@franzmoro the issue you are reporting sounds completely unrelated, as it doesn't even crash the app. You should create a separate issue, instead of diluting the problem this issue is about. If you don't get the error it has nothing to do with this issue. I don't see any indication that the problem you report has something to do with an unreleased player. Problems with locked screen oritentation are known and have been reported in this repo before. please search the issues.

**Comment by davidohayon669** [comment]
@MrLoh @franzmoro please try to recreate each problem on a public repo so I can test it myself

**Comment by MrLoh** [comment]
I will once I get around to it, I have a workaround for now and we are super busy releasing our app at the moment, but I will prepare a repo once things get a little more sane for me

**Comment by davidohayon669** [comment]
@MrLoh Please provide updates when you have any

**Comment by judemanutd** [comment]
Issue still occurs, in order to recreate the issue i created a `flatlist` and set the `list header component` as the `youtube component` , then on clearing the data set that populates the `flatlist` this error is thrown.

**Comment by Regicollis** [comment]
I have the same issue
