### ISSUE TITLE
Handle "SERVICE_MISSING" by self

### ISSUE THREAD

**Issue by wayne1203** [inProgress-team/react-native-youtube#227]
I placed "YouTube" View in ListView, I found that error alert will show when renderRow but it's annoying . Can I override the alert and handle it by my self?

**Comment by davidohayon669** [comment]
@wayne1203 I'm not sure I understand. "SERVICE_MISSING" supposed to be an internal error of the native nodule when there is no YouTube app installed on the device. What does it got to do with ListView?

**Comment by wayne1203** [comment]
Sorry for my bad English.
In other word, can I remove the alert of "this app won't run without the youtube app which is missing from your device"?

**Comment by davidohayon669** [comment]
@wayne1203 I don't think this component is that complicated to allow for selective error logging

**Comment by cyb3rsalih** [comment]
I have also same problem, I want to redirect the user to web browser youtube.com when there is no youtube app.
Try catch not working, players catch method not working also.
