### ISSUE TITLE
EXC_BAD_ACCESS-[RCTYouTubeStandalone moviePlayerPlaybackDidFinish:]

### ISSUE THREAD

**Issue by enahum** [inProgress-team/react-native-youtube#229]
I've hooked my app to Sentry and I'm getting the following reports when the is crashing

EXC_BAD_ACCESS-[RCTYouTubeStandalone moviePlayerPlaybackDidFinish:]
fatalAttempted to dereference garbage pointer 0x10. Originated at or in a subcall of __cxa_throw

![image](https://user-images.githubusercontent.com/6757047/31718642-0e355baa-b3e7-11e7-9fc8-078350e47667.png)

**Comment by davidohayon669** [comment]
@enahum we use [XCDYouTubeKit](https://github.com/0xced/XCDYouTubeKit) for the standalone player on iOS. I guess they would have much more experience with this problem.
