### ISSUE TITLE
Multiple video on one component

### ISSUE THREAD

**Issue by supritshah1289** [inProgress-team/react-native-youtube#230]
I'm trying to render multiple videos on the same component. However, It only shows single video multiple times. Even though videoId is different. 

```
render() {
    return (
      <ScrollView>

          {this.state.showId.map((videoId,i)=>
            <View key={i}>
              <Text>
                {videoId}
              </Text>
              <Youtube
                key={i}
                videoId={videoId}
                play={false}
                fullscreen={true}
                loop={false}
                apiKey="__API_KEY__"
                style={{alignSelf: 'stretch', height: 300, backgroundColor: 'black', marginVertical: 10}}
                >
              </Youtube>
            </View>
          )}
      </ScrollView>
    );
  }

```

**Comment by davidohayon669** [comment]
@supritshah1289 Android?

**Comment by supritshah1289** [comment]
@davidohayon669  Yes, I'm using React-native-youtube for building an Android app. I'm testing it in an Android device.

**Comment by davidohayon669** [comment]
@supritshah1289 [it's all right there](https://github.com/inProgress-team/react-native-youtube#multiple-youtube--instances-on-android)

**Comment by Rratio** [comment]
@davidohayon669  is there possible to show multiple video on same screen

**Comment by Rratio** [comment]
> I'm trying to render multiple videos on the same component. However, It only shows single video multiple times. Even though videoId is different.
> 
> ```
> render() {
>     return (
>       <ScrollView>
> 
>           {this.state.showId.map((videoId,i)=>
>             <View key={i}>
>               <Text>
>                 {videoId}
>               </Text>
>               <Youtube
>                 key={i}
>                 videoId={videoId}
>                 play={false}
>                 fullscreen={true}
>                 loop={false}
>                 apiKey="__API_KEY__"
>                 style={{alignSelf: 'stretch', height: 300, backgroundColor: 'black', marginVertical: 10}}
>                 >
>               </Youtube>
>             </View>
>           )}
>       </ScrollView>
>     );
>   }
> ```

Have you find any solution for this @supritshah1289
