### ISSUE TITLE
Android fullscreen not working when nested in Flatlist

### ISSUE THREAD

**Issue by franzmoro** [inProgress-team/react-native-youtube#231]
@davidohayon669 I embedded the Youtube player like so (nested inside a FlatList + other views):
```js
<FlatList
  {...otherProps}
  renderItem={({ item: props }) => (
    <View style={styles.container}>
      {props.isYoutubeVideo && (
        <YoutubePlayer
          apiKey={androidGoogleAPIKey}
          style={styles.player}
          videoId={props.video.youtubeId}
          showFullscreenButton={true}
        />
      )}
    </View>
  )}
/>
```
**Steps**:
- run app on Android Emulator
- scroll through list of other items & reach video
- play video (works while still in portrait)
- press the fullscreen button, outcome:
    - orientation rotates to Landscape
    - list is still showing (video is not fullscreen) & list has scrolled to the top
    - cannot rotate back to portrait
    - no error thrown

Btw, it works on iOS.

originally posted in #226

**Comment by davidohayon669** [comment]
@franzmoro any chance you can fork the example in this repo and recreate the problem there? or anywhere else?

**Comment by lucianomlima** [comment]
Is related to this https://github.com/inProgress-team/react-native-youtube#multiple-youtube--instances-on-android?

**Comment by davidohayon669** [comment]
Android cannot and probably will not enable mounting YouTube instances in parallel
