### ISSUE TITLE
Could not to play live video on Android only

### ISSUE THREAD

**Issue by jokopurnomoa** [inProgress-team/react-native-youtube#233]
When playing live video with id "AtXZJM8rQfg" for example, it runs fine on iOS, but it does not work on Android. If it plays normal videos then it runs fine on both platforms.

```
<YouTube
    apiKey="API_KEY"
    videoId="AtXZJM8rQfg"   // The YouTube video ID
    play={true}             // control playback of video with true/false

    onReady={e => this.setState({ isReady: true })}
    onChangeState={e => this.setState({ status: e.state })}
    onChangeQuality={e => this.setState({ quality: e.quality })}
    onError={e => this.setState({ error: e.error })}

    style={styles.youtubePlayer}
    />
```

### Environment

1. Application Target Platform: Android

2. Development Operating System: Mac OS X El Capitan

3. Build Tools: 25.0.3

4. React Native version: 0.49.3

5. React Native Youtube Version: v1.0.0-beta.3

**Comment by Moussawi7** [comment]
it is working from my side, but it stop every second so i have have to press the play icon every time.

**Comment by davidohayon669** [comment]
@Moussawi7 I'll have to test this.. never tried live video

**Comment by jokopurnomoa** [comment]
After rebuild with build tools 26.0.2 this works on android 6.0 (Nougat) and above. On android version below 5.1 (Lollipop) runs a black blank with sound only.

**Comment by davidohayon669** [comment]
@jokopurnomoa probably an issue with the native module

**Comment by Kaywee27** [comment]
> it is working from my side, but it stop every second so i have have to press the play icon every time.

Hiii, I am facing the same problem and found this issue closed. Did you get that fixed?

**Comment by neilakoh** [comment]
For live videos I just use a different library
https://lonelycpp.github.io/react-native-youtube-iframe/
