### ISSUE TITLE
Not working with Exponent/CRNA

### ISSUE THREAD

**Issue by bllohar** [inProgress-team/react-native-youtube#234]
Warning: Native component for "ReactYouTube" does not exist

**Comment by davidohayon669** [comment]
Did you link this library's native code?
On a regular project it goes with `react-native link && rnpm link`. Not sure about exponent or CRNA

**Comment by SamMatthewsIsACommonName** [comment]
I tried today and have done both react-native link && rnpm link, on React Native 0.50.3

**Comment by SamMatthewsIsACommonName** [comment]
I tried looking through the android file of the example app to see what should be in build.gradle, app/build.gradle, MainActivity.java, settings.gradle etc and couldn't see anything different. Is it possible to find what changes are made on android to the native files after the link, and I could try and see if some aspect didn't work?

**Comment by davidohayon669** [comment]
@SamMatthewsIsACommonName The example app in the repo is **NOT** linked out of the box.

As per the [instructions](https://github.com/inProgress-team/react-native-youtube#example-app-and-development), you need to install it and then link. After that you'll be able to watch the diff with git

**Comment by SamMatthewsIsACommonName** [comment]
You're right sorry. In my case the link process had missed MainActivity.java. Thanks!

**Comment by davidohayon669** [comment]
@SamMatthewsIsACommonName good to know I helped

**Comment by DamnedScholar** [comment]
I believe I have the same problem but don't know enough to follow the solution presented here. I've used `react-native link` and `rnpm link` on an ejected (ExpoKit) app and nothing. Is there something preventing the automated linking process from completing even though it says it does? What manual steps are necessary to correct that? Thanks.

**Comment by DamnedScholar** [comment]
[According to the documentation](https://facebook.github.io/react-native/docs/native-modules-android.html#register-the-module), there should be a `createReactPackages` somewhere under `android/app`. There is not, and the documentation doesn't say what file it should go in. Shouldn't that be the first thing handled by the `link` commands, though?
