### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by decodez** [inProgress-team/react-native-youtube#235]
Hi, I am getting this error,

/Users/akhil.prasenan/Documents/sites/mci_app/node_modules/react-native-youtube/android/src/main/java/com/inprogress/reactnativeyoutube/VideoFragment.java:10: Error: Avoid non-default constructors in fragments: use a default constructor plus Fragment#setArguments(Bundle) instead [ValidFragment]
    public VideoFragment(YouTubeView youTubeView) {
           ~~~~~~~~~~~~~

   Explanation for issues of type "ValidFragment":
   From the Fragment documentation:
   Every fragment must have an empty constructor, so it can be instantiated
   when restoring its activity's state. It is strongly recommended that
   subclasses do not have other constructors with parameters, since these
   constructors will not be called when the fragment is re-instantiated;
   instead, arguments can be supplied by the caller with setArguments(Bundle)
   and later retrieved by the Fragment with getArguments().

   http://developer.android.com/reference/android/app/Fragment.html#Fragment()

2 errors, 0 warnings
:app:lintVitalRelease FAILED

**Comment by davidohayon669** [comment]
@decodez Please provide specific info about your build environment. This should not happen

**Comment by punksta** [comment]
Have this issue also. with api 25.
```
        compileSdkVersion 25
                buildToolsVersion "25.0.3"
```
you can add this to root build.gradle file
```
subprojects { subproject ->
    afterEvaluate{
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion 25
                buildToolsVersion "25.0.3"
            }
        }
    }
}
```

This code is wrong. 
https://github.com/inProgress-team/react-native-youtube/blob/master/android/src/main/java/com/inprogress/reactnativeyoutube/VideoFragment.java#L10

Fragments should have default constructors(without args) to support their life-cycle. Android will not able restore object of fragment in case it does not have default constructor.

**Comment by zarcode** [comment]
+1

**Comment by adamonkey** [comment]
+1

**Comment by CarlosUvaSilva** [comment]
@punksta hello, which lines should I replace with the ones you provided? I tried different things but I couldn't make it work

**Comment by die20** [comment]
+1

**Comment by punksta** [comment]
@CarlosUvaSilva I sent only my configuration to lib author. 
for temporal fix you can add lintOptions inside `android` block of `android/app/build.gradle` file:
```
android {
lintOptions {
        abortOnError false
        disable 'ValidFragment'
    }
}
```

**Comment by ruipaulo** [comment]
Hi, same error here. Build Tools '26.0.1'. Turning of linting is a good quickfix, but not a real solution.
