### ISSUE TITLE
Force display landscape fullscreen ios

### ISSUE THREAD

**Issue by lamtan92** [inProgress-team/react-native-youtube#236]
Hi team,
Could we force video play landscape in fullscreen mode, at ios?
Thank you

**Comment by davidohayon669** [comment]
@lamtan92 AFAIK the native YouTube module do not support it. You probably better try to control the aspect from outside, with the react-native APIs

**Comment by lukewlms** [comment]
@lamtan92 We use react-native-orientation for this - lock Landscape Right when video starts, lock Portrait again when video ends.
