### ISSUE TITLE
Youtube video not play in iOS device.

### ISSUE THREAD

**Issue by kagmanoj25** [inProgress-team/react-native-youtube#237]
Youtube video doesn't play on the iOS device. It's showing white box only. Is anybody facing this problem? I attached a screenshot for reference.
![simulator screen shot - iphone 6 - 2017-11-15 at 14 18 00](https://user-images.githubusercontent.com/31121876/32826881-22919368-ca10-11e7-9af6-cc158d4e254c.png)

**Comment by davidohayon669** [comment]
`onError` ?

**Comment by kagmanoj25** [comment]
@davidohayon669 Yes i already run link command.

**Comment by haani104** [comment]
How can this be closed without an explanation?
