### ISSUE TITLE
"INTERNAL_ERROR" for playing video and if try to play new video it gives same error for next video

### ISSUE THREAD

**Issue by technextest** [inProgress-team/react-native-youtube#239]
I want to play multiple youtube videos. But it gives me "INTERNAL_ERROR" for playing video and if try to play new video it gives same error for next video until the app is killed and restarted. I am facing this problem on android. I have latest version of everything.

**Comment by davidohayon669** [comment]
@technextest Android version cannot play more than one video
https://github.com/inProgress-team/react-native-youtube#multiple-youtube--instances-on-android

**Comment by technextest** [comment]
Thanks for feedback.
I am not playing multiple videos simultaneously. After completion of one video I am playing next video. But if "INTERNAL ERROR" occurs and then I start next video then that error is appearing continuously for all next videos.

**Comment by xstable** [comment]
Have the same Issue. Sometimes the Video load, sometimes it doesn't load and quit with `INTERNAL ERROR` message. 
And I even have only one Video loaded like the thread opener.

Happend on Android 9 with RN 0.60.5 and react-native-youtube 2.0.0-beta.2
