### ISSUE TITLE
error when loading youtube video on iOS

### ISSUE THREAD

**Issue by stanams** [inProgress-team/react-native-youtube#240]
I've been doing all the requirements (installing, linking the lib both ways, calling the component) and still have an error on the screen that holds the <Youtube /> component. I provided an apiKey.
The error says:
`invariant violation:  Native component for "RCTYoutube" does not exist.`

I'm not using create-react-native starter, and build my app through `react-native run-ios`

Could you please help me solving this basic issue ?
Thanks

**Comment by vivekkadu** [comment]
Same problem while Working with Windows & Android.

**Comment by waterple** [comment]
Same problom

**Comment by samernady** [comment]
any update on that ?

**Comment by udugam** [comment]
Also getting the same issue but did not provide an APIKey.

**Comment by rajatbeck** [comment]
facing the same issue on my side...any updates in this issue??

**Comment by udugam** [comment]
@rajatbeck, open your IOS project in Xcode and check to see if the "RCTYoutube.xcodeproj" library was actually added to the "Libraries" folder. Also check to see if "libRCTYouTube.a" was added to the "Link Binary With Libraries" list found in your Targets' Build Phases.

If not, you need to add the "RCTYoutube.xcodeproj" library to the Xcode Libraries folder. You can find "RCTYoutube.xcodeproj" in the react-native-youtube folder of your app's Node Modules folder. Once you've done that you'll be able to find the "libRCTYouTube.a" binary when you click the "+" option at the end of the "Link Binary With Libraries" list found in your Targets' Build Phases. All should be working after this is done.

The official docs for manually linking libraries explains it well with screenshots: https://facebook.github.io/react-native/docs/linking-libraries-ios.html

**Comment by KangYoosam** [comment]
thanks, @udugam
