### ISSUE TITLE
IOS <Youtube> component not work 

### ISSUE THREAD

**Issue by alex3144** [inProgress-team/react-native-youtube#250]
hello, 

All is in the title :) 

Thx

**Comment by kdemoya** [comment]
Same here, just getting a white space, nothing on `onError` either.

**Comment by alex3144** [comment]
So youtube project IOS is dead we need to fork ???

**Comment by davidohayon669** [comment]
@alex3144 Can you be more specific? 
iOS version, RN version

Also, if you have any solutions you can provide a pull request and i'll review it right away

**Comment by yareyaredesuyo** [comment]
It maybe react-native or react version problem.

Works fine in "react": "16.0.0-beta.5", "react-native": "~0.49.3".

Try to check example project's package.json and compare your project version.
