### ISSUE TITLE
No sound in silent mode on iOS

### ISSUE THREAD

**Issue by arnsa** [inProgress-team/react-native-youtube#256]
Hello,

If there's a silent mode turned on on iOS, when video is playing, there's no sound for some reason. When I watch videos on other apps on iOS with silent mode turned on, it works just fine. Is there an available fix for this?

Package version: ^1.0.1
RN: 0.49.3

**Comment by arnsa** [comment]
Ah, okay, sorry, found the fix in the documentation.

**Comment by bneigher** [comment]
For those who arrived here:
[Relevant docs section](https://github.com/inProgress-team/react-native-youtube#optional-activated-sound-when-iphone-ios-is-on-vibrate-mode)

And for SEO:

1. Open AppDelegate.m and add:
`#import <AVFoundation/AVFoundation.h>`

2. A bit lower in AppDelegate.m -- In the didFinishLaunchingWithOptions method add:
`[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error: nil];`
