### ISSUE TITLE
React Native Youtube Player iOS Autoplay false 

### ISSUE THREAD

**Issue by vishnumm93** [inProgress-team/react-native-youtube#257]
In my app the video is played automatically when the activity is opened. I have added the code autoplay = false. But its not working. Any Solutions??

**Comment by davidohayon669** [comment]
@vishnumm93  There is no `autoplay` prop. Did you try `play={false}`?

**Comment by phanoophong** [comment]
i just put play={false] but doesn't work

**Comment by davidohayon669** [comment]
@phanoophong @vishnumm93 Can you reproduce this behaviour in the example app in this repo?

If I set `play={false}` the video never auto-starts

![screen shot 2018-02-05 at 23 15 31](https://user-images.githubusercontent.com/7001025/35829193-bd4861f2-0aca-11e8-9202-f5d5e610c001.png)

**Comment by vishnumm93** [comment]
I tried play = {false} its working in Android but not in iOS

**Comment by davidohayon669** [comment]
@vishnumm93 can't think of anything.. If you try the example app in this repo, does it behave the same?

**Comment by GutteApps** [comment]
this still happens on 1.1.0. play={false} is ignored on iOS after initial load

**Comment by hindsricardo** [comment]
The same is happening with me for IOS.  Is there some work around?

**Comment by amed** [comment]
Should this issue stays without any response?

**Comment by amed** [comment]
Should this issue stay without any response?

**Comment by elango** [comment]
`handleReady = () => {
  this._youTubeRef.reloadIframe();
}`

**Comment by kofsiwon** [comment]
I resolved the problem like this
videoId={ this.state.isGuidePlaying ? this.state.guide.url : null}

But I had to cover thumbnail image on player before start playing

**Comment by AKnuazev** [comment]
> `handleReady = () => { this._youTubeRef.reloadIframe(); }`

This worked for me, thaks!

i used it like this:
```js
	useEffect(() => {
		youTubeRef.current?.reloadIframe?.();
	}, [youTubeID]);


	return (
			<YouTube
				videoId={youTubeID}
				play={false}
				ref={youTubeRef}
				rel={false}
				controls={1}
				showinfo={false}
				modestbranding
				style={playerStyles}
			/>
)
```
