### ISSUE TITLE
Invariant violation: Native component for "RCTYoutube" does not exist

### ISSUE THREAD

**Issue by rajatbeck** [inProgress-team/react-native-youtube#259]
Facing this issues when trying to use Youtube player in IOS ... I have correctly followed the installation steps and properly linked it ..
react and react-native version i am using is 
"react": "16.2.0",
"react-native": "0.52.2"

![simulator screen shot - iphone 6 - 2018-02-08 at 19 43 11](https://user-images.githubusercontent.com/19323153/35977350-e9fffe86-0d08-11e8-8eb7-13a51b5d18cb.png)

**Comment by johnckendall** [comment]
Add this: assets/YTPlayerView-iframe-player.html to your projects ios directory

**Comment by pacikav** [comment]
have similar issue on android emulator
"react": "16.0.0",
"react-native": "0.51.0",
what could be a problem?
![1](https://user-images.githubusercontent.com/478783/35980718-17dda192-0cf4-11e8-8008-eb92456a9e09.jpg)

**Comment by davidohayon669** [comment]
@pacikav @rajatbeck You have to somehow link this native library with your react project. On the example app in this repo it is demonstrated with `react-native link && rnpm link` (must have both as global dependencies or local if registered in your project as an npm script.
[
More about native package's linking (explains about iOS but Android should behave the same with regard to `react-native link`)](https://facebook.github.io/react-native/docs/linking-libraries-ios.html)

**Comment by redefinered** [comment]
Same issue here.

**Comment by vardaan** [comment]
Same here :(

**Comment by sadi304** [comment]
you have to link the native projects.

# react-native link 
# then see if its properly included in settings.gradle and build.gradle also see the mainapplicatio java

this should be properly mentioned in the docs. as sometime react-native link does not work successfully

**Comment by rajatbeck** [comment]
Solved  it.. it was not linked properly.. it worked when tried doing it manually.

**Comment by celalkasli** [comment]
@rajatbeck what did you do exactly as manually. i have tried to add YTPlayerView-iframe-player.html to the root directory and all others linking things, but i still get same error.
  "react": "16.3.1",
  "react-native": "0.55.3",
  "react-native-youtube": "^1.1.0",

**Comment by ziyafenn** [comment]
Still, have the problem on Android! Everything linked correctly. On iOS all works.

**Comment by AownRaza** [comment]
Still having this issue. Any solution found?

**Comment by nmartin867** [comment]
@AownRaza are you using Cocoapods? 

`pod install`

**Comment by AownRaza** [comment]
@nmartin867 Im doing it for Android

**Comment by absolute37** [comment]
> Solved it.. it was not linked properly.. it worked when tried doing it manually.

it's still error after manual link, How to resolve this error 😭

**Comment by rajatbeck** [comment]
@evanb2 .xcodeproj file is present 

> /node_modules/react-native-youtube/RCTYouTube.xcodeproj

add this file manually. Hope this solves your problem

**Comment by rajatbeck** [comment]
absolute37 i just tried to link it manually and everything worked out. 
Maybe you are doing something wrong.
I hope you are using `npm install react-native-youtube -S`
because somehow if you install package through `yarn add react-native-youtube` it leads to invariant voilation

**Comment by vkumarNobul** [comment]
Restart your server and re-run the app.

**Comment by SirCameron** [comment]
Manually linking libRCTYouTube.a in xcode crashes the build. Abandoning this.

**Comment by MITDD6338** [comment]
@SirCameron any solution in IOS

**Comment by redjanym** [comment]
After installing the library i had this issue, then i did `pod install`  but then i had this error in iOS:
`requireNativeComponent: "RCTYouTube" was not found in the UIManager`

I had to uninstall the app from the emulator and install it again in order for it to work.

**Comment by Biplovkumar** [comment]
> npm install react-native-youtube -S

I am using yarn, Not able to link this library and kit too.
Same error here.

**Comment by Biplovkumar** [comment]
App update, More than react native 60.0 is only solution.then it is working fine.
