### ISSUE TITLE
Force Node version > 8

### ISSUE THREAD

**Issue by mxmtsk** [inProgress-team/react-native-youtube#261]
Hey,

is there a specific reason why you force node version 8 in the `package.json`?

It was added in https://github.com/inProgress-team/react-native-youtube/commit/d3933a8687a503560cff1497deebd8d2e03436b5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 and I see no reason for it. Now you're not able to install this package when using a a node version below 8. `prettier` has, as well as `react-native` only the requirement for node `>=4`

Thanks for the clarification :)

**Comment by davidohayon669** [comment]
@mxmtsk will be taken off
