### ISSUE TITLE
Incompatible block pointer (self.bridge.uiManager addUIBlock)

### ISSUE THREAD

**Issue by dann1609** [inProgress-team/react-native-youtube#262]
self.bridge.uiManager addUIBlock:^(__unused RCTUIManager *uiManager, NSDictionary<NSNumber *, UIView *> *viewRegistry) show an alert that says incompatible block pointer

You can solve this adding : 
`pod 'React', path: '../node_modules/react-native'
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'`
to pod file.

**Comment by SalimValuecoders** [comment]
Please following this url

https://github.com/react-native-community/lottie-react-native/issues/113
