### ISSUE TITLE
Status unstarted for some videos IDs

### ISSUE THREAD

**Issue by Couiljer** [inProgress-team/react-native-youtube#263]
Hi there, 

I can't figure out why for some videos the status state responds "unstarted". According to youtube, this is a non-playing status (-1).
e.g: with this videoId 'FMBpdfM3Iso' it works like a charm however if I take this one '9GvKfvDt5T8' I get the unstarted status (and ofc unplayable video) 

Could anyone help me with that issue?

**Comment by johnckendall** [comment]
9GvKfvDt5T8 is a VEVO video.  They are not playable anywhere but on the youtube site because the author has designated them that way.

**Comment by Couiljer** [comment]
@johnckendall this video can easily be embedded on a website. I also tried to use another non-VEVO video like '0rBznra4-D4' and it results in status unstarted too.

**Comment by davidohayon669** [comment]
@Couiljer some publishers chose theirs videos to not be available outside of the official youtube website or embeds
