### ISSUE TITLE
Playlist items Idea

### ISSUE THREAD

**Issue by MrNagoo** [inProgress-team/react-native-youtube#267]
I am using the youTube api to get all Video Id's and content details for a specific playlist. I then take each video id and create a <Youtube> component with each one. This way, when a video gets added to the playlist, it will know and dynamically add a new <YouTube> component with the new videoId and send a notification. Would be nice to have a function to import from this library that could make that call.

**Comment by davidohayon669** [comment]
This is not in the scope for this library
