### ISSUE TITLE
How to embed a live stream?

### ISSUE THREAD

**Issue by christiansaiki** [inProgress-team/react-native-youtube#268]
Hi I've got the following video that I want to display
https://www.youtube.com/embed/live_stream?channel=UCHk3Xtz3k8H1Ms6CtodmawQ

I want to display in that way because it is a live stream and the videoId keeps changing.

Nevertheless if I put 
```jsx
render () {
    return (
      <YouTube
        apiKey={API_KEY}
        videoId='live_stream?channel=UCHk3Xtz3k8H1Ms6CtodmawQ'   // The YouTube video ID
        play             // control playback of video with true/false
        showFullscreenButton
        onReady={e => this.setState({ isReady: true })}
        onChangeState={e => this.setState({ status: e.state })}
        onChangeQuality={e => this.setState({ quality: e.quality })}
        onError={e => this.setState({ error: e.error })}
        style={{ height: 300 }}
      />
    )
  }
```

It renders
![image](https://user-images.githubusercontent.com/7768082/37002963-24c5a412-20aa-11e8-9a20-6da7610c46cd.png)

What should I do?
Best Regards

**Comment by silkyland** [comment]
You just need youtube ID from it URL

**Comment by srinusonly** [comment]
Any update on this?

**Comment by christiansaiki** [comment]
Hey @srinusonly 
I am using this componentDidMount trick to get the videoUrl

```javascript
componentDidMount () {
    fetch(`${YOUTUBE_API}`)
      .then((response) => response.json())
      .then((responseJson) => {
        if (responseJson && responseJson.items[0]) this.setState({ videoId: responseJson.items[0].id.videoId })
      })
      .catch((error) => {
        console.error(error)
      })
  }
```

where YOUTUBE_API is 
`const YOUTUBE_API = `https://www.googleapis.com/youtube/v3/search?part=snippet&channelId=${CHANNEL_ID}&eventType=live&type=video&key=${API_KEY}``

**Comment by srinusonly** [comment]
Good work around.

Thanks for the help

**Comment by jdadojr** [comment]
Only works on IOS, not on Android.. 
Android will just spin the circle forever

**Comment by mayconmesquita** [comment]
Would be nice this working on Android

**Comment by davidohayon669** [comment]
@mayconmesquita Whatever abilities this library provide, depends on the official utils YouTube provide for iOS and Android, in your case [YouTube Android Player API](https://developers.google.com/youtube/android/player/)

This lib is just a RN wrapper around those, if they provide some functionality that is not covered here, please suggest it

**Comment by HarshitMadhav** [comment]
I can confirm that workaround provided by @christiansaiki works in both android and iOS.

**Comment by mayconmesquita** [comment]
@HarshitMadhav thanks! I will test soon.

**Comment by firofame** [comment]
YOUTUBE_API has a 100x free limit. 

it would be awesome if we could please support "https://www.youtube.com/embed/live_stream?channel="
