### ISSUE TITLE
Player changes the app's default orientaion , while unmount

### ISSUE THREAD

**Issue by thayanithik** [inProgress-team/react-native-youtube#269]
I am facing a major problem while used with new version of "react-native-youtube" v1.1.0.

if i played video in fullscreen mode and return back to normal, then if i pressed down phone's back button or navigator back button, It will changes the app's default orientation .(like PORTRAIT to LANDSCAPE)

Which will affect other views of entire app.

Kindly check this issue on new version ...

**Comment by jerearaujo03** [comment]
+1

**Comment by guptayush** [comment]
please give some solution

**Comment by unishubh** [comment]
This issue still persist
