### ISSUE TITLE
Failed build using xCode

### ISSUE THREAD

**Issue by randymuhroji** [inProgress-team/react-native-youtube#286]
Argument list too long: recursive header expansion failed at /Users/macbookpro/Documents/Project/mobile/frontend-mobile-app/node_modules/react-native-youtube/../../ios/Pods/React/node_modules/recast/node_modules/source-map/lib.

**Comment by PierreBresson** [comment]
I also had a `Argument list too long: recursive header expansion failed` error and solved it by removing reference _RCTYouTube.xcodeproj_ then put it again from node_module. Then select _RCTYoutube.xcodeproj_ and go to **Build Settings** and **Framework Search Paths** and remove `$(SRCROOT)/../../ios`

**Comment by randymuhroji** [comment]
fixed.
thanks

**Comment by paour** [comment]
Toi avoid having to edit this file each time you reinstall your node modules, use [`patch-package`](https://github.com/ds300/patch-package).

**Comment by Biplovkumar** [comment]
@PierreBresson  thanks,it worked.

**Comment by prayuditb** [comment]
I just remove `$(SRCROOT)/../../ios` from **Framework Searh Path**
Thanks @PierreBresson

**Comment by mhp92** [comment]
@prayuditb hey can you explain a little bit more how to do it step by step? I'm a newby..
thanks in advance.

**Comment by marlon-wiprud** [comment]
My build is working just fine with xcode, but breaks when using Detox with this same error.  Removing `$(SRCROOT)/../../ios` did not work.
