### ISSUE TITLE
Use without Play services

### ISSUE THREAD

**Issue by Rudloff** [inProgress-team/react-native-youtube#288]
Hello,

This library can't be used on a device without Play services.

Also it can't be built without a proprietary jar, which means any app using this library can't be included in free software repositories like [F-Droid](https://f-droid.org/).

Wouldn't it be possible to switch to a free Youtube library like [this one](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player)?

**Comment by davidohayon669** [comment]
@Rudloff the library you suggested uses a regular iFrame player under the hood. This can be achieved in many ways and is not the objective of this library
