### ISSUE TITLE
Fullscreen launches always in Landscape on Android

### ISSUE THREAD

**Issue by gschattenhofer** [inProgress-team/react-native-youtube#289]
Is there a way to force playing the video on Portrait from the beginning on Android? I've tried using react-native-orientation but it ignores it.

**Comment by Rana-Muhammad-Amir** [comment]
fullscreen = {true}
change it to 
 fullscreen = {flase}

**Comment by senthilsivanath** [comment]
@Rana-Muhammad-Amir  Didn't work for me. Had to move to stand alone player in android.

**Comment by GastonSchWun** [comment]
@Rana-Muhammad-Amir I need it to play it only on fullscreen. I've finally decided to fork the repo and handle the orientation natively customizing the events listeners.

**Comment by GeoffreyPlitt** [comment]
@senthilsivanath What's the stand alone player? link?

**Comment by bhaveshdaswani93** [comment]
@GastonSchWun GastonSchWun
Can you provide the code on how to do it natively

**Comment by gschattenhofer** [comment]
@bhaveshdaswani93 I lost access to that GitHub account but you can see the commits made on the forked repo at that user repo.

Link:
- https://github.com/GastonSchWun/react-native-youtube/commits/master

Notes:
- Be aware I have never updated the repo after those commits.
- I'm not a JAVA programmer so i can't guarantee it's nice nor following the best practices.
- I can not share code from the app it self.

I hope it's useful to you :)
