### ISSUE TITLE
Android singleton ?

### ISSUE THREAD

**Issue by dungnguyen10989** [inProgress-team/react-native-youtube#291]
How to resolve this problem ? 

> Multiple <YouTube /> instances on Android
The YouTube API for Android is a singleton. What it means is that unlike the iOS implementation, no two players can be mounted and play a video at the same time. If you have two scenes that happen to live together, or come one after the other (such as when navigating to a new scene), The new <YouTube /> Will take the focus of the singleton and play the video, but after being unmounted, the older mounted <YouTube /> will not be able to take the role back, and will need to be re-mounted.

**Comment by jayporta** [comment]
It seems you can't. I just used a WebView. Here's an example

```
        <WebView
          style={styles.webView}
          source={{ uri: `https://www.youtube.com/embed/${videoID}?autoplay=0?controls=0?modestbranding=1` }}
          mediaPlaybackRequiresUserAction
          scalesPageToFit
          domStorageEnabled
          bounces={false}
          scrollEnabled={false}
        />
```

**Comment by tlweiii6465** [comment]
@jayporta Hi did you know how can i set the WebView video not plays in inlinesplay not fullscreen on IOS? the IOS screen will auto turn to fullscreen after play

**Comment by davidohayon669** [comment]
Android is a singleton for this library, This is how YouTube API for Android works
