### ISSUE TITLE
Fails to build with Android SDK 26 to library compatibility with 23.0.1

### ISSUE THREAD

**Issue by taboca** [inProgress-team/react-native-youtube#295]
## Problem - when starting the React-native app with SDK 26, react-native-youtube fails to build due to its compatibility with 23.0.1

I recently created a react-native init MyProject and followed the instructions as shown in the readme file. In my system configuration, however, I had the following under ./android/build.grade: 

```
ext {
    buildToolsVersion = "26.0.3"
    minSdkVersion = 16
    compileSdkVersion = 26
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
}
```
And under dependencies: 

```
        classpath 'com.android.tools.build:gradle:2.3.3'
```

When attempting to build the whole system, based in the example, it got an error claiming that I didn't sign the terms/agreements for the 23.0.1. 

## Workaround 

When I looked this project source code, I was able to identify: 

https://github.com/inProgress-team/react-native-youtube/blob/master/android/build.gradle

Which have 

```
 buildscript {
    repositories {
        jcenter()
    }

   dependencies {
        classpath 'com.android.tools.build:gradle:1.1.3'
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    lintOptions {
        abortOnError false
    }
}

repositories {
    mavenCentral()
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.facebook.react:react-native:+'
}
```

In order to have the system working, I had to update the above lines to become compatible with the SDK I had installed — after patch is the following: 

```
buildscript {
    repositories {
        jcenter()
    }

   dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.3"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
    }
    lintOptions {
        abortOnError false
    }
}

repositories {
    mavenCentral()
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.facebook.react:react-native:+'
}


```

I wonder how would be an elegant solution here, considering that this library normally comes from npm or that node_modules is usually not part of project repositories. Right now, any new replica of my project I depend on manually patching like the above.

**Comment by taboca** [comment]
I have studied a bit more and I have seen some projects to provide the component specific build.grade to reference the "rootProject".  Here is my patch: 

https://github.com/taboca/react-native-youtube/commit/367d7458ba92b8ea49a446f04455b3ea8423643e

I wonder if a solution like this is considered a problem or would it make sense.

**Comment by mehulmpt** [comment]
@taboca  Yeah bumping the gradle version and compileSdkVersion fixes it for me too! I don't think this would be a problem because it compiles down properly and there are no breaking backward changes with upgraded sdk version. But I'm not sure, so following this thread.

**Comment by hamedhossani** [comment]
The specified Android SDK Build Tools version (28.0.3) , it is below the minimum supported version   for Android Gradle Plugin 3.2.1.

**Comment by davidohayon669** [comment]
https://github.com/inProgress-team/react-native-youtube/releases/tag/v2.0.0-beta.1
