### ISSUE TITLE
Invariant Violation: Native component for "ReactYouTube" doens't exist

### ISSUE THREAD

**Issue by aryalprakash** [inProgress-team/react-native-youtube#300]
I'm stuck on this error :(
`react-native link` was successful.

![screenshot_20180719-160408](https://user-images.githubusercontent.com/3658290/42937161-e52e91e0-8b6d-11e8-96d6-051c8c090dd2.png)

My `package.json` file:

`{
  "name": "VideoProject",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "1.14.0",
    "jest-expo": "~27.0.0",
    "react-test-renderer": "16.3.1"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^6.3.1",
    "expo": "^27.0.1",
    "native-base": "^2.7.1",
    "react": "16.3.1",
    "react-native": "~0.55.2",
    "react-native-youtube": "^1.1.0",
    "react-navigation": "^2.7.0"
  }
}
`

**Comment by ziyafenn** [comment]
Is this android or iOS? I get same error on Android only.

**Comment by ziyafenn** [comment]
I'm getting same error on Android. On iOS all works fine.

I have created an API key for android.

Any ideas?

**Comment by ziyafenn** [comment]
@aryalprakash that's weird! I don't use expo...

**Comment by mhannan** [comment]
I am also getting same error, I am using `expo` but I am not sure which kind of changes I'll need to make in my code in order to run Youtube video player. `expo` initializes the project and has its own configuration, so how those can be converted into a working form.

**Comment by Goethe0** [comment]
Im also having this problem w/ expo, I have checked manually, all the links and all of them, looks fine.
