### ISSUE TITLE
substitute for expo?

### ISSUE THREAD

**Issue by johnnykoo84** [inProgress-team/react-native-youtube#303]
so by reading some threads here, I now understand react-native-youtube does not support Expo. Now I wonder what other folks use substitute for Expo. 

I appreciate the tip. 

Thank you :)

**Comment by hevinxx** [comment]
Set up your project with "react-native init", not "create-react-native-app" nor using Expo.
This will solve your problem.

**Comment by joao-alberto** [comment]
@johnnykoo84 I think the only way is using [WebView](https://facebook.github.io/react-native/docs/webview)

```
<WebView
    style={{flex:1}}
    javaScriptEnabled={true}
    source={{uri: 'https://www.youtube.com/embed/sBzrzS1Ag_g?rel=0?rel=0&autoplay=0&showinfo=0&controls=0'}}
/>
```

**Comment by sin2** [comment]
If you app is detached you can use it.

**Comment by davidohayon669** [comment]
@johnnykoo84 Expo is not supporting native libraries AFAIK. This library access native modules in Android and iOS

**Comment by Samide47** [comment]
@joao-alberto  WebView is not working on Android devices 5.1 :( :(
