### ISSUE TITLE
There was an error initializing the YouTubePlayer (INTERNAL_ERROR)

### ISSUE THREAD

**Issue by sovanndyul** [inProgress-team/react-native-youtube#304]
I have an issue every time run with android  'There was an error initializing the YouTubePlayer (INTERNAL_ERROR)' 
<img width="1273" alt="screen shot 2018-08-03 at 4 38 35 pm" src="https://user-images.githubusercontent.com/35282187/43636411-31b3eba8-973c-11e8-9aee-8c3978e25af2.png">
.
YouTubeStandaloneAndroid.playVideo({
          apiKey: 'API_KEY',
          videoId: 'lctaXe3s3Ws',
          autoplay: true,
          startTime: 120,
          lightboxMode: false
        })
          .then(() => console.log('Standalone Player Exited'))
          .catch(errorMessage => console.error(errorMessage))
I can play video with iOS very well that have code likes 
YouTubeStandaloneIOS.playVideo(youtubeId)
          .then(() => console.log('Standalone Player Exited'))
          .catch(errorMessage => console.error(errorMessage))
Could you guys help resolve issue with android ?

**Comment by JPodz** [comment]
You might want to remove your API key from your question.

**Comment by hungnt167** [comment]
I also see the same error on Kitkat android physical device. If you try start a simulator has higher android ver (ex:  9.0) ,it works
