### ISSUE TITLE
Android // Youtube player view breaks when I minimize on full screen

### ISSUE THREAD

**Issue by JongGyuChoi** [inProgress-team/react-native-youtube#305]
plz help me

**Comment by JongGyuChoi** [comment]
UNAUTHORIZED_OVERLAY error

**Comment by jassi79ka** [comment]
Same Issue here control loss when screen rotate from full-screen to small screen.

**Comment by GoaGit** [comment]
@JongGyuChoi @jassi79ka if you are using react-native-navigation, this link might help you out https://github.com/inProgress-team/react-native-youtube/issues/161#issuecomment-338648074

The Youtube container detects an overlay (which means some screen is on top of the Youtube video) and therefore stops. You should comment all code in this repo that is related to the fab/snackbar container.

**Comment by JongGyuChoi** [comment]
@GoaGit Thanks for your advice ! but My project is using react-navigation. is that same both library?

**Comment by GoaGit** [comment]
@JongGyuChoi react-navigation and react-native-navigation are different repositories. I am referring to react-native-navigation. You might want to find code similar to the description that I gave in the library you are using. Anything in a view that could overlap the Youtube container might cause this problem.
