### ISSUE TITLE
can i modify onProgress method from 500ms to 100ms 

### ISSUE THREAD

**Issue by jin3378s** [inProgress-team/react-native-youtube#307]
thankyou

**Comment by kraksin** [comment]
Is there a way around this?

**Comment by webdevbyjoss** [comment]
There is no such possibility so far.

**Comment by davidohayon669** [comment]
no

**Comment by miracle2k** [comment]
The 500ms are defined here: https://github.com/youtube/youtube-ios-player-helper/blob/master/youtube-ios-player-helper/Assets.bundle/Assets/YTPlayerView-iframe-player.html#L58

It seems at this time, a fork is required to change the value.
