### ISSUE TITLE
[IOS] Not good support for iphone x

### ISSUE THREAD

**Issue by tiendinh595** [inProgress-team/react-native-youtube#310]
I'm having a problem, when running the app on iPhoneX click the full screen button then the video will not play.
![image](https://user-images.githubusercontent.com/8623356/44295905-04fd9580-a2dd-11e8-8f65-756f5e3847fe.png)

**Comment by ducngv** [comment]
same, black screen when fullscreen on iPhone X simulator

**Comment by goodhyun** [comment]
<img width="964" alt="screen shot 2018-09-04 at 4 30 06 pm" src="https://user-images.githubusercontent.com/4727708/45034878-9cac0380-b093-11e8-90d3-12c4d4a1def5.png">

Could you be more specific on how it is not working out?

**Comment by ducngv** [comment]
@goodhyun i use it with https://github.com/happypancake/react-native-scrollable-tab-view
When i press fullscreen button, tabbar change to another tab automatically
When exit fullscreen mode,  tab change automatically again
So i have black screen in fullscreen mode
I don't know why press fullscreen can activate `onChangeTab ` function
Rewrite proj use tabbar react-navigation is working fine
