### ISSUE TITLE
Video Unavailable (only on IOS)

### ISSUE THREAD

**Issue by jdadojr** [inProgress-team/react-native-youtube#314]
Hi,

Using the videoId T-fSsXqH-Qk
I am able to play it on Android without a problem.
However, on IOS, the video will just flash in half a
second (or less) then will show Video Unavailable.

What could be causing this?

Thanks

**Comment by jdadojr** [comment]
adding this
  origin="http://www.youtube.com"
solved the issue

**Comment by lavarajallu** [comment]
{Platform.OS === "android" ? (
              <WebView
                style={{ alignSelf: "stretch", height: 248 }}
                source={{ uri: "https://www.youtube.com/embed/" + getFinalId }}
              />
            ) : (
              <YouTube
                videoId={getFinalId}
                fullscreen={true}
                onReady={e => this.setState({ isReady: true })}
                onChangeState={e => this.setState({ status: e.state })}
                onChangeQuality={e => this.setState({ quality: e.quality })}
                onError={e => this.setState({ error: e.error })}
                style={{ alignSelf: "stretch", height: 248 }}
              />
            )}
