### ISSUE TITLE
Cannot Play my video on iPhone6(iOS11.4)

### ISSUE THREAD

**Issue by akjesto** [inProgress-team/react-native-youtube#316]
I tried to load example app on my iPhone 6(iOS 11.4) , its always showing black screen.I dont know what is the issue happend.In my iPhone6S(iOS 11.0.3) same app running successfully and also loaded the video.

**Comment by aliustaoglu** [comment]
+1
We are also experiencing this issue. It works fine for IOS 12 though. Any updates?
