### ISSUE TITLE
is there a way to use this library on Android without installing Youtube application ?

### ISSUE THREAD

**Issue by Er-rchydy** [inProgress-team/react-native-youtube#317]
Hey
I was wondering if there are a work around to use this library on Android without installing Youtube application .

**Comment by gianpaj** [comment]
No. You'll get an error:
https://github.com/inProgress-team/react-native-youtube/blob/1c2d9dca67653dd540ea850ec53a221a12493e09/android/src/main/java/com/inprogress/reactnativeyoutube/YouTubeStandaloneModule.java#L140-L143

The library uses the [YouTube Android Player API](https://developers.google.com/youtube/android/player/)

**Comment by Er-rchydy** [comment]
ok thanks

**Comment by davidohayon669** [comment]
no
