### ISSUE TITLE
YouTubeStandaloneIOS player error on play - YTError

### ISSUE THREAD

**Issue by psycura** [inProgress-team/react-native-youtube#319]
RN: 0.55.4
react-native-youtube: 1.1.0
I started to receive this error:

> ExceptionsManager.js:71 Error: YTError
>     at createErrorFromErrorData (NativeModules.js:121)
>     at NativeModules.js:78
>     at MessageQueue.__invokeCallback (MessageQueue.js:398)
>     at MessageQueue.js:137
>     at MessageQueue.__guardSafe (MessageQueue.js:314)
>     at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:136)
>     at debuggerWorker.js:70
> reactConsoleErrorHandler @ ExceptionsManager.js:71
> console.error @ YellowBox.js:69
> (anonymous) @ YouTubeVideo.js:33
> tryCallOne @ core.js:37
> (anonymous) @ core.js:123
> (anonymous) @ JSTimers.js:295
> _callTimer @ JSTimers.js:152
> _callImmediatesPass @ JSTimers.js:200
> callImmediates @ JSTimers.js:464
> __callImmediates @ MessageQueue.js:327
> (anonymous) @ MessageQueue.js:145
> __guardSafe @ MessageQueue.js:314
> flushedQueue @ MessageQueue.js:144
> invokeCallbackAndReturnFlushedQueue @ MessageQueue.js:140
> (anonymous) @ debuggerWorker.js:70
> 

But some time ago everything work fine

**Comment by goodhyun** [comment]
I'm also getting this error rather sporadically. However, there seem to be a pattern re: which one is getting this error. 

For example, this one is bad, : https://www.youtube.com/watch?v=SX_ViT4Ra7k 

Anyway, we can see this error in the debug console.
`Error: YTError
ExceptionsManager.js:84
code:"error"
domain:"XCDYouTubeVideoErrorDomain"`
`NSLocalizedDescription:"This video is unavailable."`

Looks like this symptom is related to this. 
https://github.com/0xced/XCDYouTubeKit/issues/388

**Comment by goodhyun** [comment]
It was an easy fix.

Just edit your Podfile
` pod 'XCDYouTubeKit', '~> 2.6'`
then `pod update`

You will be now good to go.

**Comment by goodhyun** [comment]
Met another YTError.

`  pod 'XCDYouTubeKit', '~> 2.7.6'`
then
`pod update XCDYouTubeKit`

Need to keep up with the release, as it seems like Youtube API is constantly moving away.

**Comment by davidohayon669** [comment]
XCDYouTubeKit behavior is not this library's responsibility, we use it as-is

If you have some functionality you want to add to the wrapping, please provide a PR
