### ISSUE TITLE
Crashes in iOS12. Gives EXC_BAD_ACCESS randomly on multiple threads.

### ISSUE THREAD

**Issue by wliadmin** [inProgress-team/react-native-youtube#329]
It gives EXC_BAD_ACCESS on multiple places only in XCode 10 & iOS12. I have attached one sample of that thread. It gives this kind of bad access crashes. Please do the required support for iOS 12.

![youtube_thread](https://user-images.githubusercontent.com/9083810/48065974-4756b480-e1f2-11e8-8efd-b9813073e4bc.png)

My XCode version : 10
iOS : 12
React native version : 0.55.4

**Comment by alekseykarpenko** [comment]
+1 same issue on iOS12 only

**Comment by webdevbyjoss** [comment]
+1

**Comment by efkowalchyk** [comment]
+1 our team is hitting this same issue when users close the full screen YT video player and then try to play the video again, but the crash is intermittent. Please @inProgress-team see if you can address this issue soon, and let me know if our team can help in some way.  thanks!

**Comment by manikmahajan65** [comment]
after struggling with this for a couple of days. Finally, following resolved this for me

https://github.com/youtube/youtube-ios-player-helper/pull/331
https://github.com/youtube/youtube-ios-player-helper/pull/331/commits/9a0d4eb40991107ab63b0a2aaf8681470f827804

Hope someone found this helpful.

**Comment by joebochill** [comment]
@manikmahajan65 I made the changes from the PR you linked, but all that renders is a blank white box. Is there a step I'm missing?

**Comment by manikmahajan65** [comment]
@joebochill Simply updating YTPlayerView.h and YTPlayerView.m files, will work

**Comment by rnowm** [comment]
Same as @joebochill I get a blank video replacing YTPlayerView.h and YTPlayerView.m.
@manikmahajan65 if that works for you, could you please create a PR in that repo? I could test that again in my app

**Comment by dallen4** [comment]
@rnowm I didn't completely replace the files but updated all the corresponding references by reading through the git diff he linked to. Did the trick for me.

If you guys like, I will commit the changes to a fork and you all can try implementing that version of the module. If it works, I'll submit a PR.

**Comment by nonotest** [comment]
I have been using this fork GroupXTech/react-native-youtube for a while with no significant issues.

**Comment by farad4y** [comment]
https://github.com/up-inside/react-native-youtube-sdk

**Comment by davidohayon669** [comment]
https://github.com/inProgress-team/react-native-youtube/releases/tag/v2.0.0-beta.2
