### ISSUE TITLE
Error while building release apk

### ISSUE THREAD

**Issue by eshantbist** [inProgress-team/react-native-youtube#331]
While I was trying to make a build of app, it was showing this error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-youtube:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

What is the solution to this problem?

**Comment by marksturm** [comment]
Open your android/build.gradle

and pass on line 23 (before: allprojects { ... ):

```
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 27 
                buildToolsVersion '27.0.3'
            }
        }
    }
}
```

**Comment by iChwn** [comment]
@marksturm Thanks that's work

**Comment by davidohayon669** [comment]
#370
