### ISSUE TITLE
Youtube subscribe button

### ISSUE THREAD

**Issue by ilyakar** [inProgress-team/react-native-youtube#333]
Hi,

Is there a way to add a Youtube subscribe button into my react-native app?

Something like this: https://developers.google.com/youtube/youtube_subscribe_button

Thanks!
Ilya

**Comment by mighty6ft5max** [comment]
trying to do this also. the problem seems to be because using className instead of class, I think

**Comment by davidohayon669** [comment]
@ilyakar what you linked to is for html
