### ISSUE TITLE
[Android] Video is played with wrong aspect ratio in some cases

### ISSUE THREAD

**Issue by webdevbyjoss** [inProgress-team/react-native-youtube#334]
**Platform:** Android only
**Versions:** 
- react-native v55
- react-navigation v2.12.1
- react-native-youtube v1.1.0

**Example of vertical video:** [https://www.youtube.com/watch?v=qr64OXFDD7A](https://www.youtube.com/watch?v=qr64OXFDD7A)

I'm building a catalog of handpicked videos, and the whole app is basically 2 screens: a list and details (player) view.

**Reproducing steps:**
1. Play random 9x16 video
2. Navigate to list and open next video (which is vertical)

**Actual:** Video is stretched
<img width="295" alt="screenshot 2018-11-28 13 58 24" src="https://user-images.githubusercontent.com/402001/49152819-a785d580-f31c-11e8-98c6-c549d13649a2.png">

**Expected:** Video played with proper aspect ratio
<img width="307" alt="screenshot 2018-11-28 14 01 26" src="https://user-images.githubusercontent.com/402001/49152779-92a94200-f31c-11e8-8f34-947928e18fe1.png">

**The workaround:** navigate away from the screen (player control is unmounted) and return back to the **exact same** video (player control is mounted again) - now the video is refreshed and plays with proper aspect ratio as expected.

I may be wrong, but It feels like video player on Android (which is singleton?) doesn't refresh video metadata in this particular case, and does that when the video is played for the second time. 

- Is there a way to reset player instance?
- Or maybe the way to force reloading the video metadata?
- Any other hacks and tricks to force a player to stretch the video properly

**Comment by Kisepro** [comment]
Same problem

**Comment by webdevbyjoss** [comment]
A similar outcome is observed when entering fullscreen mode and returning back:
https://github.com/inProgress-team/react-native-youtube/issues/345
Still didn't manage to fix the issue.

**Comment by Delwalt** [comment]
Did anyone find the solution for this issue? I am also having same problem.

**Comment by davidohayon669** [comment]
you can check if c9a0c38c1799f7cfb7d3ad9435ad834c52ba56d8 does the trick for you
