### ISSUE TITLE
youtube view controll can't load in android

### ISSUE THREAD

**Issue by AkshayItaliya** [inProgress-team/react-native-youtube#337]

**Comment by Kisepro** [comment]
Was working yesterday night, and this morning same problem.  Only the preview image load.
I reproduced on a virgin project.

![image](https://user-images.githubusercontent.com/7433141/49375509-cc0af480-f704-11e8-9e89-e373a3c54671.png)

**Comment by Kisepro** [comment]
It seems to be only on emulator, not on the phone

**Comment by IacoCesar** [comment]
Use a height hack on [#131](https://github.com/inProgress-team/react-native-youtube/issues/131#issuecomment-314456875) solved my problem with view controls

**Comment by davidohayon669** [comment]
solved in c9a0c38c1799f7cfb7d3ad9435ad834c52ba56d8
