### ISSUE TITLE
Invariant Violation: requireNativeComponent:"ReactYoutube" was not found in UIManager.

### ISSUE THREAD

**Issue by dark5611** [inProgress-team/react-native-youtube#339]
![screenshot_20181205-162743_project](https://user-images.githubusercontent.com/22434695/49545182-e2eb4b80-f8aa-11e8-816c-d952c4ab9580.jpg)

**build.gradle**

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}

**package.json**

{
  "name": "Project",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.1",
    "react-native": "0.57.7",
    "react-native-deprecated-custom-components": "^0.1.2",
    "react-native-material-design-searchbar": "^1.8.0",
    "react-native-scrollable-tab-view": "^0.10.0",
    "react-native-vector-icons": "^6.1.0",
    "react-native-youtube": "^1.1.0"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.50.0",
    "react-test-renderer": "16.6.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

Can someone please help me resolve this on android

**Comment by kyhnlbyrk** [comment]
same issue any fixes? w

**Comment by SuperBesse** [comment]
In your mainApplication, have you add the ReactNativeYouTube package ?

`import com.inprogress.reactnativeyoutube.ReactNativeYouTube;`

and in the `getPackages()` method, add `new ReactNativeYouTube()`

**Comment by Rufyi** [comment]
> In your mainApplication, have you add the ReactNativeYouTube package ?
> 
> `import com.inprogress.reactnativeyoutube.ReactNativeYouTube;`
> 
> and in the `getPackages()` method, add `new ReactNativeYouTube()`

Yea I already have those things

**Comment by Rufyi** [comment]
Did you fix the problem? I came back to this after a while and got an error saying compile' is obsolete and has been replaced with 'implementation' and 'api'  for react-native-youtube and my app module.  I changed all the complies in build.gradle files to implementation and built my project again it seemed to have fixed the problem but not sure if that is the actual solution.

**Comment by ygtbzkrt** [comment]
guys can u fix this problem. I got same error.

**Comment by budet-b** [comment]
Same here.

**Comment by arvput** [comment]
Facing the same issue any fix?

**Comment by ramazord** [comment]
> In your mainApplication, have you add the ReactNativeYouTube package ?
> 
> `import com.inprogress.reactnativeyoutube.ReactNativeYouTube;`
> 
> and in the `getPackages()` method, add `new ReactNativeYouTube()`

@SuperBesse this fix the issue for me, in my case using react-native link doesn't import the package to mainapplication.java, so this should do if you have same issue

**Comment by MssMaster** [comment]
facing the same issue

**Comment by JVictorV** [comment]
I managed to fix that by: 
1. installing the component
2. running `react-native link react-native-youtube`
3. `cd android && gradlew clean`
4. `react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`

(if step 4 fails just create the missing folders manually, you will probably have to create the assets one)

**Comment by simransinghkataria** [comment]
change
 `compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.facebook.react:react-native:+`
to 
`implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.facebook.react:react-native:+'`

and remove
`buildToolsVersion "23.0.1"`

 in node_modules/react-native-youtube/android/build.gradle

**Comment by sauravsolanki** [comment]
> In your mainApplication, have you add the ReactNativeYouTube package ?
> 
> `import com.inprogress.reactnativeyoutube.ReactNativeYouTube;`
> 
> and in the `getPackages()` method, add `new ReactNativeYouTube()`

This work for me too.

**Comment by ParthChugh** [comment]
I was trying to add react-native-youtube by creating react-native-creating-library, the new version of react-native i.e., 0.60.3, supports auto-linking, still getting ReactYoutube was not found.

**Comment by SmiljanicN** [comment]
@ParthChugh +1

**Comment by timraybould** [comment]
In addition to adding those two lines mentioned above to `MainApplication.java`, I also had to add this to `settings.gradle`:

    `include ':react-native-youtube'`
    `project(':react-native-youtube').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-youtube/android')`

And this to the dependencies in `build.gradle`:
    `implementation project(':react-native-youtube')`

**Comment by davidohayon669** [comment]
@timraybould is this problematic with v2?

**Comment by timraybould** [comment]
@davidohayon669 good question, I'm not sure. I'm on 1.1 given I'm on React Native 59.10.

**Comment by davidohayon669** [comment]
@timraybould ok.. I hope this is all handled in the next version that will get out of beta soon

**Comment by MITDD6338** [comment]
@SuperBesse IOS generated  this  Error

<img width="429" alt="Screenshot 2019-11-11 at 4 21 08 PM" src="https://user-images.githubusercontent.com/31823903/68581863-54f6e800-049f-11ea-9131-e914b5ced8d0.png">

can you help me ?

**Comment by amitjaiswal-sonu** [comment]
i'm new in react-native...using expo-cli for it, got same issue here. Isn't this feature working on expo??

**Comment by ishara28** [comment]
Same error. Any fixes???

**Comment by paragmore** [comment]
> i'm new in react-native...using expo-cli for it, got same issue here. Isn't this feature working on expo??

It wont work in expo as you have to link files with native modules you can eject your project or use react-native-youtube-iframe it supports expo

**Comment by Badarch** [comment]
I just added __import com.inprogress.reactnativeyoutube.ReactNativeYouTube;__ to my MainApplication.java and rebuilt my project.

Now it is working fine :D

**Comment by ger88555** [comment]
To those on an Expo managed project: see the answer [to this post on Expo Voters](https://expo.canny.io/feature-requests/p/react-native-youtube). They now offer a way to use `react-native-youtube` without ejecting. There are some drawbacks tho:
1. You can still use Expo Go, except when executing the parts of your code that import `react-native-youtube`.
2. You won't need Expo Go, all of it's features are available in [expo-dev-client](https://docs.expo.dev/development/getting-started/#installing--expo-dev-client--in-your-project). You WILL have to build a development client for your device/emulator using `expo run:[android|ios]` first.
3. You'll have some native code for both iOS and Android lying around in your codebase, but your project will still be compatible with all Expo Managed Workflow features.
4. You'll now have to use ```eas-cli``` in case you're still using ```expo-cli``` to build your binaries.
