### ISSUE TITLE
Youtube Video Restricted

### ISSUE THREAD

**Issue by adrianha** [inProgress-team/react-native-youtube#34]
Is it possible to play video from VEVO? because i got this issue.. If i pass the origin property with "https://www.youtube.com/", it is still not working.. Any solutions? @paramaggarwal 

![vevorestricted](https://cloud.githubusercontent.com/assets/5382429/10583338/904b894a-76b6-11e5-87aa-033417d64b44.png)

**Comment by Mokto** [comment]
@adrianha Some videos are restricted. What is the youtube video id please ?

**Comment by adrianha** [comment]
try this @Mokto 6GUm5g8SG4o or this xo1VInw-SKc...
Thanks

**Comment by Mokto** [comment]
It's weird, both works in my apps (both mobile and web).

I did use origin='http://www.songpeek.com'.

Is it changing things for you by any chance ?

**Comment by adrianha** [comment]
I've used 'http://www.songpeek.com' as the origin, the video still got an error..
Heres my code:
<YouTube
          ref="youtubePlayer"
          videoId={this.props.videoId} // The YouTube video ID
          play={false}           // control playback of video with true/false
          hidden={!this.state.isReady}        // control visiblity of the entire view
          playsInline={true}    // control whether the video should play inline
          origin="http://www.songpeek.com"

          onReady={(e)=>{this.setState({isReady: 'true'})}}
          onChangeState={(e)=>{this.setState({status: e.state})}}
          onChangeQuality={(e)=>{this.setState({quality: e.quality})}}
          onError={(e)=>{this.setState({error: e.error})}}
          onProgress={(e)=>{this.setState({currentTime: e.currentTime, duration: e.duration})}}

          style={{alignSelf: 'stretch', height: 250, backgroundColor: 'black', marginVertical: 10, marginTop: 2}}
        />

Is it possible because of the country? I live in Indonesia by the way..
any idea?

**Comment by adrianha** [comment]
@Mokto

**Comment by Mokto** [comment]
Oh yes, you are right, it must be because of that...

**Comment by adrianha** [comment]
any solutions @Mokto ? :cry:

**Comment by Mokto** [comment]
No it's sad but in my experience, some videos are just not working in some countries.

The weird thing is that I usually get "The video is not available in your country".

Maybe someone else could help you better than me !

**Comment by adrianha** [comment]
@Mokto do u have sample project that can run those videos with videoId 6GUm5g8SG4o or xo1VInw-SKc?
I'm still curious about this problem...

**Comment by Mokto** [comment]
Please ping me if you still need informations about this.

**Comment by tirrorex** [comment]
@Mokto Hi, if you have some updates on that I would appreciate it, as the only reason i want to use this framework in the first place is to read vevo videos

**Comment by davidohayon669** [comment]
@tirrorex Vevo videos are unplayable with this component

**Comment by tirrorex** [comment]
@davidohayon669 tried it yesterday and they play actually.

**Comment by davidohayon669** [comment]
@tirrorex It all depends on the underlying module https://github.com/youtube/youtube-ios-player-helper

**Comment by tirrorex** [comment]
@davidohayon669 I'm talking about android mate, for ios we have an app in swift ;)

**Comment by davidohayon669** [comment]
@tirrorex AFAIK there was never a problem playing vevo videos on the Android version
