### ISSUE TITLE
Youtube view count is not update, when we play the video using this player.

### ISSUE THREAD

**Issue by PasinduDineth** [inProgress-team/react-native-youtube#341]
HI. I have configured the player to my react native app. Everything is working  fine. But when i watch the video using the app, it won't update the view count of the youtube video. How to fix this? I played  few times, event checked with the youtube dashboard real time view. No views yet. Any fixes? Thanks!!

**Comment by davidohayon669** [comment]
This library is just a wrapper around an iFrame that embeds YouTube's official embedded player, inside an iOS WebView. However this iFrame player behaves regarding view count is the iFrames responsibilty
