### ISSUE TITLE
In go back of fullscreen mode, the proportion is not re-adjusted

### ISSUE THREAD

**Issue by nicolascbarbosa** [inProgress-team/react-native-youtube#345]
This happened on Android.

**Comment by GoaGit** [comment]
@nicolascbarbosa is the issue you are experciencing similar to what you can see in this gif:

1. Have phone in portrait position and start a video that is embedded in the react-native-youtube component
2. Enlarge video by clicking enlarge icon 
3. Rotate device - landscape position
4. Rotate device back to portrait position: video automatically rotates, but the controls and video position are off

![](https://media.giphy.com/media/ycBIiWpdUSQeeDQRhS/giphy.gif)

**Comment by mananjobanputra** [comment]
I am getting the same issue. Any idea How to manage?

**Comment by webdevbyjoss** [comment]
Not yet, as far as I know. By looking at the Android source code, there is no way to reset a player from the API or force the aspect ratio recalculation.

**Comment by mananjobanputra** [comment]
Currently, It is working by below fixing. I have used example code of this repo and change width by some minor numbers on onReady event and also change width again after some timeout so it will get some more space after rendering the control. Maybe useful to someone.

` onReady={e => {
          this.setState({
            containerWidth: this.state.containerWidth + 3
          })
          setTimeout(() =>
            this.setState({
              containerWidth: this.state.containerWidth + 10
            }), 500);
        }}`

**Comment by Albert0405** [comment]
#362 try this

**Comment by davidohayon669** [comment]
sovled in c9a0c38c1799f7cfb7d3ad9435ad834c52ba56d8
