### ISSUE TITLE
Example app doesn't compile: ":CFBundleIdentifier", Does Not Exist

### ISSUE THREAD

**Issue by brownieboy** [inProgress-team/react-native-youtube#347]
The example app doesn't compile for iOS in XCode 10.1 for me.  It fails with the error:

> Failed to install the requested application
> The bundle identifier of the application could not be determined.
> Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
> Print: Entry, ":CFBundleIdentifier", Does Not Exist

But the Bundle Identifier field in info.plist _does_ have a value, which is:

> org.reactjs.native.example.$(PRODUCT_NAME:rfc1034identifier)

In Xcode's Info screen, the Bundle Identifier field shows:

> org.reactjs.native.example.RCTYouTubeExample

So that all looks good to me.

I followed the instructions in the documentation.  I did `react-native link` and `rnpm link`.

**Comment by claudepark** [comment]
you have to change react-native version 0.54 -> 0.57 in package.json.
and execute  'react-native upgrade'

**Comment by davidohayon669** [comment]
newest version should be working fine
