### ISSUE TITLE
Android port of the youtube component?

### ISSUE THREAD

**Issue by bozzmob** [inProgress-team/react-native-youtube#35]
I would be glad to help to have a same port to android. @paramaggarwal Planning to start one?

**Comment by paramaggarwal** [comment]
This repo does need it. Open to PRs!

**Comment by shishircc** [comment]
I also need an android version. I will be working on it soon. @bozzmob do you want to divide this work ? 

What kind of work would this involve? Google has an android version of youtube player api which we can wrap inside a react native module (https://github.com/youtube/yt-android-player , https://developers.google.com/youtube/android/player ). 

My only concern with the initial documentation of this API, is that it requires developer to key in the developer API key. This is not big issue but the IOS version looks like it is simpler with no need of API key.

**Comment by bozzmob** [comment]
@shishircc  Yes. Sure. We can start the work. I have developed a Native Youtube Component and used it as a plug-in in one of my earlier Cordova project. Let me know if it helps.

**Comment by mariostallone** [comment]
The implementation would be a little tricky as there are caveats to how the youtube sdk works on Android, specifically when there's more than one video on screen... Playing a single video on screen would work fine...

**Comment by Mokto** [comment]
+1. You also cannot add another component on top of YouTube video player.

**Comment by paramaggarwal** [comment]
I believe these caveats would be ok to live with in the beginning. I believe the iOS one also plays only one video at a time, and that you cannot add subviews to it.

**Comment by shishircc** [comment]
@bozzmob , if you have a cordova version, maybe this https://github.com/axemclion/react-native-cordova-plugin can be used to just use it directly in the react-native . Otherwise we can wrap the java implementation into a module. 

Some of the implementations work using the youtube app on android. I guess that is reasonable assumption.

How about starting work on this next week Monday ?

**Comment by bozzmob** [comment]
@shishircc  I am AFK for the next 4 days. I am travelling. Yes, we can try the cordova version first. I can push some code I have soon. But, since the iOS version is build using native way, shall we also start with that? (Just a thought)

Has anyone tried cordova plugins v/s react native way of writing Java code? We need performance analysis.

**Comment by mikedizon** [comment]
+1

**Comment by mikedizon** [comment]
@bozzmob @shishircc Hey guys, have either of you had any luck with Cordova?

**Comment by razat2013** [comment]
Hey guys, Is anybody working for the android port for the youtube component?

**Comment by shishircc** [comment]
Hi all,

I am presently working on iOS version of my app. I would return to Android
version in a month.

As I suggested, you can try using these two together
1. https://github.com/axemclion/react-native-cordova-plugin
2.  (https://github.com/Glitchbone/CordovaYoutubeVideoPlayer) or  (
https://github.com/RemcoB00/cordova-phonegap_youtube_player_api_android)

as a quick fix to implement the youtube control on react native

Regards,
Shishir

**Comment by karannakai** [comment]
I've been trying to implement this last night and this is the main issue right now - The YouTubePlayerView can only be used in a class that extends YouTubeBaseActivity which means I can't pass directly to the ViewManager. I can make an activity that extends YouTubeBaseActivity and loads the YouTubePlayerView but it seems impossible to be able to send this View to the ViewManager.

Any thoughts?

**Comment by mikedizon** [comment]
I'll be working on the Android port this week, or at least experimenting.  The YouTube iOS Player Helper uses the YT's iframe API (https://developers.google.com/youtube/iframe_api_reference?hl=en)

For this to work, it seems that one would have to load the contents of the YTPlayerView-iframe-player.html file into an Android WebView (http://developer.android.com/reference/android/webkit/WebView.html). However, it seems that react-native doesn't officially support webviews (https://github.com/facebook/react-native/issues/2701).

**Comment by bozzmob** [comment]
@mikedizon @karannakai Give me some time. By end of the day, I will commit whatever code I had used earlier for my cordova project. We can all fork it and start working on it.

Oh! yes as @mikedizon said the cordova approach won't work I guess. As there is a WebView involved.
But, we can have a look at-
https://github.com/rgaidot/react-cordova
https://github.com/axemclion/react-native-cordova-plugin

**Comment by mikedizon** [comment]
@bozzmob the goal is to keep the design of the android version as close as possible to the iOS version.

The issue I mentioned above references a component someone wrote for WebView. I imagine that the design for this YouTube player can borrow some inspiration from there.

https://github.com/lucasferreira/react-native-webview-android

**Comment by bozzmob** [comment]
@mikedizon Agreed. Just saying, this was the [Youtube Plugin](https://github.com/Glitchbone/CordovaYoutubeVideoPlayer) of Cordova I had used. Checked all my old codes.

**Comment by balramkhichar** [comment]
@bozzmob any update on android port?

**Comment by bozzmob** [comment]
Sorry @balramkhichar I have not got enough time to work on the port. But, I have given a reference to the cordova project that I had used earlier. It can be used as a great starting point to build the native bridge/plugin.

**Comment by BastienAlvez** [comment]
Can we use the cordova plugin inside react native app ?

**Comment by shishircc** [comment]
In recent react native, web view is supported in Android. It can be an easy way to show a youtube video by using iframe. Just in case you have not considered that.

**Comment by paramaggarwal** [comment]
Yes, @shishircc - I think the approach forward for a generic YouTube component for iOS and Android would be to use RN's `WebView` component itself.

**Comment by alejomendoza** [comment]
+1

**Comment by balramkhichar** [comment]
@paramaggarwal I tried putting youtube iframe inside RN's webview but it's doesn't work. All I see is a black screen.

**Comment by alejomendoza** [comment]
this might help https://github.com/gajus/youtube-player if we can link the webview javascript with react native

**Comment by ericraio** [comment]
@alejomendoza were you able to get this running on Android?

**Comment by alejomendoza** [comment]
What I found hacking around https://github.com/alinz/react-native-webview-bridge and a javascript youtube player is that events coming from injected javascript won't work. Otherwise using Webview to load the youtube frame and controlling javascript from react native would be a great cross platform solution. For now I would have to stick with using native libraries.

**Comment by paramaggarwal** [comment]
I am not actively maintaining this project and am open to handing over the project to someone who can support it on Android also - making it a complete _Youtube for RN_ package.

**Comment by paramaggarwal** [comment]
Open Bounty: If you can add good support to this repo for an Android YouTube player, I'll hand over this project to you to own and grow.

**Comment by skleest** [comment]
Would love to see any progress on this for Android!

**Comment by gn02394847** [comment]
Android + 1

**Comment by gn02394847** [comment]
solution.
i use this pugin and create hack page. 

react-native-webview-android
https://github.com/lucasferreira/react-native-webview-android

hack page.
https://github.com/gn02394847/youtube-embed-page/blob/gh-pages/index.html

 <WebViewAndroid
                    ref="webViewAndroidSample"
                    javaScriptEnabled={true}
                    geolocationEnabled={false}
                    builtInZoomControls={false}
                    onNavigationStateChange={()=>{}}
                    url={"http://gn02394847.github.io/youtube-embed-page/index.html?id=eESGnrzYVL0"}
                    style={{
                        flex:1,
                    }} />


you can change url id = {youtube id}.

**Comment by davidohayon669** [comment]
+1

**Comment by Mokto** [comment]
Looking into this soon ;)

**Comment by eladcandroid** [comment]
+1

**Comment by adeebbasheer** [comment]
Android + 1

**Comment by Mokto** [comment]
Android support on it's way ;)

**Comment by cjmling** [comment]
@Mokto  Any update after 3 months ?

**Comment by jujumoz** [comment]
Android support has been merged, you can try and let me know how is it going. ;)
