### ISSUE TITLE
Play button position is wrong when switching screen on Android.

### ISSUE THREAD

**Issue by kraksin** [inProgress-team/react-native-youtube#354]
If you switch the screen horizontally and vertically in Android, the position of play button is abnormal. It will not be fixed in the center of the image. I want to know if there is a cause for this and what is the solution.

<img width="397" alt="2019-01-29_11-03-19" src="https://user-images.githubusercontent.com/40831445/51879126-8a6d9180-23b5-11e9-99ef-a8e2cd0d7118.png">

**Comment by GoaGit** [comment]
@kraksin this is probably related to #345
