### ISSUE TITLE
logo and title hide fullscreen button

### ISSUE THREAD

**Issue by timurridjanovic** [inProgress-team/react-native-youtube#356]
![image](https://user-images.githubusercontent.com/1295621/52137700-2d721580-2619-11e9-9786-8a0c29d6535a.png)

Is there a way to hide the logo and title or make it shorter so that the fullscreen button is accessible?
I can't hit the fullscreen button this way.

**Comment by wahju** [comment]
YouTube changed this. You can't hide the info anymore: https://developers.google.com/youtube/player_parameters#release_notes_08_23_2018
I'm also looking for a fix.
