### ISSUE TITLE
Gradle Build Fails, Unable to find a matching configuration of project :react-native-youtube

### ISSUE THREAD

**Issue by anasbakro** [inProgress-team/react-native-youtube#358]
I just added the library to my project and it throws this error when running react-native run-android:

**Unable to find a matching configuration of project :react-native-youtube: None of the consumable configurations have attributes.**

I looked online and it said that I should add ` matchingFallbacks = ['release', 'debug']` to build.gradle but it didn't work.
I'm using
"react": "16.6.3",
"react-native": "0.58.1",
Android build tools 28.03
minSdkVersion = 16
compileSdkVersion = 28
targetSdkVersion = 27
supportLibVersion = "26.1.0"

**Comment by anasbakro** [comment]
the issue was a typo in my settings.gradle file

**Comment by rafaelbrandao98** [comment]
What is the error in your setting.gradle?

**Comment by anasbakro** [comment]
Sorry, it was a long time ago I can't remember.
