### ISSUE TITLE
Crash on android

### ISSUE THREAD

**Issue by dantn93** [inProgress-team/react-native-youtube#364]
I have a crash on Firebase Crashlytic, so is the bug from the android native code?

Fatal Exception: java.lang.IllegalStateException
This YouTubePlayer has been released

ltw.a (SourceFile:95)
ltw.l (SourceFile:154)
amuy.dispatchTransaction (SourceFile:134)
dah.onTransact (SourceFile:7)
android.os.Binder.transact (Binder.java:387)
com.google.android.youtube.player.internal.s.play (Unknown Source)
com.inprogress.reactnativeyoutube.YouTubePlayerController$1.run (YouTubePlayerController.java:315)
android.os.Handler.handleCallback (Handler.java:739)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)

**Comment by HashDot** [comment]
See: https://github.com/inProgress-team/react-native-youtube/issues/238#issuecomment-474840965
