### ISSUE TITLE
Doesn't works after update my iOS mac version

### ISSUE THREAD

**Issue by armandoarmando** [inProgress-team/react-native-youtube#366]
Hi everyone...yesterday I updated my mac and when I restarted, the component didn't reproduced videos on iPhone simulator (no error messages, no nothing). Only shows a black box. Any idea? thanks!!!

**Comment by arsomjin** [comment]
Any update ?

**Comment by farad4y** [comment]
[https://github.com/srfaytkn/react-native-youtube-sdk](https://github.com/srfaytkn/react-native-youtube-sdk) try this :), we developed new package for a project

**Comment by davidohayon669** [comment]
@armandoarmando, @BatuhanW on iOS when you see a black screen, most times it means that `YTPlayerView-iframe-player.html` is not added to the xcode project.

New version 2 (beta) using RN > 60 installs this file automatically with Cocoapods

**Comment by lukewlms** [comment]
(And YTPlayerView must be removed from xcode project Resources when upgrading to 60+)
