### ISSUE TITLE
Are we allowed to put others Youtube videos while the app is monetized by ads?

### ISSUE THREAD

**Issue by Albert0405** [inProgress-team/react-native-youtube#369]
I am using this plugin to display youtube videos that is not mine. Most of these videos are gameplays from mobile game. Is there anyone out there who uses this library and got a problem uploading their app after this? What if the youtube owner of an specific video i embed report my app? What kind of legal issue will i face?

By the way, my app have other contents that i made myself, it just that i wanted to put youtube videos since my application is a guide app

**Comment by davidohayon669** [comment]
@Albert0405 AFAIK you're not suppose to monetize the content (videos) themselves. If the content helps you to sell something else that it's ok. Google it
