### ISSUE TITLE
How implement currenttime listener on Android?

### ISSUE THREAD

**Issue by lucacastagnotto** [inProgress-team/react-native-youtube#371]
I'd like to use 'currentTime ' method every second and update the state, but since 'currentTime' is a method and not an event, what is the best way to do it? I'd want something lime this:

onChangeState={e => {
    this.setState({ status: e.state });
    if(e.state == "playing"){
         //call currentTime and update the state every second
    }
    else if(e.state == "ended" || e.state == "paused"){
        //stop to call currentTime
     }
  }}

**Comment by saqib006** [comment]
is this issue solved, same issue here

**Comment by lucacastagnotto** [comment]
I did like this:

//onProgressAndroid
  gettime = () => {
    this.youTubeRef
      .currentTime()
      .then(currentTime => {
        console.log("currentTime: "+ currentTime);
        if(currentTime >= myvalue){
          this.pause();
          this.setState({ currentTime: currentTime });
          return(null);
        }
        setTimeout(this.gettime, 500);
    })
  }

**Comment by farad4y** [comment]
Check this out
https://github.com/up-inside/react-native-youtube-sdk

**Comment by davidohayon669** [comment]
@lucacastagnotto setTimeout happens once, you should use setInterval
