### ISSUE TITLE
UIManager warning when using seekTo method

### ISSUE THREAD

**Issue by manzoorwanijk** [inProgress-team/react-native-youtube#373]
Due to #131, I decided to hide the default controls and create my own using [slider](https://react-native-training.github.io/react-native-elements/docs/slider.html), like this:

![Player](https://user-images.githubusercontent.com/18226415/59736475-6123a400-9277-11e9-9353-6412839c6a12.jpg)
----------------------------------
<br>
But, when I change the slider value and set the video position using `seekTo()`, it generates the warning, <b>Accessing view manager configs directly off UIManager via UIManager['ReactYouTube'] is no longer supported. Use UIManager.getViewManagerConfig('ReactYouTube') instead.</b>

Here is the screenshot of the error:

![Warning](https://user-images.githubusercontent.com/18226415/59736382-0db15600-9277-11e9-81ed-8140c0356ddd.png)
<br>
After Googling, I found two similar issues with other components - [here](https://github.com/react-native-community/react-native-video/issues/1463) and [here](https://github.com/react-native-community/react-native-maps/issues/2620)

**Comment by sanjaypojo** [comment]
Facing the same issue!

**Comment by davidohayon669** [comment]
@manzoorwanijk 56c037c15813976f86f225c1ec669e192af33185
