### ISSUE TITLE
rnpm & androidx support

### ISSUE THREAD

**Issue by Shanie1331** [inProgress-team/react-native-youtube#374]
# Requesting update for next releases.

The packages use deprecated "rnpm" config that will stop working from next release of React-native. Please give a release update for the same.
React-Native 6.0 have some breathtaking changes like:
1. completely removing "rnpm" in next release.

<img width="709" alt="Screen Shot 2019-07-08 at 12 51 01 AM" src="https://user-images.githubusercontent.com/27643210/60772935-d9fd7980-a11a-11e9-94c2-25f81509a465.png">

2. AndroidX migration for mantained support lib version. All the support libs are updated to jetpack AndroidX. you can check these changes [here](https://developer.android.com/jetpack/androidx/migrate).

These changes seems mandatory and I will be great if I can help you on same.

**Comment by srfaytkn** [comment]
you can use https://github.com/srfaytkn/react-native-youtube-sdk

**Comment by davidohayon669** [comment]
@Shanie1331 New version v2 (beta) supports RN 60 with Cocoapods deps on iOS and dynamic library imports for Android (managed internally by RN)

This library don't depends on `rnpm` anymore
