### ISSUE TITLE
Android currentTime() function

### ISSUE THREAD

**Issue by saqib006** [inProgress-team/react-native-youtube#376]
I'd like to use 'currentTime ' method every second and update the state, but since 'currentTime' is a method and not an event, what is the best way to do it?
here is the code written down, but app is very slow working stopped working
componentDidMount() {
this.interval = setInterval(() => {
if(this.state.isReady && this.state.isPlaying){
this._youTubeRef
.currentTime()
.then(currentTime => this.setState({ currentTime }))
.catch(errorMessage => this.setState({ error: errorMessage }))
}else{
clearInterval(this.interval)
}
}, 1000)
}

componentWillUnmount() {
clearInterval(this.interval);
}

**Comment by farad4y** [comment]
Check this out
https://github.com/up-inside/react-native-youtube-sdk

**Comment by davidohayon669** [comment]
@saqib006 You'll have to use some kind of interval to call this method periodically
