### ISSUE TITLE
Compatibility with react native 0.60 ?

### ISSUE THREAD

**Issue by alexandre033** [inProgress-team/react-native-youtube#377]
The package is working on react native 0.60 ?
Thanks

**Comment by farad4y** [comment]
@alexandre033 Check this out
https://github.com/up-inside/react-native-youtube-sdk

**Comment by redbluenat** [comment]
+1

**Comment by farad4y** [comment]
@redbluenat 
https://github.com/up-inside/react-native-youtube-sdk

**Comment by sgup** [comment]
The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-youtube: https://github.com/inProgress-team/react-native-youtube#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.

**Comment by davidohayon669** [comment]
@sgup, @redbluenat, @alexandre033 New v2 (beta) is suppose to have no breaking changes but was tested only on RN > 60.0
