### ISSUE TITLE
The "rel" property doesn't work iOS. Though set to false I can see video suggestions at end of video. 

### ISSUE THREAD

**Issue by chetan-zalake** [inProgress-team/react-native-youtube#378]
I tried a lot but no success. Please suggest. Let me know if anyone faced the same issue and resolved. Below is the code how I setup player.

<YouTube
                apiKey=""
                videoId= {Platform.OS === 'ios' ? this.props.videoId : this.props.navigation.state.params.videoId}   // The YouTube video ID
                play={Platform.OS === 'ios' ? false : true}             // control playback of video with true/false
                fullscreen={this.state.fullscreen}       // control whether the video should play in fullscreen or inline
                loop={true}             // control whether the video should loop when ended
                // controls={2}
                playsInline={Platform.OS === 'ios' ? true : false}
                modestbranding={true}
                showFullscreenButton = {false}
                resumePlayAndroid={false} 
                rel = {false}
                onReady={(event) => this.isPlayerReady(event)}
                onChangeState={(event) => this.onChangeState(event)}
                onChangeQuality={e => this.setState({ quality: e.quality })}
                onError={e => this.setState({ error: e.error })}
                style={{ width: '100%', height: '40%' }}
            />

**Comment by elango** [comment]
+1

**Comment by davidohayon669** [comment]
@chetan-zalake In my experience this is ignored in the iOS version. Not something this library can override
