### ISSUE TITLE
0.60 react-native crashes

### ISSUE THREAD

**Issue by SmiljanicN** [inProgress-team/react-native-youtube#383]
Running on MacOS, rn version 0.60.3
After following instructions and linking the package, after component renders, the error is thrown after react-native run-ios command

<img width="286" alt="Screen Shot 2019-08-10 at 19 45 42" src="https://user-images.githubusercontent.com/23521914/62825610-1fe0ae00-bbaf-11e9-9d72-3a488e475d5a.png">

Tried also manual linking to Xcode (Link Binary with Libraries) = build fails 

> In file included from /Users/username/Desktop/react-native/ProjectName/node_modules/react-native-youtube/RCTYouTube.m:6:
> ../react-native/React/Base/RCTBridge.h:10:9: fatal error: 'React/RCTBridgeDelegate.h' file not found
> #import <React/RCTBridgeDelegate.h>
>         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	CompileC /Desktop/react-native/ProjectName/ios/build/ProjectName/Build/Intermediates.noindex/RCTYouTube.build/Debug-iphonesimulator/RCTYouTube.build/Objects-normal/x86_64/RCTYouTubeManager.o /Users/username/Desktop/react-native/ProjectName/node_modules/react-native-youtube/RCTYouTubeManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)

P.S. Andorid is working okay...

**Comment by davidohayon669** [comment]
@SmiljanicN you can try the latest 2.0.0-beta. it's supports RN > 0.60 with Cocoapods

**Comment by SmiljanicN** [comment]
Thank you! It works now! 🎉 🙏 

Ios initiated perfectly
Had few problems with Android (not sure why, could be issues caused by me 👼), anyway... 
Native Component was not found, solved by running `react-native link react-native-youtube` after that build failed "importing NotNull or Nullable and Android Studio won't compile", solved it with this [answer](https://stackoverflow.com/a/56876517/9391087)
