### ISSUE TITLE
warn The following packages use deprecated "rnpm" config that will stop working from next release

### ISSUE THREAD

**Issue by SnehalAgrawal** [inProgress-team/react-native-youtube#386]
Hello Admin,
I am getting this warning while running the project which has react-native-youtube library installed.

warn The following packages use deprecated "rnpm" config that will stop working from next release: - react-native-youtube: https://github.com/inProgress-team/react-native-youtube#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.

**Comment by davidohayon669** [comment]
Version 2 is not dependent on this library. v2.0.0-beta shouldn't have any breaking changes except for installation process. Working in releasing the it as a stable version
