### ISSUE TITLE
Deprecated API Usage - UIWebView

### ISSUE THREAD

**Issue by Ingibjorg** [inProgress-team/react-native-youtube#387]
The library is using UIWebView which is deprecated so I got this note from Apple:

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

Please update the library to use WKWebView.

**Comment by davidohayon669** [comment]
#321 is about to be merged in the coming days
