### ISSUE TITLE
"'WKYTPlayerView.h' file not found" during installation (after manual link)

### ISSUE THREAD

**Issue by danielfein** [inProgress-team/react-native-youtube#389]
I've tried and retried this many times, same error. Currently the steps I've taken:

1. `npm install react-native-youtube -S
2. Project in Xcode -> Libraries -> Add Files -> `node_modules/react-native-youtube/RCTYouTube.xcodeproj` 
3. Then the main project -> Build Phases -> Link Binary With Libraries +libRCTYouTube
4. npm run ios

Then I receive:
`/Users/danfein/Desktop/reviews/native/node_modules/react-native-youtube/RCTYouTube.h:1:9: fatal error: 'WKYTPlayerView.h' file not found
#import "WKYTPlayerView.h"
        ^~~~~~~~~~~~~~~~~~`

Any idea what this may be caused by?

**Comment by davidohayon669** [comment]
@danielfein iOS version from 2.0.0-beta.2 uses another Cocoapod dependency (https://github.com/hmhv/YoutubePlayer-in-WKWebView) linked in the [podspec](https://github.com/inProgress-team/react-native-youtube/blob/v2.0.0-beta.2/RCTYouTube.podspec). I'm not sure how you can manually link that library, but with Cocoapods it should work seamlessly

**Comment by ironworkshop** [comment]
Im trying to avoid cocoapods and do all my linking for ios manually (i've found it less troublesome) so it would be good to know what we can do here. I've kept my version at v1 as well, but as we are seeing ios rejections for the UI Web view usage in this package, it seems v2 may have to be used so this is a bit of a blocker.

**Comment by davidohayon669** [comment]
@ironworkshop I'm pretty sure this pod can be manually linked. You can check in [their repo](https://github.com/hmhv/YoutubePlayer-in-WKWebView)

**Comment by infin1t3** [comment]
1) Add this line to Podfile
` pod 'YoutubePlayer-in-WKWebView', :git => 'https://github.com/hmhv/YoutubePlayer-in-WKWebView'`
2) Run `pod install`

**Comment by danielfein** [comment]
So luck so far. t I see https://github.com/inProgress-team/react-native-youtube/issues/391. Seems it's occurring more and more. :/

**Comment by danielfein** [comment]
Why is this closed?

**Comment by danielfein** [comment]
This never should have been closed....

**Comment by davidohayon669** [comment]
@danielfein Why not? The supported way to link that dependency is with Cocoapods, there might be other ways to do it through XCode but this is not a problem with this library

**Comment by tkulpa** [comment]
Cannot link manually, getting _WKYTPlayerView.h' file not found_ can this issue be open again?

**Comment by danielfein** [comment]
Updating to RN 60 was the only fix, the maintainers of this project are absolutely not helpful lol.

**Comment by davidohayon669** [comment]
@danielfein There is only one maintainer, and he has a full-time job. There must be unlimited information online on how to link iOS libraries without Cocoapods. this is not a specific issue in this library

Also: you are more than welcomed to help maintain this lib

**Comment by Cyberfolks** [comment]
'WKYTPlayerView.h' file not found in RCTyoutube.h

error on line no 1 #import "WKYTPlayerView.h"

**Comment by Cyberfolks** [comment]
im using with react native 59.10 version.

**Comment by kgirma** [comment]
> Updating to RN 60 was the only fix, the maintainers of this project are absolutely not helpful lol.

@danielfein I Absolutely agree haha, It's giving us issues even after upgrading to RN60.0 what is the specific version of RN x.xx.xx that's working for you?

**Comment by davidohayon669** [comment]
@kgirma @danielfein for limited resources I can only maintain RN 60 and up support

**Comment by eleddie** [comment]
For anyone with this issue. I forked the repo and was able to link the library without cocoapods in RN 0.59 just change in your package.json this:
`"react-native-youtube": "eleddie/react-native-youtube#bdf7bce",` 
Then link and it works fine.

**Comment by MathiasLund** [comment]
Still getting this issue using RN 0.59.10 trying to manually link library

**Comment by gloredo** [comment]
A solution for manual link in RN 0.60+

1. Download [YoutubePlayer-in-WKWebView](https://github.com/hmhv/YoutubePlayer-in-WKWebView) zip file
2. Extract the folder in the iOS folder of your project
3. Import the `youtube-ios-player-helper.xcodeproj` in your Xcode project
4. In `YourProjectName.xcodeproj` go to Build Phases > Link Binary With Libraries and add `YouTubeiOSPlayerHelp.framework`
5. In `RCTYouTube.xcodeproj` go to Search Paths > Header Search Paths and add non-recursive `$(SRCROOT)/../../ios/YoutubePlayer-in-WKWebView/WKYTPlayerView`
6. In Xcode go to Product > Clean and finally Product > Build
