### ISSUE TITLE
Video loading with INTERNAL_ERROR

### ISSUE THREAD

**Issue by Xumochuan** [inProgress-team/react-native-youtube#397]
Hi, Thanks for your great Youtube video player.
I am going to use this on my  app.
At first, I have copy and paste code from example of this github repository. 
By the way it shows only loading screen with INTERNAL_ERROR, but internet is okay.
And if I click <b>youtube</b>, then youtube player is opened.
I don't know, why don't show video screen.
Could you do me a favor?
![image](https://user-images.githubusercontent.com/47884397/66073997-d13a0980-e58a-11e9-8709-3531285521ac.png)

This is played on Youtube app.
![image](https://user-images.githubusercontent.com/47884397/66074794-a2bd2e00-e58c-11e9-9814-ef19836ed705.png)

Hope your kind help

Many Thanks

**Comment by srfaytkn** [comment]
you can use https://github.com/up-inside/react-native-youtube-sdk

**Comment by davidohayon669** [comment]
@Xumochuan is this happens with any video? Can you play the same videos with the example app in this repo? can you reproduce the error with the example app?

**Comment by Xumochuan** [comment]
Hi,
In your example repo, there is no youtube api key.
I have youtube link video and api key. 
But, this happen INTERNAL_ERROR.

Thanks

**Comment by davidohayon669** [comment]
AFAIK the API key for Android is not that needed. just put some random string and try if it works

**Comment by escobar5** [comment]
Any reason this issue was closed? this is happening with or without API Key

**Comment by amirhosein5858** [comment]
https://developers.google.com/youtube/android/player
this api is deprecated and no longer works on android
