### ISSUE TITLE
Listening to onFullScreenExit event

### ISSUE THREAD

**Issue by gauravsapiens** [inProgress-team/react-native-youtube#40]
I want to exit youtube player whenever full screen is exited. However, for that I need to listen to `onFullScreenExit` event. Is there any way I could do it?

**Comment by Mokto** [comment]
No it's not possible yet.

PR are welcome ;)

**Comment by sibelius** [comment]
@gauravsapiens any workaround solution for this?

**Comment by tiemevanveen** [comment]
I think something like this could work iOS http://stackoverflow.com/questions/25766365/detect-when-a-webview-video-becomes-fullscreen-on-ios8/34706156#34706156 but needs to be implemented in the lib.. 

```
[[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(VideoExitFullScreen:)
                                                 name:UIWindowDidBecomeVisibleNotification
                                               object:self.view.window];

[[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(VideoEnterFullScreen:)
                                                 name:UIWindowDidBecomeHiddenNotification
                                               object:self.view.window];
```

**Comment by mrwest808** [comment]
Forked and [tried something](https://github.com/mrwest808/react-native-youtube/commit/5544bf1f0dbd97a6674294adc8fceed8fa2c9004) like @tiemevanveen mentioned, seems to work (only for iOS).

Unfortunately I have too little time (and familiarity with Android) to tackle this in a PR atm, but perhaps it can help someone looking for the same.

**Comment by tiemevanveen** [comment]
Awesome! @mrwest808 yeah same here. A PR just for only iOS is not an option?

**Comment by mrwest808** [comment]
@tiemevanveen Yeah I suppose iOS only is better than nothing! 👍

**Comment by IjzerenHein** [comment]
I've implemented this for android in pull request #91. On android it then emits "fullscreenMode" and "windowMode" states in the `onStateChange` callback

**Comment by teameh** [comment]
@davidohayon669 what's the reason this is closed? It's implemented or just that the PR was not active for a while?

**Comment by davidohayon669** [comment]
@teameh there is an `onChangeFullscreen` event now

**Comment by teameh** [comment]
Awesome! Thanks a lot! 👍
