### ISSUE TITLE
How do we use the wkwebview build?

### ISSUE THREAD

**Issue by danielfein** [inProgress-team/react-native-youtube#406]
After creating this issue:
https://github.com/inProgress-team/react-native-youtube/issues/389

It was closed as this build was pushed "[MM-18656] Use WKWebView over UIWebView":
https://github.com/mattermost/react-native-youtube/pull/1

It's not clear how to use this build. Any help would be greatly appreciated.

**Comment by davidohayon669** [comment]
@danielfein What are you having difficulties with? We use the WKWebView as a dependency now that needs to be installed with Cocoapods

**Comment by danielfein** [comment]
I can't get passed "'WKYTPlayerView.h' file not found" and this build appears to be a fix for it. I'm not sure how to use that build, though. It seems that was uploaded a few days ago, and the latest npm publish date was around 2 weeks ago. Just trying to figure out how to use that code so I can actually implement. It seems new integrations of react-native-youtube aren't working for many people.

**Comment by davidohayon669** [comment]
what do you mean by build? a merge? a commit?
Can you try installing and setting the example app in this repo? Should be pretty straight forward if you use cocoapods

**Comment by danielfein** [comment]
I was confused and thought that project was the same. Turns out the issue still exists in this repo. I don't really make sense to set up the example app for me, I'm trying to implement it into a specific project. Following the steps I've received that error every time.

**Comment by davidohayon669** [comment]
Duplicate #389

**Comment by danielfein** [comment]
Upgrading to RN 60 was the only fix.

**Comment by Biplovkumar** [comment]
@danielfein . Agreed from your above comment.
