### ISSUE TITLE
modestbranding not working in android.Does not remove the youtube logo.

### ISSUE THREAD

**Issue by hvaidsain** [inProgress-team/react-native-youtube#410]
How to remove youtube logo(in bottom right) in react-native-youtube library in android.
modestbranding does not work in android.

**Comment by johnckendall** [comment]
YouTube disabled this option quite a while ago

**Comment by hvaidsain** [comment]
> YouTube disabled this option quite a while ago
@johnckendall 
Is there any way we can do some changes in the library to implement this ?

**Comment by hvaidsain** [comment]
Is modestbranding working only with ios and not android and if so then why it is not working with android?

**Comment by davidohayon669** [comment]
@hvaidsain This is the respinsibility ot the underlying [Library](https://developers.google.com/youtube/android/player/)
