### ISSUE TITLE
deprecated "rnpm" config

### ISSUE THREAD

**Issue by zulqarnain26** [inProgress-team/react-native-youtube#422]
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-youtube: https://github.com/inProgress-team/react-native-youtube#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.

**Comment by davidohayon669** [comment]
not present in version 2
