### ISSUE TITLE
Why does Android require the user has the YouTube app?

### ISSUE THREAD

**Issue by pickhardt** [inProgress-team/react-native-youtube#426]
Hi, happy 2020!

I'm looking for a YouTube RN library and from reading the documentation here, it has what I consider a dealbreaker for Android, namely that the end user must have the YouTube app installed themselves.

However, the YouTube Android Player API doesn't seem to have that requirement.

So I'm wondering what the reason this requires the YouTube app be installed and if it's just for certain features perhaps? (Could I get away with it not being installed?) Perhaps this library could make the requirement only be for specific features, if so.

Thanks!

**Comment by davidohayon669** [comment]
@pickhardt it is actually written in the landing page of that library
https://developers.google.com/youtube/android/player/

<img width="659" alt="Screen Shot 2020-01-03 at 0 27 46" src="https://user-images.githubusercontent.com/7001025/71697200-ea3b9c00-2dbf-11ea-9dec-b801bad1e141.png">

**Comment by pickhardt** [comment]
Interesting. I haven't used Android in many years but it looks like YouTube is preinstalled with Android phones, and is virtually impossible to delete. I'm guessing the vast majority of users will have YouTube installed, so this probably isn't a problem like I thought it was going to be.
