### ISSUE TITLE
how to hide the red youtube button?

### ISSUE THREAD

**Issue by faceyspacey** [inProgress-team/react-native-youtube#45]

**Comment by Mokto** [comment]
Set this as props I think it should be enough :

**Comment by Mokto** [comment]
Closing this. Feel free to discuss this here.

**Comment by samyakbhuta** [comment]
Even after setting the above value, the Red Youtube buttons still appears.  Below is the complete snippet.

```html
<YouTube
  ref="youtubePlayer"
  videoId="zmIUm1E4OcI" // The YouTube video ID
  play={false}           // control playback of video with true/false
  hidden={false}        // control visiblity of the entire view
  playsInline={false}    // control whether the video should play inline
  loop={false}          // control whether the video should loop when ended
  rel={false}
  showinfo={false}
  controls={0}
  modestbranding={true}
  onReady={(e)=>{this.setState({isReady: true})}}
  onChangeState={(e)=>{this.setState({status: e.state})}}
  onChangeQuality={(e)=>{this.setState({quality: e.quality})}}
  onError={(e)=>{this.setState({error: e.error})}}
  onProgress={(e)=>{this.setState({currentTime: e.currentTime, duration: e.duration})}}
  style={styles.youtubePlayer}
/>
```

I tried to apply the same parameters directly, and I can see the Red YouTube button in my browser, as well. Wondering what I am doing wrong. One can see it by following the link https://www.youtube.com/embed/zmIUm1E4OcI?showinfo=0&controls=0&rel=0&modestbranding=1

**Comment by Mokto** [comment]
Can you show me a screenshot please ?

**Comment by faceyspacey** [comment]
ur not gonna be able to hide this button. ur only option is to put something over it, such as ur own play button, or the youtube image for the video and a play button on top of that, etc. ..same with the logo in the bottom right that appears for the first 3 seconds of the video playing. ...i did a lot to try to make this work a while back when i was working on this, and these are the solutions i came up with.

**Comment by khadkaPratik** [comment]
One solution I came across is wrapping the YoutubePlay with a view component to disable touch using pointer events as shown below  👍 

```
<View pointerEvents="none">
<YouTube
  ref="youtubePlayer"
  videoId="zmIUm1E4OcI"
/>
</View>
```
