### ISSUE TITLE
Android instructions

### ISSUE THREAD

**Issue by GeoffreyPlitt** [inProgress-team/react-native-youtube#52]
Hi,

How do we run an Android example? Seems to have instructions missing...

**Comment by Mokto** [comment]
Android is still a work in progress. See #51

**Comment by adeebbasheer** [comment]
Any progress ?

**Comment by marister** [comment]
Any estimation on this? Can I help?

**Comment by jujumoz** [comment]
Android support has been merged, you can try and keep me in touch if you have any problems. ;)

**Comment by morelazers** [comment]
Hi @jujumoz, could you provide some instructions on which API key we need for the Android component? I am a little lost trying to find the right one.

**Comment by joncursi** [comment]
@morelazers mind sharing how you were able to configure it? I created a YouTube Data API key and loaded it in via prop but I'm still getting "An error occurred while initializing the YouTube player."

**Comment by joncursi** [comment]
I also added the SHA1 fingerprint in the Google Dev Console.

Are you using Genymotion or AVD? I wonder if it's an issue with Google Play services on my AVD.

**Comment by morelazers** [comment]
@joncursi I was using a device. The problem I was having is that I did not recompile after installing the module.

I turned on the YouTube Data API v3 and then created a generic API key in the dev console, this "worked" for me. I haven't had a chance to fully test on Genymotion/AVD/Device yet because of another issue, but I can see that the player is initialising.

**Comment by jonohodgson** [comment]
@morelazers @joncursi  
I'm having the same issue...  "An error occurred while initializing the YouTube player". 
I did the following:
1. Created a project in Google APIs
2. Enabled YouTube Data API v3
3. Used create credentials to create an unrestricted API key

Have you both had any luck getting this to work? Is there something I'm missing?

**Comment by morelazers** [comment]
@jonohodgson Are you running on device or emulator?

**Comment by jonohodgson** [comment]
@morelazers running on emulator

**Comment by morelazers** [comment]
Sorry for taking so long - here's a code sample that works for me. Are you passing in the apiKey to the component as a prop?

```
<YouTube
  ref="youtubePlayer"
  videoId={videoId}     // The YouTube video ID
  play={false}          // control playback of video with true/false
  hidden={false}        // control visiblity of the entire view
  playsInline={true}    // control whether the video should play inline
  loop={false}          // control whether the video should loop when ended
  modestbranding={true}
  apiKey={"MY_API_KEY"}

  onReady={(e)=>{this.setState({isReady: true})}}
  onChangeState={(e)=>{this.setState({status: e.state})}}
  onChangeQuality={(e)=>{this.setState({quality: e.quality})}}
  onError={(e)=>{this.setState({error: e.error})}}
  onProgress={(e)=>{this.setState({currentTime: e.currentTime, duration: e.duration})}}

  style={{alignSelf: 'stretch', height: 300, backgroundColor: 'black', marginVertical: 10}}
>
```

**Comment by jonohodgson** [comment]
Thanks for the reply. Yeah that's exactly what I was doing. I can embed the Youtube video in a WebView and it plays, but when I use react-native-youtube I get the error on Android.

**Comment by morelazers** [comment]
Hm, you have definitely made sure everything is linked etc? Sometimes rnpm will fail so it's best to double-check it all manually. And then make sure you're rebuilding the project with `react-native run-android`
