### ISSUE TITLE
How make audio play when in background 

### ISSUE THREAD

**Issue by maivo** [inProgress-team/react-native-youtube#54]
I followed the instructions to enable the background audio:
1)  project->capabilities->background mode to ON and Audio and Airplay 
2) add code in AppDelegate.m:
     [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord error:&sessionError];
reference: https://github.com/youtube/youtube-ios-player-helper/issues/38

But when I press the home button, the sound stops when the app goes into background state.

Any ideas how to enable the Youtube video  audio to still play when the app goes into the background state?

**Comment by simonvaucher** [comment]
Playing sound when app is in background is forbidden by YouTube's policy. Yeah, there are apps out there that do it anyway, but that's against multiple terms under the "Prohibitions" section: https://developers.google.com/youtube/terms

**Comment by Mokto** [comment]
thanks for the answer @simonvaucher ;)
