### ISSUE TITLE
modestBranding option set to true does not hide the youtube logo

### ISSUE THREAD

**Issue by SpecialDOS** [inProgress-team/react-native-youtube#55]
setting this property doesn't seem to change anything. I tried camel case as specified in the readme, and also tried modestbranding all lowercase, neither hides the branding.

Thanks

**Comment by mcatmos** [comment]
Ive got the same issue! :(

**Comment by SpecialDOS** [comment]
Oh, I figured this out, should have posted an update. Setting modest branding to true does nothing  when showinfo is false, the two are mutually exclusive. When show info is true then setting modestbranding true hides a youtube link that shows up as part of the info bar. Basically, youtube is forcing you to either show the info bar at the top, or the youtube logo bottom right, you can't hide both of them. This is a limitation of the youtube iframe player itself, not of the react-native-youtube component.

**Comment by keyurparalkar** [comment]
I am unable to hide the youtbe button which is present at the bottom right of the video. Even when i set
modestbranding={true} and showinfo={false} still I am not able to remove the youtube button ?
