### ISSUE TITLE
Videos with content restrictions will not load anything.

### ISSUE THREAD

**Issue by wski** [inProgress-team/react-native-youtube#56]
For example videos from VEVO (similar to slack) will not play on the player. This is somehow bypassed in apps like Discord. It might be possible to implement whatever discord has done to bypass this for a more seamless experience. 

I will investigate further and try my best to offer a PR but wanted to open an issue to see if this is something that has already been brought up / addressed.

**Comment by jnelken** [comment]
Hi @wski ,

Try setting the `origin` prop to `"http://www.mydomain.com"` on your component. I had the same issue before, and found out that Youtube videos with blacklists will auto-blacklist your app if you don't provide any originating domain. If you don't own a domain, you can try adding something else in that field. 

This will provide a domain to check against the blacklist, and keep your app from being auto-blacklisted (from having no domain at all).

**Comment by wski** [comment]
@jnelken cool thanks, will give that a shot! I'm curious how they validate that though, since the app is technically not running on a domain.

**Comment by jnelken** [comment]
I'm curious too @wski . Let me know how it goes for you!
