### ISSUE TITLE
npm install failed with errors. 

### ISSUE THREAD

**Issue by vettukal** [inProgress-team/react-native-youtube#57]
I tried to do npm install on the Example dir. It failed with the following log:

> 12 warnings and 14 errors generated.
> make: **\* [Release/obj.target/validation/src/validation.o] Error 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/Users/16527/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
> gyp ERR! System Darwin 15.4.0
> gyp ERR! command "/Users/16527/.nvm/versions/node/v6.2.1/bin/node" "/Users/16527/.nvm/versions/node/v6.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /Users/16527/ios/dir2/RCY2/react-native-youtube/Example/node_modules/utf-8-validate
> gyp ERR! node -v v6.2.1
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok 
> npm WARN install:utf-8-validate@1.1.0 utf-8-validate@1.1.0 install: `node-gyp rebuild`
> npm WARN install:utf-8-validate@1.1.0 Exit status 1

**Comment by mcatmos** [comment]
Try doing rnpm ;) like the documentation says.

**Comment by vettukal** [comment]
I was trying to run the Example project provided in source. Documentation to run it is:
```
git clone git@github.com:paramaggarwal/react-native-youtube.git
cd react-native-youtube/Example
npm install
open RCTYouTubeExample.xcodeproj
```

Should I do rnpm instead of install here?

**Comment by sibelius** [comment]
@vettukal yeah, u should

did u solve the issue?

can u close this?

**Comment by vettukal** [comment]
If its a typo in the documentation then please close the issue.
