### ISSUE TITLE
YouTube IOS not working - Warning generated: "type should not be null"

### ISSUE THREAD

**Issue by savioseb** [inProgress-team/react-native-youtube#59]
I used this module before with RN v0.24.1 & react-native-youtube v0.6.0.

But I recently updated to RN v0.31.0 & react-native-youtube v0.7.2 and I can't play YouTube Videos anymore in my app.

I'm not sure what I'm doing wrong. Please advice.

This is the warning Screenshot:
![screen shot 2016-08-12 at 5 35 10 pm](https://cloud.githubusercontent.com/assets/698524/17621807/95912d00-60b3-11e6-84b5-e2be814b4c2d.png)

```
ExceptionsManager.js:76 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).
```

**Comment by sibelius** [comment]
@savioseb could u try the latest release? it is fixed for >=RN33

**Comment by labithiotis** [comment]
I had this issue when I didn't link the native libraries correctly, followed the readme and works fine now.
