### ISSUE TITLE
Black screen when embedding youtube video

### ISSUE THREAD

**Issue by nancyhuynh** [inProgress-team/react-native-youtube#65]
Hi,

I just integrated react-native-youtube into my project and am seeing just a black background using the example snippet. I am using react-native 0.34.0. Is there something wrong with the snippet?

```
render() {
    return (
      <YouTube
        ref="youtubePlayer"
        videoId="CebcmJKutaQ" // The YouTube video ID
        play={true}           // control playback of video with true/false
        hidden={false}        // control visiblity of the entire view
        playsInline={true}    // control whether the video should play inline
        loop={false}          // control whether the video should loop when ended

        style={{alignSelf: 'stretch', height: 300, backgroundColor: 'black', marginVertical: 10}}
      />
    );
  }
```

![image](https://cloud.githubusercontent.com/assets/12261742/18529556/8eac9f68-7a9b-11e6-8914-695595c37ba2.png)

**Comment by nancyhuynh** [comment]
More info:

I get the the following warning in console:
```
ExceptionsManager.js:82 Warning: Native component for "RCTYouTube" does not exist
```

I used rnpm to link the library, and RCTYouTube appears in my project.

Also, none of the following callbacks get triggered:

```
<YouTube
        ref="youtubePlayer"
        videoId="CebcmJKutaQ" // The YouTube video ID
        play={true}           // control playback of video with true/false
        hidden={false}        // control visiblity of the entire view
        playsInline={true}    // control whether the video should play inline
        loop={false}          // control whether the video should loop when ended

        onReady={(e)=>{ console.log('YOUTUBE READY', e)}}
        onChangeState={(e)=>{ console.log('YOUTUBE CHANGE STATE', e) }}
        onChangeQuality={(e)=>{ console.log('YOUTUBE CHANGE QUALITY', e) }}
        onError={(e)=>{ console.log('YOUTUBE ERROR', e) }}
        onProgress={(e)=>{ console.log('YOUTUBE PROGRESS', e)}}

        style={{alignSelf: 'stretch', height: 300, backgroundColor: 'black', marginVertical: 10}}
      />
```

**Comment by adeebbasheer** [comment]
<YouTube ref="youtubePlayer"
            videoId={this.props.item.id.videoId} // The YouTube video ID
            apiKey={Config.youtube.apiKey}
            onReady={(e)=>{}}
            onChangeState={this._onStateChange}
            onError={(e)=>{console.log(e);}}
            onProgress={(e)=>{}}
            style={[{alignSelf: 'stretch', backgroundColor: 'black', marginVertical: 10}]} />

**Comment by mahyarse** [comment]
@nancyhuynh did you find out the reason by any chance?

**Comment by nancyhuynh** [comment]
@mahyarse unfortunately, I did not. I ended up just using a WebView instead, which suits our current needs:

```
<WebView
  source={{ uri: `https://www.youtube.com/embed/${this.props.item.videoId}` }}
/>
```

**Comment by onpaws** [comment]
`ExceptionsManager.js:82 Warning: Native component for "RCTYouTube" does not exist`

Just saw this error. For me it wasn't enough to simply use `rnpm` because it didn't include `RCTYouTube.a` in the linker. I was able to fix by double checking the library was included over in the target's Build Phases (same process as described in the linking [docs](https://facebook.github.io/react-native/docs/linking-libraries-ios.html).

![image](https://cloud.githubusercontent.com/assets/182515/18807353/971e373c-8212-11e6-82cd-c234557b3088.png)

**Comment by onpaws** [comment]
Don't forget to include `Assets/YTPlayerView-iframe-player.html` in the Xcode project.
Without this file you'll get an error like the following in Console.app, and no errors in JavaScript:
`Received error rendering template: Error Domain=NSCocoaErrorDomain Code=258 "The file name is invalid."`

**Comment by jreziga** [comment]
Same problem on Android

**Comment by gauravsbagul** [comment]
> `ExceptionsManager.js:82 Warning: Native component for "RCTYouTube" does not exist`
> 
> Just resolved this error. For me it wasn't enough to simply use `rnpm` because it didn't include `RCTYouTube.a` in the linker. I was able to fix by double checking the library was included over in the target's Build Phases (same process as described in the linking [docs](https://facebook.github.io/react-native/docs/linking-libraries-ios.html).
> 
> ![image](https://cloud.githubusercontent.com/assets/182515/18807353/971e373c-8212-11e6-82cd-c234557b3088.png)

I did the same but still getting the same error 
`Invariant Violation: requireNativeComponent: "RCTYouTube" was not
![Screenshot 2020-02-29 at 4 51 39 PM](https://user-images.githubusercontent.com/25247251/75606542-d1c3d580-5b13-11ea-8e03-d02e27199ccf.png)
 found in the UIManaager.
