### ISSUE TITLE
Error while linking the package in Android

### ISSUE THREAD

**Issue by chetnadaffodil** [inProgress-team/react-native-youtube#68]
**Please mention the package to import in MainApplication.java in your docs**
![screenshot from 2016-09-28 15 17 55](https://cloud.githubusercontent.com/assets/17562095/18908818/c3be75f2-858e-11e6-800b-bc1d9f5f21c5.png)

**Comment by jujumoz** [comment]
`import com.inprogress.reactnativeyoutube.ReactNativeYouTube; `
I will add it to "README.md". ;)
