### ISSUE TITLE
Error in Andriod: Attempt to invoke virtual method on a null reference

### ISSUE THREAD

**Issue by chetnadaffodil** [inProgress-team/react-native-youtube#69]
![screenshot from 2016-09-28 15 31 06](https://cloud.githubusercontent.com/assets/17562095/18909478/610c5aca-8591-11e6-8996-486c599fc2f3.png)
With the following dependencies
"react": "^0.14.8",
"react-dom": "^15.3.1",
"react-native": "^0.32.0",

![screenshot from 2016-09-28 15 31 06](https://cloud.githubusercontent.com/assets/17562095/18909323/c3ece1ce-8590-11e6-8a9f-362f78bcc63a.png)

**Comment by jujumoz** [comment]
It does work with the following dependencies :
 "react": "15.3.2",
 "react-native": "^0.34.1",

**Comment by chetnadaffodil** [comment]
Re-installed the package.. but the issue persists. I'm using your example as mentioned.

**Comment by machei** [comment]
Here same

**Comment by machei** [comment]
Here solved after upgrading react-native.

**Comment by gendeld** [comment]
Same problem here
