### ISSUE TITLE
Black screen on Android

### ISSUE THREAD

**Issue by jreziga** [inProgress-team/react-native-youtube#78]
Hello,

I'm trying to run this module on Android but I just have a black screen... Is this a known issue ?

Thanks !

**Comment by machei** [comment]
I have same issue:
```
YouTube video playback stopped due to unauthorized overlay on top of player. The YouTubePlayerView is not contained inside its ancestor android.widget.FrameLayout{a38d0a1 V.E..... ......I. 0,0-0,0}. The distances between the ancestor's edges and that of the YouTubePlayerView is: left: 0, top: 0, right: 0, bottom: 0 (these should all be positive)
```

**Comment by ManiSJ** [comment]
@machei How to resolve it? I got black screen also. Do we need to add left: 0, top: 0, right: 0, bottom: 0 in style of Youtube

**Comment by machei** [comment]
@ManiSJ I gave up with that, i made own script for printing thumbnail with action click for opneing new instance.

**Comment by jreziga** [comment]
You have another workaround. Try like with a WebView like that: 

```js
<WebView source={{ uri: `https://www.youtube.com/embed/Gr2DAGkQdjU?version=3&autoplay=0&showinfo=0&controls=0&modestbranding=1&fs=1&rel=0` }} />
```
on Android no fullscreen but on iOS a native player is available.

**Comment by machei** [comment]
@jreziga Try make example using side bar navigation.

**Comment by mp31415** [comment]
Sorry if it's obvious, but when I run an app with react-native-youtube in stock android emulator (where there is no YouTube app installed), I see the black screen in YouTube frame, If the same app is deployed on a real device YouTube video is loaded correctly.

**Comment by davidohayon669** [comment]
@mp31415 You have to have a YouTube app installed on the emulator as well.
Its a simple .apk file that you can find with a short google search (make sure it fits your emulators architecture) and then install it to the emulator with `adb install`

**Comment by ManiSJ** [comment]
@davidohayon669 Thanks it works now in android.

Downloaded Youtube apk file and followed steps in this https://www.youtube.com/watch?v=fSRAu6W1y0c

**Comment by jreziga** [comment]
But what if user's devices don't have Youtube application installed ?

**Comment by machei** [comment]
Then do modify this plugin, just make popup with text like "required youtube application" after pressing on view or just do make place simply message to view if user hasnt installed youtube.

This feature should be added to this plugin.

**Comment by jreziga** [comment]
@machei that's a terrible idea. So this module isn't working out of the box. First time I see a module which has a dependency on an .apk file... (i.e another app) I'll use WebView instead, more suitable for my needs. Thanks by the way ! I'm closing it now.
