### ISSUE TITLE
iOS Blank/Black Screen - How do I add YTPlayerView-iframe-player.html from Assets to my xcode project?

### ISSUE THREAD

**Issue by quadsurf** [inProgress-team/react-native-youtube#79]
All I get is a blank black screen, so I'm guessing it's because I didn't drag n drop the iframe html into the correct xcode location.

How do I add YTPlayerView-iframe-player.html from Assets to my xcode project?

Sorry, as a brand new developer, this is not entirely clear to me. Did rnmp do this for me? Or do I need to manually do this after running rnmp command? And if manually, how?

Just drag and drop? And if so, where? In the root dir of xcode proj? Or in one of the sub-dirs? Do I need to create references? And if so, how?

I am running RN 0.32.0

**Comment by CharlesMcD** [comment]
Follow these steps (WatchNext is my project name) : 

![capture d ecran 2016-10-08 a 19 06 42 - copie](https://cloud.githubusercontent.com/assets/6673075/19216469/094c296c-8d8b-11e6-9c4e-470c2a3743e7.png)

![capture d ecran 2016-10-08 a 19 06 58](https://cloud.githubusercontent.com/assets/6673075/19216470/0ef89e0e-8d8b-11e6-9b1b-2c51710dcdc9.png)

![capture d ecran 2016-10-08 a 19 07 29](https://cloud.githubusercontent.com/assets/6673075/19216471/12221380-8d8b-11e6-8257-34fbe193afb0.png)

**Comment by quadsurf** [comment]
Thank you @CharlesMcD ... it worked perfectly and beautifully after I followed your tutorial, and what's even better, is that the whole component re-renders whenever I dynamically pass it a new youtube id, so no extra voodoo needed to refresh the YouTube component, woohoo!

**Comment by ruk91** [comment]
Thanks @CharlesMcD . You saved my time
