### ISSUE TITLE
Reset to Original Play Screen When Video Finishes?

### ISSUE THREAD

**Issue by joncursi** [inProgress-team/react-native-youtube#80]
Is there a way to reset the video state to the first frame once the video finishes playing through? Currently it show a browse screen for more videos, but I only want this one video to be available. Do I need to manually re-mount the entire component?

![screen shot 2016-10-11 at 1 23 36 am](https://cloud.githubusercontent.com/assets/4974609/19259628/61ae1698-8f51-11e6-8c22-c0a0a0955da0.png)

**Comment by IjzerenHein** [comment]
I think that setting  the `rel` prop to false will solve your problem:
https://github.com/inProgress-team/react-native-youtube#properties

**Comment by joncursi** [comment]
That did it, thank you! Not sure how I missed that.
