### ISSUE TITLE
modestbranding does not remove YouTube Logo Watermark

### ISSUE THREAD

**Issue by fostertime** [inProgress-team/react-native-youtube#81]
The YouTube Watermark remains, even when setting modestbranding={true}.  I believe it might be related to how the playerVars are set in the .html file?

**Comment by fostertime** [comment]
If anyone else is wondering about this... its due to the fact you cannot have `showinfo={false}` AND `modestbranding={false}` ... apparently Google/YouTube allows only one of those options to be set. More info at: http://stackoverflow.com/a/35174042/6019768 closing this issue! :)

**Comment by keyurparalkar** [comment]
I am unable to hide the youtbe button which is present at the bottom right of the video. Even when i set
modestbranding={true} and showinfo={false} still I am not able to remove the youtube button ?
