### ISSUE TITLE
Video keeps loading

### ISSUE THREAD

**Issue by juangl** [inProgress-team/react-native-youtube#82]
As you can see below, the video just never start.

I'm not sure if I set my APIKey correctily. In fact, is the fist time that I do this, so could you tell me if that behavior is due APIKey.

When app loads the video is opened in fullscreen (this is weird for me). You can see in the bottom of the player shows "Anuncio" that means "Ad".

![screenshot_2016-10-18-15-32-12](https://cloud.githubusercontent.com/assets/1887029/19496381/e2ab3aea-954c-11e6-9cf3-2b2bd8eebad4.png)

**Comment by mp31415** [comment]
I see this behaviour when play property in YouTube element is set to false initially. Setting it to true fixes the problem. Weird.

**Comment by kt3k** [comment]
I saw the same issue on Android and @mp31415 's solution (`<Youtube play={true} .../>`) worked in my case. Thanks!

**Comment by juangl** [comment]
Yeah. It works. I think I sound keep open this issue until that unexpected behavior is fixed.

**Comment by Jarrio** [comment]
Can confirm this is still an issue on the `v1` branch

**Comment by davidohayon669** [comment]
@Jarrio @juangl I'm not sure I understand the problem. Do you set `play={true}` and still no video plays?

**Comment by Jarrio** [comment]
Starting the player with `play=false` leads to perpetual loading which can never be updated or started
