### ISSUE TITLE
Rotate on Full Screen

### ISSUE THREAD

**Issue by mshaaban0** [inProgress-team/react-native-youtube#84]
Hi Guys,
Thank you for the good work.
How can i rotate the player on full screen, something like the youtube experience ?

I am wondering if it's not doable currently, just if you guys can help me with the logic.

thanks

**Comment by Liroo** [comment]
https://github.com/yamill/react-native-orientation and change the style of the player.
Be careful of the react-native-orientation npm version, only the github is updated

**Comment by cihancil** [comment]
@Liroo How do you use react-native-orientation with player?



 Player does not have any events to detect full screen.

**Comment by Liroo** [comment]
I implemented one fully JS (react-native-orientation has listeners for rotate event).. But there is definitivly not the right way to do.
This should be implemented in Native, you could wait or try to do your own module or PR this one ;)
@cihancil

**Comment by jujumoz** [comment]
@mshaaban0 You want the player to rotate when the device rotates while in fullscreen, right ?

**Comment by mshaaban0** [comment]
@jujumoz no, i want the player in full screen on play without orientation [check here](https://github.com/inProgress-team/react-native-youtube/issues/87)

**Comment by Liroo** [comment]
Youtube player does not work like this... It detect orientation and play fullscreen only in landscape mode or if you press fullscreen button.

And what do you want is a view rotate by 90 degrees and position absolute left, right, top, bottom 0

**Comment by mshaaban0** [comment]
@Liroo actually you are right, my mistake. i did try to do it but my obj-c skills are very low. i will try to give it another try soon. 👍

**Comment by Liroo** [comment]
@mshaaban0 anyway, I dont think react native has any stable video player actualy :/

**Comment by superandrew213** [comment]
> @mshaaban0 You want the player to rotate when the device rotates while in fullscreen, right ?

@jujumoz why was this closed? Isn't this something that should we should add? At least for iOS. On Android full screen goes straight into landscape mode.

**Comment by wellyshen** [comment]
@jujumoz We really need this feature, currently (react-native-orientation)[https://github.com/yamill/react-native-orientation] seems not working for RN 0.42.0 and later... If the feature can be included in this library it will be awesome!

**Comment by jeanregisser** [comment]
On iOS you can easily allow landscape mode for videos playing in a webview (that's what this library does) even if the rest of the app is portrait mode only.

See http://stackoverflow.com/a/28467104/158525
