### ISSUE TITLE
Android Issues

### ISSUE THREAD

**Issue by wski** [inProgress-team/react-native-youtube#85]
@Override
    protected YouTubeView createViewInstance(ThemedReactContext themedReactContext) {
        mYouTubeView = new YouTubeView(themedReactContext, themedReactContext.getCurrentActivity());
        return mYouTubeView;
    }

Is causing issues in RCTYouTube\src\main\java\com\inprogress\reactnativeyoutube\YouTubeManager.java because Error:(44, 78) error: cannot find symbol method getCurrentActivity()

**Comment by minhcasi** [comment]
got the same issue:

:RCTYouTube:compileReleaseJavaWithJavac
/Users/minh/Documents/Projects/BeoNews/node_modules/react-native-youtube/RCTYouTube/src/main/java/com/inprogress/reactnativeyoutube/YouTubeManager.java:44: error: cannot find symbol
        mYouTubeView = new YouTubeView(themedReactContext, themedReactContext.getCurrentActivity());
                                                                             ^
  symbol:   method getCurrentActivity()
  location: variable themedReactContext of type ThemedReactContext
Note: /Users/minh/Documents/Projects/BeoNews/node_modules/react-native-youtube/RCTYouTube/src/main/java/com/inprogress/reactnativeyoutube/YouTubeManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:RCTYouTube:compileReleaseJavaWithJavac FAILED

Please help to fix :)

**Comment by jujumoz** [comment]
@minhcasi @wski Which version of RN are you using ?

**Comment by minhcasi** [comment]
I've used the version of 0.39

**Comment by denny64** [comment]
I'm getting the same error. Any updates on this issue?

**Comment by denny64** [comment]
Figured it out..

In `android/build.gradle`, change your react-native node_modules path to the root directory.

```
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

**Comment by bendellarocco** [comment]
I am getting this issue with RN 0.39.  @denny64s fix did not solve the issue

**Comment by bendellarocco** [comment]
Was there a resolution to this issue?
