### ISSUE TITLE
Not working with react-native listview (android)

### ISSUE THREAD

**Issue by manjeet-dobble** [inProgress-team/react-native-youtube#86]
this plugin is not functional in android while using within listview, it is working fine without listview but don't know what makes it to break with listview, see error in 

Error- binary xml file line  #10 :Binary XML file line#10 :Error inflating class fragment.

I searched a little bit and come to know that this issue is related with fragment being inflated within fragment(listview item may be a fragment), it may be related to following code in YoutubeView.java

`public void init() {
        inflate(getContext(), R.layout.youtube_layout, this);
        youTubePlayerFragment = (YouTubePlayerFragment) mMainActivity.getFragmentManager()
                .findFragmentById(R.id.youtubeplayerfragment);
        youtubeController = new YouTubePlayerController(mMainActivity, YouTubeView.this);
}
` 
I gone through little bit of youtube api documentation and come to know that we can use YouTubePlayerView as an alternative of YouTubePlayerFragment, I am willing to modify this library on my machine but don't have much knowledge of android and hence unable to decide how should I proceed, any help regarding this issue or how should I proceed doing this will be appreciated, wanted to know how this react-native library be tested within android studio(if possible)

**Comment by davidohayon669** [comment]
Im finishing work on an 1.0.0-alpha.1 version that address this issue as well

Will publish pull request these next few days

**Comment by manjeet-dobble** [comment]
@davidohayon669  that will be great

**Comment by tonygriv** [comment]
@davidohayon669, how are you getting on with new version?

**Comment by davidohayon669** [comment]
@tonygriv a matter of 3-4 days
Tons of stuff to improve so hang on :-)

**Comment by davidohayon669** [comment]
@tonygriv I've published a new branch to my fork #94, now it depends on the maintainers
