### ISSUE TITLE
Not Auto FullScreen

### ISSUE THREAD

**Issue by YuanSyun** [inProgress-team/react-native-youtube#95]
OS：Windows 10
Development platform：Android
React Native ： 0.39.2
Date：2016/12/28
------------------------------------------
File location：
node_modules\react-native-youtube\RCTYouTube\src\main\java\com\inprogress\reactnativeyoutube\YouTubePlayerController.java

```
@Override
    public void onInitializationSuccess(YouTubePlayer.Provider provider, YouTubePlayer youTubePlayer, boolean wasRestored) {
        if (!wasRestored) {
            mYouTubePlayer = youTubePlayer;
            mYouTubePlayer.setPlayerStateChangeListener(this);
            mYouTubePlayer.setPlaybackEventListener(this);

            mYouTubePlayer.setFullscreen( false ); //Modify it here

            updateControls();
            mYouTubeView.playerViewDidBecomeReady();
            setLoaded(true);
            if (videoId != null && isPlay()) {
                startVideo();
                mYouTubePlayer.setFullscreen(false);
            }
        }
    }
```

**Comment by agilecollab** [comment]
While this does fix the auto loading into full screen and then the snap back to portrait orientation the video plays but only shows a black box...that is until the devices is switched to landscape and then back. any ideas why that might be?

**Comment by davidohayon669** [comment]
Solved in v1
Next time suggest a PR
