### ISSUE TITLE
Cannot get it to load on Geny Motion

### ISSUE THREAD

**Issue by denny64** [inProgress-team/react-native-youtube#97]
How do I get the YoutubePlayer to load on the Geny motion simulator? It says "Error initializing youtube"

I'm currently using the Google Nexus 6P - 6.0.0 - API 23 device

**Comment by morelazers** [comment]
@denny64 Have you provided an apiKey prop?

**Comment by denny64** [comment]
@morelazers Yep, apiKey is there. After doing some digging, it appears that Geny Motion simulators don't have Google Play Services installed, which may be why it doesn't work? Although when I tried it on a real device, the youtube player crashes

**Comment by morelazers** [comment]
Yeah I got stuck putting google play services on genymotion emulator and ended up just using the one which comes with Android Studio instead (which is actually way faster for me). You can download the Google APIs through the SDK manager in there and assign them to your emulators.

Do you have an error message for the crash? It's a while since I used the module but I'll try to help out if I can

**Comment by denny64** [comment]
@morelazers - Just tried it with the Android studio simulator, turns out I get the same "An error has occurred while initializing the Youtube Player" issue. Maybe my apiKey is incorrect. I've enabled Youtube Data API in my Google Console, and have created an API key. Am I missing something?

**Comment by morelazers** [comment]
Are you sure you have enabled the Google APIs image for the emulator? You might also have to have the YT app installed on the device.

Here's the code that worked for me:

```
          <YouTube
            ref="youtubePlayer"
            videoId={videoId}     // The YouTube video ID
            play={false}          // control playback of video with true/false
            hidden={false}        // control visiblity of the entire view
            playsInline={true}    // control whether the video should play inline
            loop={false}          // control whether the video should loop when ended
            modestbranding={true}
            apiKey={"MY_API_KEY"}
            style={{alignSelf: 'stretch', height: 300, backgroundColor: 'black', marginVertical: 10}}
          />
```

**Comment by denny64** [comment]
The error appears to be something to do with the fullscreen functionality. Every time it goes full screen, the app crashes. Any ideas?

**Comment by morelazers** [comment]
Can't say I have any off the top of my head. Are you able to get a stacktrace from android monitor?

**Comment by denny64** [comment]
@morelazers Turns out to be an issue with how our router was structured.. Thanks for your help though!
